### ISSUE TITLE
3.5 Branch

### ISSUE THREAD

**Issue by Givemeyourgits** [libgit2/libgit2sharp#1006]
Any chance of getting a 3.5 branch?
I would really love to use this for a project, but I am limited to .net 3.5 framework.

**Comment by nulltoken** [comment]
We've actually moved away from 3.5 last year (cf. #580, #654, #678)

We've held on the decision for some time (comparing the number of deployed version of .Net 4.0 compared to the number of 3.5), tweeted about this (https://twitter.com/libgit2sharp/status/446662964612194304) but only got positive feedback about moving away from 3.5.

**Comment by Givemeyourgits** [comment]
Unfortunately Unity3D refuses to pay the licensing fees to Mono, so we stuck on 3.5.  Seems all Git libs running on 4.x now as well.  I figured it was the case but wanted to check.  I saw a bunch of errors, so I suspect it would be a bunch of work to backport it.

Thanks, it looks like a big time saver too.

**Comment by nulltoken** [comment]
Actually most of the update has been done in #678. Maybe could you take a look at it, reintroduce the `Compat` layer and maintain your own fork?

**Comment by nulltoken** [comment]
>Unfortunately Unity3D refuses to pay the licensing fees to Mono, so we stuck on 3.5. 

/cc @Therzok @joncham

**Comment by Therzok** [comment]
Mono 4 drops support for 3.5 and lower frameworks - so further mono releases will not support 3.5 anyway. 3.x is the last mono version that would support that.

I have no idea about Unity's own fork and the license fees mentioned.

**Comment by Givemeyourgits** [comment]
They on a customized version of 2, which is right before the improved garbage collector.  It's pretty old and almost every one has moved on to requiring 4+.

Thanks though NullToken, I'll look at an older build and maybe fork that but likely I will just work with the Lib2Git directly, as I don't need much functionality, just the core stuff.

**Comment by ZimM-LostPolygon** [comment]
For anyone still interested, I've created a 3.5 backport fork:
https://github.com/LostPolygon/libgit2sharp

**Comment by drok** [comment]
> For anyone still interested, I've created a 3.5 backport fork:
> https://github.com/LostPolygon/libgit2sharp

Thank you for sharing your backport, LostPolygon, it is brilliant work and I'm looking to use it for the same reason @Givemeyourgits mentioned above (I need to use it with a Unity 5.6 project, ie, Mono/.Net 3.5).

My question is: are you planning on updating the backport further to bring it up to date with the libgit2 project?
If not, I'll have to attempt this work; if you have any tip I'd appreciate them; would this be fairly straight forward, or is there some significant roadblock to updating the backport?

**Comment by ZimM-LostPolygon** [comment]
No, I won't be updating the backport. I'd encourage you to attempt it, I believe there won't be any major roadblocks, it's more of a tedious job than it is difficult.
