### ISSUE TITLE
Get a CoreCLR build bot.

### ISSUE THREAD

**Issue by Therzok** [libgit2/libgit2sharp#1019]
I think we should also test this as a target.

**Comment by carlosmn** [comment]
Do we know of a hoster that does this? Does someone have Debian packages we can install?

**Comment by Therzok** [comment]
I'm going to `time` the time it takes to build coreclr itself and mess with it a bit.

**Comment by Therzok** [comment]
We'd still need assemblies from corefx. Hmmm, this is going to be tricky.

**Comment by Therzok** [comment]
It took 10 mins more or less to build coreclr from source. But we need some place to get the assemblies libgit2sharp uses. Any ideas? We could make a nuget package with the corefx assemblies we and our dependencies use.

**Comment by bording** [comment]
Why would we need to build CoreCLR from source? Couldn't we just use dnvm to grab everything we need?

https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-dnx-linux.md
https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-dnx-osx.md
https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-dnx-windows.md

On the windows side, AppVeyor already has Visual Studio 2015 RC, so we'd probably be able to skip some steps there.

xUnit already has a dnx test runner too:
https://github.com/xunit/dnx.xunit

**Comment by bording** [comment]
I spent some time this weekend digging into the dnx/coreCLR stuff, and started trying to get things up with the new dnx project system, etc. There are some pretty cool things the new project.json format enables, like easily targeting multiple frameworks simultaneously, but there are also a few things it doesn't support. For example, none of the stuff that gets done via msbuild targets currently will work in the new system.

In general, it looks like running on coreCLR is going to be tough at the moment. It looks like there is a decent amount of stuff that isn't in there (yet?), including a lot of marshaling stuff.

Take a look at the `bording/dnx` branch to see what I've got so far.

**Comment by bording** [comment]
Looking through the dotnet/corefx repo, I found several open issues related to things that LibGit2Sharp uses that aren't currently supported on CoreCLR:

dotnet/corefx#1345
dotnet/corefx#1346
dotnet/corefx#1347

**Comment by Kukkimonsuta** [comment]
There is really just one blocking issue and that's missing `ICustomMarshaller`. There was no reaction yet on whether it will be added or not.

Binary serialization seem to be only used for exceptions in `LibGit2Sharp` to conform to standards, so just not implementing it when targeting CoreCLR should work just fine.

As for CERs, there's likely no need for them (see reply in [dotnet/corefx#1345](https://github.com/dotnet/corefx/issues/1345)).

There are few other things that are missing in CoreCLR, like getting home folder and environment variables, but it's been a while since I played with it, so they may have been added or there may be other way to get them.

**Comment by AArnott** [comment]
BTW, supporting CoreCLR is a very different thing than building on it or using DNX. I see remarks above about project.json and losing MSBuild. These things are not necessary. You can target CoreCLR, build with MSBuild, and run on desktop, Mac, and Linux within a project that is any of these.
