### ISSUE TITLE
Filter Support Redux

### ISSUE THREAD

**Issue by shiftkey** [libgit2/libgit2sharp#1025]
So we currently have #854 in-flight which was paused due to the work upstream in https://github.com/libgit2/libgit2/pull/2911 to add in streaming filter support.

I've grabbed this PR, rebased it on top of vNext and am working through the necessary changes. Once I'm happy with the passing tests, I'll grab some of @ammeep's time to get a :thumbsup: and she can finish up this PR.

Anyway, a couple of questions while I'm working through tests:

- the proxy method for `git_buf_put` doesn't exist - should I submit a PR for this patch https://github.com/libgit2/libgit2/commit/a2012c4?
- I'm seeing a bunch of  `LibGit2Sharp.EntryExistsException : A filter with the name 'cipher-filter' is already registered` in tests - not sure what's changed - thoughts? 

cc @ethomson

**Comment by nulltoken** [comment]
>- the proxy method for `git_buf_put` doesn't exist - should I submit a PR for this patch https://github.com/libgit2/libgit2/commit/a2012c4?

This has been surperseded by https://github.com/libgit2/libgit2/pull/2911

>- I'm seeing a bunch of  `LibGit2Sharp.EntryExistsException : A filter with the name 'cipher-filter' is already registered` in tests - not sure what's changed - thoughts? 

That may be related to failing tests that do not properly cleanup their previously registered filter

**Comment by shiftkey** [comment]
@nulltoken

> This has been surperseded by libgit2/libgit2#2911

So no more `GitBufReadStream` and `GitBufWriteStream`, and instead using `buf_stream_write`? 

> That may be related to failing tests that do not properly cleanup their previously registered filter

I thought that might be the case but the first test would fail even after restarting VS. I'll keep digging.
