### ISSUE TITLE
Windows file path not supported?

### ISSUE THREAD

**Issue by mkliu** [libgit2/libgit2sharp#1027]
I'm trying to clone a repo
  
    var repoUrl = "xxx";
    var repoDir = "D:\\a";
    Repository.Clone(repoUrl, repoDir);

But it says:

Unhandled Exception: LibGit2Sharp.NotFoundException: Path is not a directory 'D:': The filename, directory name, or volume label syntax is incorrect.

**Comment by ethomson** [comment]
What version of LibGit2Sharp are you running?  (I ask because this sounds like https://github.com/libgit2/libgit2/pull/2880 )

**Comment by mkliu** [comment]
will check on the machine when i go back for the exact version, but should be the newest from nuget since i added it this afternoon just now. Any work arounds?

**Comment by mkliu** [comment]
i upgraded to pre, now it's using LibGit2Sharp 0.22.0-pre20150415174523. The problem is fixed.
However, is it safe to use this version?

**Comment by nulltoken** [comment]
>However, is it safe to use this version?

@mkliu Although this is a prerelease NuGet package, it is safe to use it.

Thanks for this report!

**Comment by taspeotis** [comment]
I hit this issue and now I'm waiting for v0.22 of libgit2sharp.

It's easily worked around though: instead of `X:\Temp` use `X:\Temp\.`

**Comment by ethomson** [comment]
[LibGit2Sharp v0.22](https://github.com/libgit2/libgit2sharp/releases/tag/v0.22) was already released.
