### ISSUE TITLE
Support `--patience` flag of `diff-tree` command

### ISSUE THREAD

**Issue by dmalikov** [libgit2/libgit2sharp#1037]
Currently `Diff.Compare<Patch>` method doesn't support `--patience` flag, thus it's impossible to implement git command like that using the library:

    git diff-tree T1 T2 --patience

**Comment by Therzok** [comment]
The flags are binded [here](https://github.com/libgit2/libgit2sharp/blob/a026f5d84e35f1df94bc3f30503429ef8a216209/LibGit2Sharp/Core/GitDiff.cs#L173-L178).

I guess it's just a matter of exposing this data in [CompareOptions](https://github.com/libgit2/libgit2sharp/blob/a026f5d84e35f1df94bc3f30503429ef8a216209/LibGit2Sharp/CompareOptions.cs#L8)

**Comment by nulltoken** [comment]
>I guess it's just a matter of exposing this data in [CompareOptions](https://github.com/libgit2/libgit2sharp/blob/a026f5d84e35f1df94bc3f30503429ef8a216209/LibGit2Sharp/CompareOptions.cs#L8)

Indeed!

Labeled as `up-for grabs`.

**Comment by dmalikov** [comment]
@nulltoken could you please explain a little bit what does "up-for-grabs" label actually mean?

**Comment by bording** [comment]
@dmalikov The idea behind that label comes from here: 

http://up-for-grabs.net/

**Comment by nulltoken** [comment]
@dmalikov This means that we would be interested in exposing this feature but, as it doesn't require a strong expertise to make it happen, core contributors will refrain from implementing it.

Indeed, it may be an easy first task for a new contributor willing to dabble with the library and we would happily support him/her until the feature's ready to be merged.
