### ISSUE TITLE
How to perform a push

### ISSUE THREAD

**Issue by nmartin867** [libgit2/libgit2sharp#104]
Does this library provide support for push?

**Comment by Cyberboss** [comment]
Any support for force push yet?

**Comment by ethomson** [comment]
Only via the `+` syntax mentioned above.

**Comment by felixfbecker** [comment]
Would be awesome to have a `PushOptions.Force` option to make this easier. Could that just adapt the refspec?

Is there a way to do `--force-with-lease`?

**Comment by iceicys** [comment]
Any chance there's an update that includes force push?
