### ISSUE TITLE
Add SecureString support for Credentials

### ISSUE THREAD

**Issue by ckuhn203** [libgit2/libgit2sharp#1048]
Credentials currently only support taking in username and password as plain text. Being able to pass a secure string in and have LibGit2Sharp handle the retrieval of the plain text as close as possible to it's use would improve security and centralize the action. Essentially moving the decryption responsibility from the client to the library where it can be handled in a correct way.

I'm thinking a new `SecureUsernamePasswordCrentials` class could be implemented relatively simply. It would be *very* similar to [the existing class][1]. Instead of a `System.String` for `Username` and `Password`, we would simply use a `SecureString` instead.

        /// <summary>
        /// Username for username/password authentication (as in HTTP basic auth).
        /// </summary>
        public SecureString Username { get; set; }

        /// <summary>
        /// Password for username/password authentication (as in HTTP basic auth).
        /// </summary>
        public SeucreString Password { get; set; }

The `GitCredentialHandler` override would be very similar to the existing implementation as well. This is where the `SecureString` would be converted to an unmanaged string to be passed along to the NativeMethods and immediately freed from memory once a credential is created.

I'm willing to do the work and submit a pull request if there is any interest in this.

Am I missing any caveats?
What kinds of tests would you like to see for this functionality?

[1]: https://github.com/libgit2/libgit2sharp/blob/a026f5d84e35f1df94bc3f30503429ef8a216209/LibGit2Sharp/UsernamePasswordCredentials.cs

**Comment by Therzok** [comment]
Imo, we already have credentials tests in place. What would need to be done is verifying that it works by setting the [credentials](https://github.com/libgit2/libgit2sharp/blob/0b3109048f0ec3ac8fd991370c40aba69526f742/LibGit2Sharp.Tests/TestHelpers/Constants.cs#L33) and the [url](https://github.com/libgit2/libgit2sharp/blob/0b3109048f0ec3ac8fd991370c40aba69526f742/LibGit2Sharp.Tests/TestHelpers/Constants.cs#L28)

**Comment by ckuhn203** [comment]
Thanks for the tip @Therzok.

**Comment by nulltoken** [comment]
>I'm willing to do the work and submit a pull request if there is any interest in this.

:+1: :sparkles: :tada:
