### ISSUE TITLE
Clone fails due to Unicode character in filename?

### ISSUE THREAD

**Issue by japj** [libgit2/libgit2sharp#1053]
Hi,

Just checking here since this might actually be a bug in libgit2sharp.
I am trying to clone the PTVS github project but it fails due to an Unicode filename issue.

See also
https://github.com/Microsoft/PTVS/issues/184

**Comment by ethomson** [comment]
If you're seeing a bug *in GitHub's Visual Studio integration*, please report that to GitHub.  It's very difficult to determine where in the stack a bug exists.  If there's a bug in libgit2, it will get appropriately routed to us (and hopefully even fixed!) by the team that actually owns the feature that you're using.

That said, please be clear when you do report a bug what you mean by "Unicode".  Windows users often say "Unicode" to mean "the mostly UTF-16 two-byte thing that Windows uses".  Git uses UTF-8 internally.  If you have some two-byte "Unicode" filename in your repository, then this is probably an error.

**Comment by shiftkey** [comment]
> If you're seeing a bug in GitHub's Visual Studio integration, please report that to GitHub.

support@github.com :grinning:

**Comment by ethomson** [comment]
That byte sequence is not valid UTF-8.  Appears to be a mangled filename in your repository and this does not appear to be an issue in libgit2 or LibGit2Sharp.  (Unless, of course, we were the ones that put that filename in the repository in the first place!)

Thanks!
