### ISSUE TITLE
SSH-Transport-Protocol functionality?

### ISSUE THREAD

**Issue by AJSclyn** [libgit2/libgit2sharp#1054]
I was wondering if this was ever implemented?  The latest update I found on the issue was here:
https://github.com/libgit2/libgit2sharp/pull/852

**Comment by Therzok** [comment]
It's still awaiting review and stalling for some reason.

**Comment by bording** [comment]
@Therzok At this point I think it's a bit of a race between #852 and #984. Whichever one lands second will have to account for changes in the first!

**Comment by Therzok** [comment]
Hah. I guess I'll have to update. :P

**Comment by AJSclyn** [comment]
Thanks for the replies.  I'm new to GitHub.  Is there a way to grab your update even if it's not implemented in the official build?

**Comment by bording** [comment]
@AJSclyn At this point you would have to build the branch from source yourself if you want to try it out.

The easiest way to do that would be to clone the repo and then checkout the therzok/sshAPI branch.

**Comment by carlosmn** [comment]
libgit2 and libgit2sharp do support SSH. The libgit2 we ship does not, as we do not want to ship 3rd-party crypto libraries in our package.
