### ISSUE TITLE
Ensure *nix builds fail at the first error

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#1055]
https://travis-ci.org/libgit2/libgit2sharp/jobs/63710116#L1492 shows that the NuGet restore has failed. However, the build script kept on running. Which makes the log hard to read and troubleshoot.

Is there any way to tweak those in order to make them stop on any error?

/cc @bording @carlosmn

**Comment by carlosmn** [comment]
You'd need `set -e` like we do in the installation scripts so that the shell script exits with an error if a command does.

**Comment by Therzok** [comment]
ORRRRR: decorate each call with `|| exit 1` :D
