### ISSUE TITLE
Commits log issue.

### ISSUE THREAD

**Issue by FeniXVRN** [libgit2/libgit2sharp#1074]
Hi.
I've tried to get commits for specific files, but every time i've got empty list.
There is a code sample:

```
var commits = repo.Commits.QueryBy(parameters.FilePath.Replace(_repository, "")).ToList();               

var lastCommit = commits.First().Commit;
var commitDate = DateTime.Now;
foreach (var commit in commits.Select(x => x.Commit))
{
    if (commit.Sha != lastCommit.Sha)
    {
        Tree commitTree1 = repo.Lookup<LibGit2Sharp.Commit>(lastCommit.Sha).Tree;
        Tree commitTree2 = repo.Lookup<LibGit2Sharp.Commit>(commit.Sha).Tree;
        string content = repo.Diff.Compare<Patch>(commitTree1, commitTree2).Content;
        if (content.Contains(parameters.TestName))
        {
            if (commitDate.CompareTo(commit.Committer.When.Date) > 0)
            {
                commitDate = commit.Committer.When.Date;
                // do some stuff
            }
        }
        lastCommit = commit;
    }
}
```

FilePath is subfilder and file name, example: Project\Folder\src\test.cs

If I tried to get  commits list:

```
var commits = repo.Branches.First(x => x.CanonicalName.Equals(_branch)).Commits.Reverse();     
```

It was full of commits.

**Comment by whoisj** [comment]
What is the value of `parameters.FilePath`?

**Comment by FeniXVRN** [comment]
example: Project\Folder\src\test.cs

**Comment by nulltoken** [comment]
@FeniXVRN Is `Project` the name of the working folder (eg. the folder containing a `.git` directory)? If that's the case, that won't work and you should only use `Folder\src\test.cs`.

For troubleshooting purpose can you please run `git log --follow Project\Folder\src\test.cs`?

**Comment by Therzok** [comment]
Is the string replacement actually yielding a relative path for the git file? Do not forget, the paths need to be unix like (`/` as a separator, not `\`).

**Comment by whoisj** [comment]
As @Therzok points out, and I was alluding to by asking about the value of the parameter - you have to use repo path nomenclature not Windows file system nomenclature.

**Comment by nulltoken** [comment]
Good point. I didn't think of the slash/backslash point. Logged #1075 to cover this.

**Comment by FeniXVRN** [comment]
Sorry for secrecy.
http://joxi.ru/KAgJK5QI05EJ2l - is not working
But http://joxi.ru/YmEpVgLfVGw7r6 is working now, and I don't know why.
I've just opened console before launching the app, and sent git log --follow.

**Comment by Therzok** [comment]
Why did you replace `\\` with `//`? You only need one slash `/` for unix paths.

**Comment by ethomson** [comment]
We cannot support `\` as a path separator, since you can actually have a repository path entry with `\` in it.  We _must_ use `/` as the repository separator.
