### ISSUE TITLE
Ensure repo.Commits.QueryBy(string) accepts paths with backslash

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#1075]
Add a unit test with paths built using `Path.PathSeparator` to ensure we correctly cope with slashes and backslashes

If the test fails on Windows, fix the current implementation. Leveraging the `FilePath` type may help.

Related to #1074 

/cc @ThomasBarnekow

**Comment by ornatwork** [comment]
I don't think you wanted Path.PathSeperator, rather test for DirectorySeparatorChar and AltDirectorySeparatorChar ?

**Comment by Therzok** [comment]
I think we don't want to break backwards compat, and treat both path separators as valid.

**Comment by ethomson** [comment]
We cannot support `\` as a path separator, since you can actually have a repository path entry with `\` in it.  We _must_ use `/` as the repository separator.
