### ISSUE TITLE
LibGit2Sharp.Network.BuildRemoteSafeHandle Should be Two Methods

### ISSUE THREAD

**Issue by whoisj** [libgit2/libgit2sharp#1084]
Currently `LibGit2Sharp.Network.BuildRemoteSafeHandle` has a rather confusing signature. It takes two parameters `remote` and `url`, then proceeds to ignore `remote` if `url` is not `null` or does a fallback to deferencing `remote.Name` if url is `null`.

```
        static RemoteSafeHandle BuildRemoteSafeHandle(RepositorySafeHandle repoHandle, Remote remote, string url)
        {
            Debug.Assert((remote == null) ^ (url == null));

            RemoteSafeHandle remoteHandle = null;

            if (url != null)
            {
                remoteHandle = Proxy.git_remote_create_anonymous(repoHandle, url);
            }
            else if (remote != null)
            {
                remoteHandle = Proxy.git_remote_lookup(repoHandle, remote.Name, true);
            }

            return remoteHandle;
        }
```

Rather than this confusing and irregular signature, I propose two methods:

```
static RemoteSafeHandle BuildRemoteSafeHandle(RepositorySafeHandle repoHandle, Remote remote);
```
```
static RemoteSafeHandle BuildRemoteSafeHandle(RepositorySafeHandle repoHandle, string url);
```

The methods would be more self describing if nothing else. Thoughts?

If nobody objects, I'll try and get a PR up in a day or so.

**Comment by jamill** [comment]
Seems like a reasonable proposal to me!

**Comment by nulltoken** [comment]
:+1:

**Comment by nulltoken** [comment]
What should we do with #1083? Close it?

**Comment by jamill** [comment]
> What should we do with #1083? Close it?

That is what I would do - close that one and proceed with this one.

**Comment by whoisj** [comment]
Sounds fine. Fixing the issue is cheap but very small value. Fixing the API could be more extensive but has higher value. Either take the other change then this one, or just wait for this. Net value is the same.

**Comment by jamill** [comment]
>Fixing the API could be more extensive 

This is not an public API change - but rather an internal private method?

**Comment by whoisj** [comment]
Absolutely not a public API change. Sorry if I'm using the term in a way your not familiar with (or is just plain incorrect) but I tend to call any method-object-surface-area an API for brevity.

**Comment by jamill** [comment]
Gotcha - I think we are on the same page!
