### ISSUE TITLE
Teach Network.ListReferences() and Repository.ListRemoteReferences to cope with symbolic references

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#1085]
Once #1065 is merged, let's work on this

**Comment by carlosmn** [comment]
If you're going to interpret the output into something which looks a lot more like references, it would be good to clean up those `refs/tags/foo^{}` entries which currently are converted to `DirectReference` as those could never be a reference locally due to their name. What those represent are the peeled targets of the references just before them.

**Comment by nulltoken** [comment]
@carlosmn :+1:

**Comment by nulltoken** [comment]
@psawey Are you willing to give a stab at this one? There's some light interop involved, but I'd be more than happy to help you with it.

**Comment by psawey** [comment]
@nulltoken Definitely, will start digging into it. Have an idea on where to get started, but will have some questions as I get further into it.

**Comment by psawey** [comment]
@nulltoken Am I on the right path in that both methods would only need to return references that are actually `DirectReferences`, filtering out any `SymbolicReferences` or any Dereferenced tags?

**Comment by nulltoken** [comment]
@psawey I indeed think that most of them would be `DirectReference`s.

However, some of them may be `SymbolicReference`s pointing at some `DirectReference`s (or other `SymbolicReference`s would they be chained). Thus, we would have to return a `IEnumerable<Reference>`.

**Comment by nulltoken** [comment]
@psawey Do you need any help making this happen?

**Comment by psawey** [comment]
@nulltoken The issue I'm hung up on is the best way to resolve a SymRef Target to it's `DirectReference`. After getting that, I can build the new `SymbolicReference`. Have been looking at `git_reference_symbolic_target`, but didn't see any good usages on how to pass it a `ReferenceSafeHandle` as building that requires a `RepositoryHandle`, making it difficult in cases when no Repository has been set locally.

**Comment by nulltoken** [comment]
@psawey Can you please open a PR with what you have now and point me to the missing piece of code (even it doesn't even compile)? It'll be easier for me to help you this way.

**Comment by carlosmn** [comment]
Fixed via #1132
