### ISSUE TITLE
GPG-sign commit

### ISSUE THREAD

**Issue by Aimeast** [libgit2/libgit2sharp#1101]
Looks like `libgit2sharp` not supported to GPG-sign commit.

I propose import the API about GPG-sign.

http://git.kernel.org/cgit/git/git.git/plain/Documentation/RelNotes/1.7.9.txt
```text
Git v1.7.9 Release Notes
"git commit" learned "-S" to GPG-sign the commit; this can be shown
   with the "--show-signature" option to "git log".
```

**Comment by Aimeast** [comment]
@nulltoken this issue maked as `FeatReq` but not `libgit2`, is that mean `libgit2` support to GPG-sign? If yes, could you please point me an example GPG API of `libgit2`. Thanks.

**Comment by carlosmn** [comment]
There's no support for this in libgit2 and there likely won't be any short-term. There likely will be a way to grab the specific header such that you can perform whatever gpg operations on it yourself.

**Comment by nulltoken** [comment]
@Aimeast good :eyes: ! Label added, thanks!

**Comment by nulltoken** [comment]
First bits are here: 

 - Extracting a commit header field: https://github.com/libgit2/libgit2/pull/3240

**Comment by shrikantbmali** [comment]
@carlosmn if you know and can point to a guide as to how I can use this?
I am using repo.Commit method and would like to sign it with gpg signature.
I am using Gpg4win for sing commit.
