### ISSUE TITLE
DetachedHead canonical name

### ISSUE THREAD

**Issue by Therzok** [libgit2/libgit2sharp#1104]
We currently have "(no branch)" as the canonical name for a Detached Head. Shouldn't this show a SHA (short-SHA) or something clearer?

**Comment by whoisj** [comment]
What does git.exe do, and there's your answer :smiling_imp: 

Yes, I believe we should show the SHA (or something).

**Comment by Therzok** [comment]
'detached from $shortsha', that's what git does.

**Comment by Therzok** [comment]
Superseded by #1105
