### ISSUE TITLE
Drop Mono workaround

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#1108]
**[GitErrorSafeHandle.cs](https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/Core/Handles/GitErrorSafeHandle.cs)** is currently implemented that way

```csharp
// Required on Mono < 3.0.8
// https://bugzilla.xamarin.com/show_bug.cgi?id=11417
// https://github.com/mono/mono/commit/9cdddca7ec283f3b9181f3f69c1acecc0d9cc289
if (handle == IntPtr.Zero)
{
    return null;
}
```

As we require Mono 3.6+, this is no longer necessary.

It would be worth taking a look at the other `SafeHandle` types and drop similar workarounds would they have been duplicated.

**Comment by carlosmn** [comment]
We got rid of this class with #1247, so the workaround is no longer there.
