### ISSUE TITLE
Repository cleanup pack files functionality

### ISSUE THREAD

**Issue by Therzok** [libgit2/libgit2sharp#1118]
Using a long-lived Repository, you end up having lots of pack files open at runtime, so it probably would make sense to expose a Cleanup function which closes them in libgit2 land?

Is there anything in libgit2 for this? (Except disposing the repo and creating a new one).

/cc @carlosmn @nulltoken

**Comment by Therzok** [comment]
By cleanup pack files, I don't mean `GC`-wise, from the filesystem, I meant just in-memory pack files which are open.

**Comment by carlosmn** [comment]
We clean up when we allocate a largish amount of address space for packfiles, but that won't trigger if you have a lot of tiny packfiles. See libgit2/ligit2#2758
