### ISSUE TITLE
Is the name `GlobalSettings` accurate and descriptive, or should we rename?

### ISSUE THREAD

**Issue by whoisj** [libgit2/libgit2sharp#1119]
In the spirit of "get all your breaking changes in now, before v1.0" I'd like to bring up a discussion related to `GlobalSettings`. As the scope the library increases, more and more features are being packed into the `GlobalSettings` object. While these feature belong in a global singleton, I'm questioning if that object should be named "xxxSetting" or something more meaningful?

Perhaps something as simple as "Global"? Thoughts?

Part of #1103

**Comment by nulltoken** [comment]
While we're in this area, maybe should we also improve the documentation of this type. Indeed, this type holds registrations that exceeds the lifespan of a `Repository.`I *feel* that pretty strange side-effects may happen would we blindly deregister while some repos are still alive and leveraging those.

**Comment by whoisj** [comment]
> I feel that pretty strange side-effects may happen would we blindly deregister while some repos are still alive and leveraging those.

100% agree. While Git has global and system settings, and obviously supports many repos, it is a user application which is not long lived. Libgit2/Sharp are libraries which can be loaded by very long lived services - this means any time the global structure is touched it can affect dozens to hundreds of repos and potentially hundreds or thousands of users. :scream:

**Comment by nulltoken** [comment]
>Perhaps some kind of locking of global values while any Repository objects are not yet disposed could provide some value?

Indeed! @sharwell and @jbialobr did something similar with #361

**Comment by ethomson** [comment]
My $0.02: I'm perfectly happy with `GlobalSettings`.

**Comment by Therzok** [comment]
> My $0.02: I'm perfectly happy with GlobalSettings.

:+1:

**Comment by nulltoken** [comment]
Dropped stabilization label from this issue as this doesn't seem to gather a clear consensus.

**Comment by ckuhn203** [comment]
I'll third the sentiment from @ethompson @Therzok. `GlobalSettings` is fine. More than fine, it's pretty descriptive IMO.
