### ISSUE TITLE
Repository.RemoveUntrackedFiles() throws exception : fail to rename git lockfile : access denied

### ISSUE THREAD

**Issue by john-grandy-opentable** [libgit2/libgit2sharp#1128]
Windows Server 2008 
McAfee Agent v4.8.0.1938 
no indexing service 
ASP.NET C# app 
libgit2sharp v0.21.0.176 NuGet package 

My ASP.NET app uses libgit2sharp `Repository.Clone()` method to create a local clone of a GitHub repo. ( But note that I experience the same errors when I manually clone the repo via CLI `git clone` on the deploy server. )

On my local dev workstation, various libgit2sharp operations succeed ( e.g. `Repository.Checkout()` , `Repository.Fetch()` ) with no issues.

However, once my app is deployed to a remote server and hosted inside IIS , I'm encountering what appear to be either permissions or locking issues.

    Repository.RemoveUntrackedFiles()

Exception thrown :

    Failed to rename lockfile to 'c:/github/{org-name}/{target-repo-name}/.git/index': Access is denied.

If I re-attempt the operation it again fails but this time with a different exception :

    The index is locked. This might be due to a concurrent or crashed process.

Subsequent attempts ( no matter how many ) fail with this same exception.

Issue is not resolved with iisreset or reboot.

If I re-create the local repo by going to cli and deleting local repo folder and then running git clone, I'm now able to successfully execute various git operations until I again attempt `Repository.RemoveUntrackedFiles()` at which point the above error-sequence re-occurs.

EDIT : I'm also encountering similar issues with

    Repository.Checkout()

Exception thrown : 

    Failed to rename lockfile to 'c:/github/{org-name}/{target-repo-name}/.git/index': Access is denied.

I then go to the server and from the command line attempt `git checkout master` :

    c:\github\{org-name}\{target-repo-name}>git checkout master
    fatal: Unable to create 'c:/github/{org-name}/{target-repo-name}/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

**Comment by john-grandy-opentable** [comment]
@nulltoken any chance you could take a look soon ?  I am not finding any explanation for this error outside of libgit2sharp code-base. The error occurs on multiple machines (Windows Server 2008 RC2 )with freshly cloned repos.  Any assistance I can provide please let me know.

**Comment by nulltoken** [comment]
>Any assistance I can provide please let me know.

Would you please be able to provide us with a end-to-end repro case? (a minimalist c# project that we could deploy in order to troubleshoot the issue?

When working on your local computer how do host the web site? Can you repro this behavior locally on IIS?

**Comment by john-grandy-opentable** [comment]
I'll work on a minimalist C# project that will repro issue on our servers.

On my local dev machine, the issue does not repro. 

My local dev machine (Windows 7) is configured to model the deploy servers (Windows Server 2008 RC2) as much as possible.

Two local dir-structures are established : 

    c:\github\{org-name}\{app-repo-name}
    c:\github\{org-name}\{target-repo-name}

IIS is configured with site {app-name} with Physical Path = `c:\github\{org-name}\{app-repo-name}` 

The site is configured with a dedicated app pool ( .NET Framework Version 4.0 ).

**Comment by nulltoken** [comment]
Thanks for your feedback. Under which identity is run the app on your local dev environment vs on your servers?

**Comment by ethomson** [comment]
Just to set expectations, it's very possible that what you're describing is the correct behavior.

To begin doing modifications, git clients lock the index by writing `.git\index.lock`.  When they are ready to commit the changes, they rename `.git\index.lock` to `.git\index`.  This is what failed in your first step, which sounds like a permissions problem.

To prevent data loss, `.git\index.lock` is not removed.  Subsequent operations by git clients will see that the index is locked and not perform any changes.  (And indicate to you that either another git process is running, or one crashed.)

If you have something configured such that your `.git` directory is writable by the IIS user, but `.git\index` is not, then what you've described is exactly what I would expect.

**Comment by john-grandy-opentable** [comment]
@nulltoken : Local dev workstation is Windows 7 and deploy server is Windows Server 2008 R2 IIS 

In both cases IIS v7.5.7600.16385 with site's application pool identity = `ApplicationPoolIdentity`

So in both cases this corresponds to account `IIS AppPool\<app pool name>`

@ethomson : what you say makes total sense to me as it is consistent with the error pattern I'm observing .... but how could an IIS user have write permissions on `.git` dir but not `.git\index` file ?

Also note that I have some cleanup code that attempts to delete repo local dir and then `git clone` - however Access Denied exception is thrown attempting to delete .pack files.

**Comment by nulltoken** [comment]
> however Access Denied exception is thrown attempting to delete .git\object\pack\*.pack and .git\object\pack\*.idx files.

This may because of the readonly attribute those files are marked with. See the **[DirectoryHelper](https://aasolutions.visualstudio.com/DefaultCollection/Wimtt/_build#_a=summary&buildId=999)** type we're using to work around this when running our tests.

**Comment by john-grandy-opentable** [comment]
@nulltoken my Microsoft account jgrandy@opentable.com is not authorized to view the page you linked to for `DirectoryHelper` - could you add me ?

Did you see my SO question about the `Repository` object and `using` and `dispose` ?

**Comment by Therzok** [comment]
@john-grandy-opentable It was a miscopy of a link, most likely. This is [DirectoryHelper](https://github.com/libgit2/libgit2sharp/blob/63f8d6d90f06f4578604b57502f2c6b8aabf4479/LibGit2Sharp.Tests/TestHelpers/DirectoryHelper.cs#L39-L50).

**Comment by john-grandy-opentable** [comment]
@nulltoken @Therzok ah interested i wrote similar code to normalize directory attributes of contained folders/files before attempting delete - but i didn't think to attempt delete multiple times - is this necessary ?

**Comment by nulltoken** [comment]
>It was a miscopy of a link, most likely. 

@Therzok Indeed. Duh. Thanks. Fixed. :confounded:

**Comment by nulltoken** [comment]
> i wrote similar code to normalize directory attributes of contained folders/files before attempting delete - but i didn't think to attempt delete multiple times - is this necessary ?

@ThomasBarnekow wrote this part of the code in #971. He may give a better explanation than me. 

However, IIRC, it's been done to cope with some external tools aggressively keeping a hold on those files (an antivirus for instance) while we were trying to delete them.

**Comment by john-grandy-opentable** [comment]
@nulltoken I refactored my code to wrap every usage of Repository methods in a `using(){}` block but it did not solve my issue.

Here's the error-sequence : on the remote server I manually clean-up. From CLI I delete local repo dir and `git clone` the local repo. Then I logoff the server.

My app code creates a new branch and maps it to the remote origin. Next I successfully execute 'Repository.Network.Fetch()` , but when I attempt `Repository.RemoveUntrackedFiles()` I receive exception : 

    [Failed to rename lockfile to 'c:/github/{org-name}/{repo-name}/.git/index': Access is denied.

RDP to remote server Unlocker indicates no locks on local repo dir but both `\.git\index` and `\.git\index.lock` are present.

Please note that if repeat the experiment with commented-out `Repository.RemoveUntrackedFiles()` , the next git operation `Repository.Checkout()` will trigger the same exception.  So the Access Denied error appears to be triggered by any `Repository` operation that accesses `\.git\index`

**Comment by ThomasBarnekow** [comment]
> @nulltoken @Therzok ah interested i wrote similar code to normalize directory attributes of contained folders/files before attempting delete - but i didn't think to attempt delete multiple times - is this necessary?

@john-grandy-opentable This was done because, on developer machines, there might be background software (e.g., virus protection or Tortoise Git) holding on to the repositories that you are creating and deleting during your tests. This is why the deletion is attempted repeatedly in a defined fashion.

**Comment by carlosmn** [comment]
@john-grandy-opentable is the initial `git clone` done by the same user that is later executing the code inside the IIS container? I don't see that you've shown that these are the same users, or that the IIS user has permission to overwrite files which you created during the `git clone`.

**Comment by john-grandy-opentable** [comment]
@carlosmn currently the initial git clone to create the local repo is performed  manually by myself - I RDP into the server and from the CLI run `git clone`

My ASP.NET application runs under the Application Pool Identity - which I believe uses the built-in Windows account `Network Service` -- so I assume `libgit2sharp` runs under `Network Service`

Does git place special permissions on files created via `git clone` ?

**Comment by carlosmn** [comment]
There are no special permissions (though we do mark files as read-only, at least on unix), but what you're describing sounds like there are two different users performing operations, which would explain why we can't replace `.git/index`.

As for the left-over `index.lock` file, I believe I have found the problem in our code. We don't keep track of whether the rename succeeded, so the filebuf code considers it to have succeeded and we don't remove the lock.

**Comment by carlosmn** [comment]
The left-over lockfile issue was resolved in libgit2 and the new release has the fix. As for the other issue, it still looks like an issue with different users.
