### ISSUE TITLE
Repository.Clone of a public repository without credentials does not work

### ISSUE THREAD

**Issue by angellaa** [libgit2/libgit2sharp#1141]
Hello,

I know that public projects on GitHub can be cloned without the needs to provide credentials. I'd like to do the same using Repository.Clone but I get the exception "Request failed with status code: 401".

Is it possible to clone a public repository without authentication using Repository.Clone?

Thanks,
Andrea

**Comment by carlosmn** [comment]
If the repository exists and is public, then there is no authentication required and GitHub won't ask for credentials, thus libgit2sharp won't ask them of your program.

If the repository does not exist or is private, GitHub will ask for credentials the same way. This technique often used as a way to avoid disclosing the existence of private repositories to third parties, which would be possible if the responses were different.

So if you're being asked for credentials when you don't expect to, you may have mistyped the repository's path, or the repository is in fact private.

**Comment by angellaa** [comment]
Thank you for your answer. 

You are right, it's me being stupid. I mistyped the repository. It's working great.

Thank you!

**Comment by nulltoken** [comment]
@angellaa Glad your issue was fixed!
