### ISSUE TITLE
Init not working for certain directories

### ISSUE THREAD

**Issue by mbos** [libgit2/libgit2sharp#1158]
When I call:
var repo = Repository.Init(@"D:\pass");

I get an exception that "D:" is not a valid directory.

When using a longer path:
var repo = Repository.Init(@"D:\pass\users"); 
No problem what so ever.

**Comment by nulltoken** [comment]
What version of LibGit2Sharp are you using, please?

**Comment by mbos** [comment]
Oh sorry forgot to mention.
I'm using the nuget version: 0.21.0.176

**Comment by nulltoken** [comment]
@mbos Are you able to reproduce this behavior with the most recent pre-release package?

**Comment by mbos** [comment]
Solved with 0.22

**Comment by nulltoken** [comment]
:cool: :bangbang: 

Thanks for having checked

**Comment by mbos** [comment]
No problem and thanks for the fast response.
