### ISSUE TITLE
Commit Not working: LibGit2Sharp.LibGit2SharpException: Configuration value 'user.name' is missing or invalid

### ISSUE THREAD

**Issue by kunjan13** [libgit2/libgit2sharp#1163]
I am able to clone the repository, also able to checkout my branch.
however when it tries to commit the changes it throws this exception:
LibGit2Sharp.LibGit2SharpException: Configuration value 'user.name' is missing or invalid

I thought missing signature was an issue, but after providing it, still the same issue.

PS: the same codes work perfectly fine in my local machine, and only throws this exception when on server.

**Comment by gabriel175** [comment]
It is because your local computer has [user] section and name under that section in the .gitconfig (should be located under your user folder), and your server does not have this file or does not have it under the [user] section.

You can solve this in one of this two ways:
1. create on your server the ".gitconfig" file with the section [user] and key "name" and "email".
2. you can use the overloaded method of Commit that recives both author and commiter, so you can send the signature twice (one as commiter and another one as author)

**Comment by ckuhn203** [comment]
I'm not sold on that explanation @gabriel175. According to the [BuildSignature doc][1] it's supposed to return "unknown" if the user name is unspecified.

        /// <summary>
        /// Builds a <see cref="Signature"/> based on current configuration.
        /// <para>
        ///    Name is populated from the user.name setting, and is "unknown" if unspecified.
        ///    Email is populated from the user.email setting, and is built from
        ///    <see cref="Environment.UserName"/> and <see cref="Environment.UserDomainName"/> if unspecified.
        /// </para>
        /// <para>
        ///    The same escalation logic than in git.git will be used when looking for the key in the config files:
        ///       - local: the Git file in the current repository
        ///       - global: the Git file specific to the current interactive user (usually in `$HOME/.gitconfig`)
        ///       - xdg: another Git file specific to the current interactive user (usually in `$HOME/.config/git/config`)
        ///       - system: the system-wide Git file
        /// </para>
        /// </summary>

Looks like a legitimate bug from where I sit. I haven't quite figured out why it's not returning "unknown" if it can't return a value yet though.

[1]: https://github.com/libgit2/libgit2sharp/blob/5dc59683444ded35740072f77bf7893057f53934/LibGit2Sharp/Configuration.cs#L745-L762

**Comment by ckuhn203** [comment]
Okay, so maybe not a bug, but definitely some confusing behavior here. If you don't pass a `Signature` when calling commit, it uses the internal overload of `BuildSignature` which is set to throw if the username isn't found.

        public static Commit Commit(this IRepository repository, string message, CommitOptions options)
        {
            Signature author = repository.Config.BuildSignature(DateTimeOffset.Now, true);

            return repository.Commit(message, author, options);
        }

https://github.com/libgit2/libgit2sharp/blob/5dc59683444ded35740072f77bf7893057f53934/LibGit2Sharp/RepositoryExtensions.cs#L237-L242

It seems a bit awkward to me to have to explicitly pass a signature along with every call to commit. Any of the maintainers have insight into why this is the default behavior?

**Comment by carlosmn** [comment]
The signature is part of the data that goes into making a commit and libgit2(sharp) doesn't know what you want the signatures to be any more than it knows the contents of your commit or the message. If the repository configuration (or levels above) do contain the default name and email, then libgit2sharp lets you assume that it's the one you want to use.

**Comment by ckuhn203** [comment]
@carlosmn I understand that. I'm just trying to call out and understand what looks like inconsistent behavior to me. As a consumer of the API, I find it odd that `BuildSignature` does not throw an exception by default, but `Commit` does.

**Comment by carlosmn** [comment]
`Commit()` throws if there is not author/committer identity configured in the environment because that information *must* be in the commit. And it cannot create a commit if it doesn't exist.

It would be *very bad* if the library were to ignore the fact that there is no usable identity for the commit authorship and it would just input whatever identity it wanted.

**Comment by ckuhn203** [comment]
Ahh. See, that's exactly the insight I was looking for. Thanks @carlosmn. :+1:

**Comment by carlosmn** [comment]
I will certainly concede that the exception could be much better. Mentioning one of the fields only tells you what's wrong mechanically. AFAICT the behaviour of `BuildSignature()` comes from an old behaviour wrt reflogs, which isn't relevant anymore.

**Comment by kunjan13** [comment]
Thanks @gabriel175  I tried solution 2, and it solved my issue on that day itself. However i forgot to update the issue.

Thanks everyone for the explanation!

**Comment by ckuhn203** [comment]
@carlosmn I'm considering opening a separate issue related to the inconsistent behavior and poor exception message, but I'd like to offer some solutions when I do. So, what exactly does "very bad things" mean? What could happen if the identity was registered as `unknown` in a commit?

**Comment by ckuhn203** [comment]
For history's sake. #1171 changed the behavior of `BuildSignature` in v0.22
