### ISSUE TITLE
Pull always resulting in merge conflicts (git pull works)

### ISSUE THREAD

**Issue by GSIO01** [libgit2/libgit2sharp#1184]
I'm trying to use repository.Network.Pull to get changes from our origin (residing on a network share in our local network). Trying to do so will result in an exception thrown because of merge conflicts.
I tried all possible combinations for the PullOptions.

Using git pull by hand works flawlessly.

**Comment by ethomson** [comment]
Merge conflicts shouldn't throw an exception.  Are you seeing *checkout* conflicts?  (eg, "working tree files would be overwritten by merge"...)?

What version of LibGit2Sharp?

Are you using exotic filters in your `gitattributes`?

Is your working directory *also* on a network share?

**Comment by GSIO01** [comment]
You are right the exception seems to be thrown during checkout. The Message is "20 conflicts prevent checkout" (of course with changing conflict count).

We are currently using version 0.21 of LibGit2Sharp (via NuGet).

No filters in the gitattributes.

The working directory is on a local drive.

**Comment by ethomson** [comment]
What does LibGit2Sharp's status show in this case?  Is it showing that your working directory is clean?

One Git tool showing that your working directory is "clean" and another showing that it is not is *almost always* a case of EOL filtering problems in your repository.

Are you controlling your end of line settings with a `.gitattributes` file?  What is that `.gitattributes` configuration?  And has it always been there?

If not, I would wager a tidy sum that somebody on your team has (at some point) checked in file(s) with a `core.autocrlf` setting that doesn't match the one that you have now.

**Comment by GSIO01** [comment]
It might very well be an problem with line endings as you suggested. Parts of our codebase are pretty old.
I updated our .gitattributes and also ensured all developers use the correct core.autcrlf setting.
I'll check the LibGit2Sharp status if we run into the problem again.

**Comment by carlosmn** [comment]
@GSIO01 have you had a chance to check with a newer libgit2sharp? We should be closer to git with the newer releases.

**Comment by GSIO01** [comment]
I'll just tried it and it seems to work now. I'll keep an eye on it for the next few times to be sure.
