### ISSUE TITLE
Potentially deprecate config file path overrides through RepositoryOptions parameters

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#1188]
Following the merge of #1123, let's discuss about whether it makes sense or not to keep the config filepaths overrides per repository instances.

Would any of your tools actually still need those *per repository* instance specialized config file paths now that an appdomain level setting exist?

/cc @shiftkey @rcorre @Therzok @ethomson @carlosmn @spraints @KindDragon

**Comment by shiftkey** [comment]
> Would any of your tools actually still need those per repository instance specialized config file paths now that an appdomain level setting exist?

![](https://media.giphy.com/media/8mZK9do4ZvxQc/giphy.gif)

**Comment by spraints** [comment]
> Would any of your tools actually still need those per repository instance specialized config file paths now that an appdomain level setting exist?

I don't think so, but can you give me an example of what APIs or types of calls would go away if this went away?

**Comment by rcorre** [comment]
Things like:

    var options = new RepositoryOptions { GlobalConfigurationLocation = configPath };

    var path = SandboxStandardTestRepoGitDir();
    using (var repo = new Repository(path, options)) { ... }

as seen in [some LibGit2# tests](https://github.com/libgit2/libgit2sharp/blob/d79eec540a4637bf04e5ca379f4488145fe40923/LibGit2Sharp.Tests/ConfigurationFixture.cs#L147) would go away (not `RepositoryOptions` as a whole, just the config redirection part).

As far as I'm aware, we don't rely on this at all.

**Comment by spraints** [comment]
:sunglasses: IIRC git-tfs uses vanilla config everywhere.

**Comment by carlosmn** [comment]
We do need this for the tests in order to create isolated repos, but I'm working on making the test suite set this up globally at the start of a fixture instead of only isolating some repos.
