### ISSUE TITLE
No feedback of failed push

### ISSUE THREAD

**Issue by SambalOelek** [libgit2/libgit2sharp#1192]
I'm pushing refs/notes/commits to a Stash server with yet-another-commit-checker installed.
Due to a (possible) bug in the yacc, the yacc pre-commit fails the push. This is plainly visible from the command line (`git push origin refs/notes/commits` -> "error: failed to push some refs to...").
But from the libgit2sharp `Repository.Network.Push(...)` I'm not getting one bit of information that the push has failed.

**Comment by ethomson** [comment]
I don't know anything about yacc.  What do you get when you try to push with git on the command-line?  Can you paste its output?

Better yet, can you post a fiddler or wireshark trace that shows what you're getting on the wire?

**Comment by carlosmn** [comment]
How are you calling `Push()`? There is a callback where the success and error for individual refs updates is reported. Invididual ref update failures do not cause the whole push to be considered failed, as other updates might have succeeded.

Specifically, `PushOptions` has a field `OnPushStatusError` which you must set if you want to be notified of failed ref updates (and their reasons).

**Comment by SambalOelek** [comment]
The output:

    D:\>git push origin refs/notes/commits
    Password for 'http://nnnn@stash.xyzzy.com':
    Counting objects: 11, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (2/2), done.
    Writing objects: 100% (3/3), 337 bytes | 0 bytes/s, done.
    Total 3 (delta 1), reused 0 (delta 0)
    remote:
    remote:   (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)    (c).-.(c)
    remote:    / ._. \      / ._. \      / ._. \      / ._. \      / ._. \
    remote:  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__  __\( Y )/__
    remote: (_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)(_.-/'-'\-._)
    remote:    || E ||      || R ||      || R ||      || O ||      || R ||
    remote:  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '._  _.' `-' '.
    remote: (.-./`-'\.-.)(.-./`-`\.-.)(.-./`-`\.-.)(.-./`-'\.-.)(.-./`-`\.-.)
    remote:  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'  `-'     `-'
    remote:
    remote:
    remote: Push rejected.
    remote:
    remote: refs/notes/commits: 81cf36d3c6e3dc3a47be095cd7aa5f6a1b2d46a5: expected committer name 'A' but found 'B'
    remote: refs/notes/commits: 86638b5a54ae3538a514110c0c80cb79bf8dbc57: expected committer name 'A' but found 'B'
    remote:
    To http://nnnn@stash.xyzzy.com/a/test/test-repository.git
     ! [remote rejected] refs/notes/commits -> refs/notes/commits (pre-receive hook declined)
    error: failed to push some refs to 'http://nnnn@stash.xyzzy.com/a/test/test-repository.git'

The code used

    try
    {
        repo.Network.Push(rm, refSpec, new PushOptions()
        {
            CredentialsProvider = ((a, b, c) => RepositoryWork.CredentialsHandlerLibGit(a, b, c, settings)),
            OnPushTransferProgress = (a, b, c) => {
                var msg = string.Format("Transfer status: {0} {1} {2}", a, b, c);
                sw.WriteLine(msg);
                worker.ReportProgress(-1, msg);
                return !worker.CancellationPending;
            },
            OnPackBuilderProgress = (a, b, c) => {
                var msg = string.Format("Builder status: {0} {1} {2}", a, b, c);
                sw.WriteLine(msg);
                worker.ReportProgress(-1, msg);
                return !worker.CancellationPending;
            },
            OnPushStatusError = ((a) => sw.WriteLine("Push error: {0}", a.Message))
        });
        break;
    }
    catch (Exception ex)
    {
        sw.WriteLine("Exception: {0}", ex.Message + (ex.InnerException != null ? " / " + ex.InnerException.Message : ""));
    }

returns exactly this (and is yet not successful)

    Parsing all modified notes...
    Starting a git push using origin = LibGit2Sharp.Remote...:
    Builder status: Counting 1 0
    Builder status: Deltafying 0 3
    Transfer status: 0 3 12
    Transfer status: 3 3 434

Regards

**Comment by carlosmn** [comment]
The error callback was wired up by #987. Updating to the new release will trigger the error handler.
