### ISSUE TITLE
repo.Diff.Compare Returns Different Results based on Version of Git for Windows Installed

### ISSUE THREAD

**Issue by pdemro** [libgit2/libgit2sharp#1195]
Not sure if this is an issue with Git for Windows or LibGit2Sharp..

When I install the latest Git for Windows (Git-2.5.3-64-bit.exe), these two commands return conflicting results:

From Git Bash:
git diff

From LibGit2Sharp
repo.Diff.Compare<TreeChanges>(repo.Head.tip.Tree, DiffTargets.WorkingDirectory);

When I have msysgit 1.9.5 installed the above commands return the same results.  Happy to clarify here if it would be helpful.

**Comment by Therzok** [comment]
We would love a sample of when the diffing is different. Any kind of code? The issue is too broad.

That means LibGit2sharp is consistent (we don't use Git for Windows anywhere), and something changed in Git For Windows between 1.9.5 and 2.5.3.

**Comment by pdemro** [comment]
Glad to hear from you so quickly Therzok.  I have a workaround here by using the old version of Git but I thought I'd raise my hand as something doesn't seem quite right..

To reproduce (on my machine anyway)

1. Install Git for Windows 2.5.3 (latest)

2. Clone https://github.com/pdemro/Test_09-28-2015 somewhere

3. Run in a console application 

            using (var repo = new Repository(@"<<my repo path>>"))
            {
                var tc = repo.Diff.Compare<TreeChanges>(repo.Head.Tip.Tree, DiffTargets.WorkingDirectory);
                Console.WriteLine(tc.Count<TreeEntryChanges>());
                Console.ReadLine();
            }

4. In my environment tc shows README.md as being modified for some reason.  

5. Uninstall Git for windows. Install msysgit 1.9.5 https://github.com/msysgit/msysgit/releases/

6. Same console application shows 0 changes

**Comment by nulltoken** [comment]
@pdemro Could you please paste here the output of each diff?

**Comment by pdemro** [comment]
![git_1-9-5](https://cloud.githubusercontent.com/assets/5431128/10145115/3d28dfd8-65ef-11e5-85a7-fbedb89b9dfa.png)
![git_2-5-3](https://cloud.githubusercontent.com/assets/5431128/10145116/3d2db080-65ef-11e5-889f-e14dffe9d45a.png)

**Comment by ethomson** [comment]
Tell me about your line ending configuration...

**Comment by pdemro** [comment]
In both installs I always select "Checkout Windows-style, commit Unix-style line endings"

git config --list shows core.autocrlf=true in both environments. 

Is there some other config I can check for line endings?

**Comment by ethomson** [comment]
Are there *other* `core.autocrlf` entries in your configuration?

Either way - `core.autocrlf` is scoped to your installation (and perhaps even the particular version of Git for Windows!)  You probably want something scoped to the *repository* - like a `.gitattributes` entry of:

    * text=auto

**Comment by pdemro** [comment]
Thank you Edward!  I've updated the repo from the example above with a .gitattributes file with the contents you specified and it seems to resolve the diff discrepancy.

I am new to the .gitattributes file.  Can you offer a few words for why this specific configuration seems to have fixed it?  What might have caused the same repository to work in an older version of Git versus the latest version?

**Comment by ethomson** [comment]
> I am new to the .gitattributes file. Can you offer a few words for why this specific configuration seems to have fixed it? What might have caused the same repository to work in an older version of Git versus the latest version?

My suspicion remains that there is *another* `core.autocrlf` configuration setting introduced in the new side.  Can you post the full results of `git config --list` for both?

**Comment by pdemro** [comment]
Administrator@WIN-6H8BDDODU4N ~/source/repos/Test_09-28-2015 (master)
$ git version
git version 1.9.5.msysgit.1

Administrator@WIN-6H8BDDODU4N ~/source/repos/Test_09-28-2015 (master)
$ git config --list
core.symlinks=false
core.autocrlf=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
pack.packsizelimit=2g
help.format=html
http.sslcainfo=/bin/curl-ca-bundle.crt
sendemail.smtpserver=/bin/msmtp.exe
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=store
user.email=phillip.demro@hotmail.com
user.name=Phillip Demro
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
remote.origin.url=https://github.com/pdemro/Test_09-28-2015.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master


---------------------------------------------------------------------------------

Administrator@WIN-6H8BDDODU4N MINGW64 ~/source/repos/Test_09-28-2015 (master)
$ git version
git version 2.5.3.windows.1

Administrator@WIN-6H8BDDODU4N MINGW64 ~/source/repos/Test_09-28-2015 (master)
$ git config --list
core.symlinks=false
core.autocrlf=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
pack.packsizelimit=2g
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=store
user.email=phillip.demro@hotmail.com
user.name=Phillip Demro
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
remote.origin.url=https://github.com/pdemro/Test_09-28-2015.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master

**Comment by carlosmn** [comment]
From the position of `core.autocrlf` in the output, it looks like this is set in the system config, which, as @ethomson mentioned, is per-installation. While libgit2 does try to look up the Git for Windows configuration, it's not necessarily entirely correct for us to do so without your tool asking for it.

The 2.x series of Git for Windows changed some stuff around, so it's likely that your version of lbigit2 is not detecting the installation for the 2.5.3 installation. If you set `core.autocrlf` in the repository, it should show the same results in both, as you're not making it dependent on libgit2 discovering that you happen to have Git for Windows installed. But usin `.gitattributes` is generally a better idea, as you're storing the configuration in the repository in a way that you can share it across users and machines, instead of relying on remembering to set the configuration on each repo or system.

**Comment by twsouthwick** [comment]
I noticed this as well with Git for Windows 2.7.0. Once I ran `git config --global core.autocrlf true` libgit2sharp stopped noticing the line ending diffs. However, both before and after had the `core.autocrlf=true` in the list provided by `git config --list`. Is the detection of these config files something we can update in libgit2? I can't find where the autocrlf was coming from before, but it would be awesome if we can probe the correct config files.

**Comment by ethomson** [comment]
> However, both before and after had the core.autocrlf=true in the list provided by git config --list. Is the detection of these config files something we can update in libgit2? 

@twsouthwick What version of LibGit2Sharp are you using?  The understanding of Git for Windows 2.x's fun new configuration location is relatively recent.

**Comment by twsouthwick** [comment]
I'm using the nuget package v0.21.0.176 for libgit2sharp. When was understanding of Git for Windows 2.x's new config added?

**Comment by ethomson** [comment]
0.21 is unfortunately quite ancient and I'm afraid that it *does not* include [this](https://github.com/libgit2/libgit2/pull/3475).  We're preparing an updated release which should be available shortly.  In the meantime, the nightly prerelease nuget packages are very stable.

**Comment by ethomson** [comment]
However as @carlosmn notes, `core.autocrlf` is terrible and deprecated and should very much be avoided in favor of a properly configured `.gitattributes` everywhere.

**Comment by twsouthwick** [comment]
Sounds good - I'll update to a prerelease. Yeah - I try to use .gitattributes where possible, but sometimes we don't have control over the repository :( Thanks!

**Comment by carlosmn** [comment]
We're now shipping the new version, so we detect the new config lication.
