### ISSUE TITLE
 Path is not a directory 'D:': The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by Aghlara** [libgit2/libgit2sharp#1196]
Hi,
I started receiving exceptions when I do `Repository.Init`

![image](https://cloud.githubusercontent.com/assets/5187409/10204113/55aad498-67fd-11e5-8702-de90646a8ef1.png)

```
Type: LibGit2Sharp.NotFoundException
Message: Path is not a directory 'D:': The filename, directory name, or volume label syntax is incorrect.

Source: LibGit2Sharp
Stack:    at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_repository_init_ext(FilePath workdirPath, FilePath gitdirPath, Boolean isBare)
   at LibGit2Sharp.Repository.Init(String path, Boolean isBare)
   at Designer.Vault.Histories.LocalGit.GetRep(RuleProject ruleProject)
```

Any idea?

**Comment by ethomson** [comment]
I suspect that this is related to https://github.com/libgit2/libgit2/pull/3425 - the fix for which hasn't yet made it up here to LibGit2Sharp.

Does this work if you *don't* create a repository at the root of your drive?

**Comment by Aghlara** [comment]
If you look at the picture, I don't even trying to create at root! the exception shows wrong value.

**Comment by ethomson** [comment]
I mean a repo immediately beneath the root.  You're trying to create a repository at `D:\New folder (2)` - do you have success if you create `D:\Subdir\Repo`?

**Comment by Aghlara** [comment]
Correct, if I change it to `D:\New folder (2)\test` that works.

**Comment by Aghlara** [comment]
So what is the solution/workaround here?

**Comment by ethomson** [comment]
Thanks for the confirmation.  There is no workaround at the moment, except to not create directories at the root.  I'll see if I can figure out how to publish a native binaries package to nuget - we should be able to get you a prerelease build to verify this is now fixed, if I can.

**Comment by Aghlara** [comment]
What if I recompile against the latest version of native dll?

**Comment by ethomson** [comment]
Yes, please; let me know if that solves your problem.

**Comment by Aghlara** [comment]
I'll keep you posted.

**Comment by nulltoken** [comment]
@Aghlara Thanks for the report! Latest libgit2 binaries are now available as part of the published NuGet pre-release package `LibGit2Sharp.0.22.0-pre20151003111314`.

Could you please confirm that this solves the issue? Wouldn't that be case, we'd reopen this issue.

**Comment by Aghlara** [comment]
Sill the same issue with the latest libgit2.
