### ISSUE TITLE
String interpolation of constants... for cleaner code of course

### ISSUE THREAD

**Issue by whoisj** [libgit2/libgit2sharp#1201]
Has anyone spent any time thinking about using the new C# 6.0 compilers support for string interpolation and/or `nameof` operator in the LibGit2Sharp code base yet?

So long as it is only things that can be resolved at compile time, the values are converted to string literals and therefore work fine with the .NET Framework v4.0.

If interested, it is something I could start on in the areas I care most about, then over time we could slowly replace all the invariant string literals with compile time derived values. Really helps a lot if/when parameter and variable names change.

**Comment by carlosmn** [comment]
This would make the developer/packager to have .NET 4.6 installed locally, no? I don't think that's something we want to force people to have. There's also the matter of the mono version we would want to support. Do you know which one supports C# 6.0 features? We'd have to make sure it's not unreasonable for users to have installed.

**Comment by whoisj** [comment]
> We'd have to make sure it's not unreasonable for users to have installed.

Fair enough. I have just been enjoying the refactor support it offers recently and was hoping to spread the joy. :smile:

**Comment by bording** [comment]
> There's also the matter of the mono version we would want to support. Do you know which one supports C# 6.0 features?

Looks like 4.0.0 is the first version that mentions C# 6.0 in the release notes at least.
