### ISSUE TITLE
Create missing Directory entry in GitErrorCode

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#1203]
An error in #1202 build led us to discover we're missing a `GitErrorCode` entry mapping from `GIT_EDIRECTORY`. Let's fix this.

**References:**

- https://github.com/libgit2/libgit2/blob/master/include/git2/errors.h
- https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/Core/GitErrorCode.cs

**Comment by ckuhn203** [comment]
Did PR #1208 close this? I went to grab it, but just now saw the PR.

**Comment by nulltoken** [comment]
>Did PR #1208 close this?

@ckuhn203 Indeed. Thanks for the heads up!

**Comment by ckuhn203** [comment]
You're welcome @nulltoken! I'll see what else I can find to do.
