### ISSUE TITLE
CommitFilter does not match git.exe behavior

### ISSUE THREAD

**Issue by npizzolato** [libgit2/libgit2sharp#1212]
Libgit2sharp example code in documentation does not match git.exe behavior:
https://github.com/libgit2/libgit2sharp/wiki/git-log

Git log start..end
includes end

LibGit2Sharp equivalent using:
filter =new CommitFilter { Since=start, Until=end } 
repo.Commits.QueryBy(filter)

does not include end.

**For a HEAD ref, there is no way to get end+1 commit, so it's impossible to do the equivalent git.exe log query with libgit2sharp.**

**Comment by shiftkey** [comment]
I'm not sure why this was closed - is there something that needs to be looked at here?

**Comment by npizzolato** [comment]
Sorry, I realized I was using an old version before. I wanted to retry with the latest version (0.21.0.176) with a simpler repository to make sure it reproed before someone looked at it. 

Looking at this again, I think this might just be a documentation bug. I have a very simple git repository with four commits in a line

```
> git log --pretty=oneline --abbrev-commit --graph --decorate
* b107891 (HEAD, master) Another commit.
* d57f23e Third commit.
* 426cdae (start) Second commit.
* 0bfe8e9 First commit.
```

Running git log start..master returns d57 and b10 as expected:

```
> git log --pretty=oneline --abbrev-commit --graph --decorate start..master
* b107891 (HEAD, master) Another commit.
* d57f23e Third commit.
```

According to the wiki, in the Change Filter, Since maps to the first part of the range, and Until maps to the end of the range. However, running this returns 0 results. 


            using (var repo = new Repository(RepoRoot))
            {
                var commitFilter = new CommitFilter
                {
                    Since = repo.Branches["start"],
                    Until = repo.Branches["master"]
                };

                List<Commit> commits = repo.Commits.QueryBy(commitFilter).ToList();

                Console.WriteLine("Found {0} commits.", commits.Count());

                foreach (Commit commit in commits) 
                {
                    Console.WriteLine("Commit: {0}", commit.Sha);
                }
            }

> Found 0 commits.

Switching Since to "master" and Until to "start" returns the same output as git log. 

```
Found 2 commits.
Commit: b10789125ceb514c69b0e96823a11b061269607a
Commit: d57f23ec70123b82464bc478bfea98e9a956c2da
```

**Comment by carlosmn** [comment]
We changed the names of the commit filter so they don't use time terms for the graph, which is not a time-based thing.
