### ISSUE TITLE
AccessViolationException in Proxy.git_remote_push

### ISSUE THREAD

**Issue by golsby** [libgit2/libgit2sharp#1217]
**Summary**
`GitPushOptions` (CS) signature mismatch with `git_push_options` (C) causes uninitialized memory and access violation when calling `git_remote_push` in libgit2 when credentials are passed for accessing a private repo. The `custom_headers` member of `git_push_options` points to random garbage after the call is marshalled because the corresponding member is missing from `GitPushOptions`.

As a side note, GitHub Desktop cannot push to our private repo, but it doesn't report anything useful when it fails. I imagine this is the cause.

**To Reproduce:**
Using commit 9d17afec6a6dd74d7afac10ddee7203727cdbcdd (Oct 23) I'm trying to push using the following code. I'm pushing to a private repo on GitHub using `username/personal access token` pair.

```
      if (string.IsNullOrWhiteSpace(Branch))
        Branch = "master";

      using (var repo = new Repository(WorkingTree))
      {
        Log.LogMessage("Pushing branch '{0}' from '{1}'", Branch, WorkingTree);
        LibGit2Sharp.PushOptions options = new LibGit2Sharp.PushOptions();
        options.CredentialsProvider = (_url, _user, _cred) => new UsernamePasswordCredentials { Username = Username, Password = Password };
        var branch = repo.Branches[Branch];
        lock (m_lock)
        {
          repo.Network.Push(branch, options);
        }
      }
      return true;
```

This results in a 'System.AccessViolationException'.

**Details**
Debugging into this, I see that `git_remote_push` on line 2450 of remote.c takes `git_push_options` as a parameter. From remote.h:
```
/**
 * Controls the behavior of a git_push object.
 */
typedef struct {
	unsigned int version;

	/**
	 * If the transport being used to push to the remote requires the creation
	 * of a pack file, this controls the number of worker threads used by
	 * the packbuilder when creating that pack file to be sent to the remote.
	 *
	 * If set to 0, the packbuilder will auto-detect the number of threads
	 * to create. The default value is 1.
	 */
	unsigned int pb_parallelism;

	/**
	 * Callbacks to use for this push operation
	 */
	git_remote_callbacks callbacks;

	/**
	 * Extra headers for this push operation
	 */
	git_strarray custom_headers;
} git_push_options;
```

The corresponding C# type is `GitPushOptions`
defined as
```
namespace LibGit2Sharp.Core
{
    [StructLayout(LayoutKind.Sequential)]
    internal class GitPushOptions
    {
        public int Version = 1;
        public int PackbuilderDegreeOfParallelism;
        public GitRemoteCallbacks RemoteCallbacks;
    }
}
```

Notice that `GitPushOptions` is missing the `custom_headers` member.

**Comment by golsby** [comment]
I attempted to fix this by changing `GitPushOptions` to be:

```
    [StructLayout(LayoutKind.Sequential)]
    internal class GitPushOptions
    {
        public int Version = 1;
        public int PackbuilderDegreeOfParallelism;
        public GitRemoteCallbacks RemoteCallbacks;
        public GitStrArrayManaged CustomHeaders;
    }
```

but I get an AccessViolation exception elsewhere.

**Comment by nulltoken** [comment]
@golsby Awesome repro case. Thanks!

**Comment by golsby** [comment]
You're welcome. I hope a fix for this will help the GitHub desktop team release a build that can push to private repos!

**Comment by nulltoken** [comment]
@golsby I've granted you with push bit to https://github.com/nulltoken/lg2s_issues_1217 (a private repo I've used to troubleshoot this issue).

By applying the following changes on top of vNext, I've been able to get rid from the first `AccessViolationException` you mentioned. However, I'm unable to hit the second one.

FWIW, I'm running on a Win10/x64

Any idea?

```diff
diff --git a/LibGit2Sharp/Core/GitPushOptions.cs b/LibGit2Sharp/Core/GitPushOptions.cs
index d4bbcdc..075a62b 100644
--- a/LibGit2Sharp/Core/GitPushOptions.cs
+++ b/LibGit2Sharp/Core/GitPushOptions.cs
@@ -8,5 +8,6 @@ internal class GitPushOptions
         public int Version = 1;
         public int PackbuilderDegreeOfParallelism;
         public GitRemoteCallbacks RemoteCallbacks;
+        public GitStrArrayManaged CustomHeaders;
     }
 }
diff --git a/LibGit2Sharp.Tests/PushFixture.cs b/LibGit2Sharp.Tests/PushFixture.cs
index 7dde5ef..77e84e6 100644
--- a/LibGit2Sharp.Tests/PushFixture.cs
+++ b/LibGit2Sharp.Tests/PushFixture.cs
@@ -1,5 +1,6 @@
 using System;
 using System.Collections.Generic;
+using System.Diagnostics;
 using System.IO;
 using System.Linq;
 using LibGit2Sharp.Handlers;
@@ -60,6 +61,44 @@ private void AssertPush(Action<IRepository> push)
             }
         }
 
+
+        [Fact]
+        public void e1217()
+        {
+            var scd = BuildSelfCleaningDirectory();
+
+            string clonedRepoPath = Repository.Clone("https://github.com/nulltoken/lg2s_issues_1217.git", scd.DirectoryPath,
+                new CloneOptions
+                {
+                    CredentialsProvider = dd,
+                });
+
+            PushOptions options = new PushOptions()
+            {
+                CredentialsProvider = dd,
+                OnPushStatusError = ss,
+            };
+
+            using (var repo = new Repository(clonedRepoPath))
+            {
+                var file = Guid.NewGuid().ToString();
+                Touch(repo.Info.WorkingDirectory, file, "tada");
+                repo.Stage(file);
+                repo.Commit("de", Constants.Signature, Constants.Signature);
+                repo.Network.Push(repo.Network.Remotes["origin"], "HEAD", @"refs/heads/master", options);
+            }
+        }
+
+        private Credentials dd(string url, string usernamefromurl, SupportedCredentialTypes types)
+        {
+            return new UsernamePasswordCredentials { Username = "your_name", Password = "your_password" };
+        }
+
+        private void ss(PushStatusError pushstatuserrors)
+        {
+            Trace.WriteLine(pushstatuserrors.Message);
+        }
+
         [Fact]
         public void CanPushABranchTrackingAnUpstreamBranch()
         {
```

/cc @carlosmn @dahlbyk @ethomson @jamill @shiftkey to which I've also granted push access to the repo

**Comment by golsby** [comment]
I'll take a look at your branch shortly. I'm running on Windows 10/x64, but inside an MSBuild custom task. It appears that MSBuild is running 32-bit, so my case ends up loading 32-bit libgit2.

**Comment by golsby** [comment]
Gosh, after paying close attention to figure out the first exception, I didn't actually read the second exception: *The branch '{0}' (\"{1}\") that you are trying to push does not track an upstream branch.*

Looks like that's just simple user error! Following [these instructions](http://stackoverflow.com/questions/22981934/how-to-use-libgit2sharp-to-create-a-new-branch-from-local-to-remote) results in a successful push to your test repo.

Thanks for the quick attention!

**Comment by nulltoken** [comment]
@golsby As you've done all the hard work (figuring our the bug, reporting it and with a proposal for a fix, ...), how would you feel about sending a PR? :wink:

**Comment by shiftkey** [comment]
> As a side note, GitHub Desktop cannot push to our private repo, but it doesn't report anything useful when it fails. I imagine this is the cause.

What sort of server is your private repository on? GitHub? Or somewhere else? I'd love to confirm this is fixed for a future update.

**Comment by shiftkey** [comment]
I did a quick test on my end with private repositories and I couldn't create it.

If you're still seeing this with GitHub Desktop there's a log file located at `%LOCALAPPDATA%\GitHub\TheLog.txt` which you can attach to the form at https://github.com/support - this will make it's way to my team for us to investigate further.

**Comment by golsby** [comment]
Hi Brendan,

It looks like we can now push to our repo with the latest GitHub Desktop.
Our repo is very large, so it's not terribly responsive, but it does work.

On Thu, Nov 12, 2015 at 3:12 PM Brendan Forster <notifications@github.com>
wrote:

> I did a quick test on my end with private repositories and I couldn't
> create it.
>
> If you're still seeing this with GitHub Desktop there's a log file located
> at %LOCALAPPDATA%\GitHub\TheLog.txt which you can attach to the form at
> https://github.com/support - this will make it's way to my team for us to
> investigate further.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libgit2/libgit2sharp/issues/1217#issuecomment-156266629>
> .
>
-- 
- Brian

Brian Gillespie | Rhinoceros Development | McNeel
(206) 634-4592 | brian@mcneel.com
