### ISSUE TITLE
The Myers diff algorithm is spelt incorrectly

### ISSUE THREAD

**Issue by tomcsmith1990** [libgit2/libgit2sharp#1228]
`DiffAlgorithm.Meyers` contains an extra `e`.

The value should be `DiffAlgorithm.Myers` according to the [git docs](https://git-scm.com/docs/git-diff): 
`--diff-algorithm={patience|minimal|histogram|myers}`

**Comment by ethomson** [comment]
:+1:

Apologies to Dr Myers.

**Comment by nulltoken** [comment]
Dammit! I'm the one to be blamed for this :cry: 

@tomcsmith1990 Would you feel like sending a Pull Request to fix this?

**Comment by tomcsmith1990** [comment]
Sure. No problems with breaking API changes at this point?

**Comment by nulltoken** [comment]
No, we're lucky. This has not been released as part of a stable NuGet package. So we don't need to go the `[Obsolete]` way.
