### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by gunnamrajesh** [libgit2/libgit2sharp#1238]
When will be next formal release of libgit2sharp?

**Comment by nulltoken** [comment]
I was planning to release v0.22 last week but got side tracked. I'm going to try and make this happen before Monday.

**Comment by gunnamrajesh** [comment]
Thank you for the information.

**Comment by ZxoR** [comment]
Can we get info about the new version?

**Comment by biyimaks** [comment]
I'm also eager to get my hands on the next release. Looking forward to the rebase functionality

**Comment by jzoss** [comment]
Any idea when v0.22 release will be official ?

**Comment by carlosmn** [comment]
The release is in progess, see #1266
