### ISSUE TITLE
The name 'Repository' does not exist in the current context

### ISSUE THREAD

**Issue by c0otlass** [libgit2/libgit2sharp#1241]
hi
first of all i must mention that i am beginner in asp.net 
i want to use libgit2sharp library in my project so i added "LibGit2Sharp.NativeBinaries" to my project [link](https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries/) but i could not use its classes and functions
for example how could i make  directory whit git ?
i wrote this simple code
```
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace TestGit
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            string rootedPath = Repository.Init("c://myGit/", true);
        }
    }
}
```
but i got this error
```
Severity	Code	Description	Project	File	Line
Error	CS0103	The name 'Repository' does not exist in the current context	TestGit	C:\Users\c0otlass\Documents\Visual Studio 2015\Projects\TestGit\TestGit\WebForm1.aspx.cs	19

```
what else should i do? am i missing some steps? is there any full tutorial of importing and using libgit2sharp ?
i am beginner ... so sorry for my basic question
thanks

**Comment by whoisj** [comment]
You'll need both the .NET binaries as well as the native binaries to make this work.

A `using LibGit2Sharp;` statement at the top of your file will go a long way towards letting the compiler/linker know where to look to find a `Repository` class definition.

You will need to make sure that the project knows about the `LibGit2Sharp.dll`. You can inform it by add in a reference to it via Visual Studio's Solution Explorer.

**Comment by c0otlass** [comment]
thanks a lot for helping ... 
i build "LibGit2Sharp.dll" with build.libgit2sharp.cmd and added to my references
i added "using LibGit2Sharp;" too and wow .... there was no error 
my new code is:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using LibGit2Sharp;
namespace TestGit
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            string rootedPath = Repository.Init("c:\\temp\\rooted\\path", true);
        }
    }
}
```
but when i click in button i throw an exception:
```
{"The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception."} 
```
whit an innerExeption
```
Unable to load DLL 'git2-821131f': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
 what did i do wrong?!

**Comment by bording** [comment]
How are you adding LibGit2Sharp to you project? Are you building from source?

If you just want to use it in your project, you should add it via NuGet instead, and everything should be taken care of for you automatically.

**Comment by c0otlass** [comment]
thanks for helping bording
i added "LibGit2Sharp.NativeBinaries" whit NuGet like [here] (https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries/) but there was an error and i could not have "using LibGit2Sharp;"
so i cloned [libgit2sharp] (https://github.com/libgit2/libgit2sharp) and build  it "build.libgit2sharp.cmd" then there was LibGit2Sharp.dll in bulid folder
i added it to my references ... my first problem solved but know it throw another exception that i explained

**Comment by bording** [comment]
Instead of adding LibGit2Sharp.NativeBinaries with NuGet, remove that and LibGit2Sharp directly with NuGet.

That will add LibGit2Sharp and the required native binaries package to your project.

**Comment by c0otlass** [comment]
thanks a lot
it worked ...
