### ISSUE TITLE
problem in Git Commit Wiki

### ISSUE THREAD

**Issue by c0otlass** [libgit2/libgit2sharp#1242]
Hi
 i have two problem in Git Commit Wiki :
1.i was reading an using this [wiki] (https://github.com/libgit2/libgit2sharp/wiki/Git-commit) for how to commit 
when i enter this line of code 
```
Commit commit =repo.ObjectDatabase.CreateCommit(txtCommitNote.Text,author,committer, tree,repo.Commits);
```
 i got this error:
```
There is no argument given that corresponds to the required formal parameter 'prettifyMessage' of 'ObjectDatabase.CreateCommit(Signature, Signature, string, Tree, IEnumerable<Commit>, bool, char?)'	
```
i think there is missing point in wiki page !!

2.
in this line of code
```
    td.Add("filePath.txt", newBlob, Mode.NonExecutableFile);
```
and 
```
    File.WriteAllText(Path.Combine(repo.Info.WorkingDirectory, "fileToCommit.txt"), content);
```
 what are "fileToCommit.txt" and "filePath.txt"? they will create in our repository?
thanks for helping

**Comment by c0otlass** [comment]
Hi again 
could any body help me ...
what is the correct code for commit  a file in bare repository?
this code in wiki is probably wrong

```

**Comment by nulltoken** [comment]
@c0otlass Hey! As stated in the README, programming related questions are expected to be rather posted on StackOverflow.We tend to keep the issue tracker for bugs and features.

Meanwhile **[CanCreateACommit:ObjectdatabaseFixture.cs](https://github.com/libgit2/libgit2sharp/blob/bd4e4c9407ed0ac1ad4834ba8493d4d523a18a98/LibGit2Sharp.Tests/ObjectDatabaseFixture.cs#L419-L440)** may get you started.

Cheers!

**Comment by c0otlass** [comment]
hi ...
that's right .... thanks for answering and helping ...
but please update its wiki page
thanks again
