### ISSUE TITLE
Repository.Clone - Out of Memory Exception

### ISSUE THREAD

**Issue by v-tapate** [libgit2/libgit2sharp#1245]
Hello,

While I clone repository, it is throwing me out of memory exception.

StackTrace: 
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
   at GitLibrary.Program.Main(String[] args) in C:\Repository\Practice\GitLibrary\GitLibrary\Program.cs:line 27
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by carlosmn** [comment]
Does this happen with every repository? Do you have large objects in the repository you're trying to clone which might legitimately cause an OOM?

**Comment by nulltoken** [comment]
From what I see, this happens when cloning from Visual Studio, doesn't it?

/cc @ethomson @jamill

**Comment by v-tapate** [comment]
Yes, I am doing clone from Visual Studio.

**Comment by nulltoken** [comment]
> Yes, I am doing clone from Visual Studio.

As pointed out by @ethomson in https://github.com/libgit2/libgit2sharp/issues/793#issuecomment-64431965, filing a bug in https://connect.microsoft.com/ may speed up the process of seeing this fixed in VisualStudio.

Meanwhile, could you please help us reproduce this by pointing us to a public repository where cloning triggers the same exception?

**Comment by nulltoken** [comment]
Taking a deeper look at the call stack, it appears the problem doesn't seem to happen while cloning through Visual Studio, but by directly interacting with LibGit2Sharp through a console app. You can safely forget about the "connect" recommendation, then.

We'd still be very interested in a repro case.

**Comment by v-tapate** [comment]
You mean, it is happening because of directly call from console application.

**Comment by whoisj** [comment]
> You mean, it is happening because of directly call from console application.

I believe he means that it is happening in a console application (see `GitLibrary.Program.Main(String[] args) in C:\Repository\Practice\GitLibrary\GitLibrary\Program.cs` above) and not directly in VS therefore filing a https://connect.microsoft.com/ bug is the wrong approach.

**Comment by v-tapate** [comment]
@nulltoken : Could you please provide me public repository uri ?

**Comment by nulltoken** [comment]
>> @nulltoken : Could you please provide me public repository uri ?

Sorry I was unclear earlier. Could you please share with us the url of the repository that raises this problem? Wouldn't that be possible (private repo for instance), could you please find out a public repository where cloning triggers the same problem for you? Thanks in advance.

**Comment by v-tapate** [comment]
I don't have public Url.

**Comment by v-tapate** [comment]
@carlosmn : I have created new repository with few objects and it is working fine. but if I have large objects repository then it is throwing out of memory. It should not be happen as I have done clone from VS and it is working fine. It is not working using LibGit2Sharp.

**Comment by jamill** [comment]
Could you let us know what version of LibGit2Sharp you are using?

**Comment by v-tapate** [comment]
I am using 0.21.0.176 version. Well. I am suspecting the issue as If I run as default mode with Any CPU then program run with 32 bit. because of the might be it throw error. I run program with 64 bit and it is working fine.

**Comment by jeffhostetler** [comment]
The OOM is actually being thrown by the underlying libgit2 library.  I fixed this problem (https://github.com/libgit2/libgit2/pull/2932) and it was merged into in libgit2 in March 2015.

According to nuget.org (https://www.nuget.org/packages/LibGit2Sharp/) version 0.21.0.176
was shipped February 2015, so I'm going to assert that this is the same problem.

Can you try a newer version of LibGit2Sharp?

**Comment by carlosmn** [comment]
If moving to 64 bits solves it, it looks extremely likely for this to be culprit. The libgit2sharp prerelease packages should be fixed and be API-compatible.

**Comment by ethomson** [comment]
Fixed with the release of v0.22
