### ISSUE TITLE
Does Git-Clone support Personal access tokens ?

### ISSUE THREAD

**Issue by lbrader** [libgit2/libgit2sharp#1256]
I'm trying to clone a private repository.  But I have 2 phase authorization in place.   In Octokit I have been using tokens with no issues.  

Is there a way to use tokens with libgit2sharp?  

thanks

**Comment by shiftkey** [comment]
Paraphrasing this [stackoverflow](http://stackoverflow.com/questions/24607212/bitbucket-authentication-to-use-libgit2sharp) question:

```csharp
var co = new CloneOptions();
co.CredentialsProvider = (_url, _user, _cred) => 
    new UsernamePasswordCredentials
    {
        Username = "the-access-token", // YOUR TOKEN HERE
        Password = string.Empty
     };
Repository.Clone("https://github.com/libgit2/libgit2sharp.git", "path/to/repo", co);
```

Note: this is specific to GitHub
