### ISSUE TITLE
Add Config Item Bug 

### ISSUE THREAD

**Issue by jzoss** [libgit2/libgit2sharp#1263]
Ok.. so I found a small bug when you add multiple config items. I am using the latest per-release in nuget. 

Take this sample code

```c#
 using (var repo = new Repository(pathtorepo))
            {
                for (int i = 1; i < 10; i++)
                {
                    var settingName = "sample.prefix.setting" + i;
                    var settingValue = "someValue" + i;
                    repo.Config.Set(settingName, settingValue);
                }
            }
```

You would expect to see

```
[sample "prefix"]
	setting1 = someValue1
	setting2 = someValue2
	setting3 = someValue3
        ....
```

What you actually get is 

```
[sample "prefix"]
	setting1 = someValue1
	setting3 = someValue3
	setting4 = someValue4
	setting5 = someValue5
	setting6 = someValue6
	setting7 = someValue7
	setting8 = someValue8
	setting9 = someValue9
[sample "prefix"]
	setting2 = someValue2

```

I have found it is always the 2nd item that it does this with..

**Comment by carlosmn** [comment]
That's not great. I've reproduced this in libgit2 proper. I wonder if it's related to how we write out the end of the file.

**Comment by carlosmn** [comment]
I've created libgit2/libgit2#3654 to show the bug. The bug is purely cosmetic, as the configuration file is perfectly valid and an update to those values does work.

**Comment by carlosmn** [comment]
Fixed in libgit2, it'll make its way into libgit2sharp by the next release.
