### ISSUE TITLE
reinforcement for Commits.QueryBy

### ISSUE THREAD

**Issue by Aimeast** [libgit2/libgit2sharp#1276]
Can we introduce the override `QueryBy(string path, CommitFilter filter)` ?

usage like
```
var commits = repo.Commits.QueryBy(path, new CommitFilter { IncludeReachableFrom = commit })
```

**Comment by carlosmn** [comment]
If you'd like to add it, `FileHistory` already takes in a `CommitFilter`.

**Comment by Aimeast** [comment]
I got it, Maybe I will made a PR.
