### ISSUE TITLE
Repository.RetrieveStatus methods takes so long with latest git client

### ISSUE THREAD

**Issue by vardium** [libgit2/libgit2sharp#1277]
`Repository.RetrieveStatus()` method takes too much time after upgrading to the latest windows git client ([v2.7.2](https://github.com/git-for-windows/git/releases/tag/v2.7.2.windows.1)). 
The repositories cloned via older versions ([v2.5.3](https://github.com/git-for-windows/git/releases/tag/v2.5.3.windows.1) and older) works nice (instantly gathers the result), while with newer versions it may take up to 60-70 seconds in my case.

**Comment by ethomson** [comment]
What version of LibGit2Sharp are you running?  Sounds like you're running 0.21, which didn't understand newer git's timestamps in the index, and so reloaded the cache.

Can you upgrade to [0.22](https://github.com/libgit2/libgit2sharp/releases/tag/v0.22)?

**Comment by vardium** [comment]
Yes, I just checked, it was 0.22.0-pre20151003111314. Upgrading solved the problem. Thanks.
