### ISSUE TITLE
View additions/deletions after pull/fetch

### ISSUE THREAD

**Issue by dragondgold** [libgit2/libgit2sharp#1296]
I'm doing a fetch from a repository with this code:

```
                    FetchOptions options = new FetchOptions();
                    options.CredentialsProvider = new CredentialsHandler(
                        (url, usernameFromUrl, types) =>
                            new UsernamePasswordCredentials()
                            {
                                Username = USERNAME,
                                Password = PASSWORD
                            });
                    repo.Network.Fetch(remote, options);             
```

Is it possible to view the modified files or the number of additions and deletions affected by the `Fetch` operation?

**Comment by carlosmn** [comment]
There are no files affected by the fetch operation as it only updates the remote-tracking branches. What you can do is keep track of which references were updated (as reported by the callback) and then perform diffs on those updates.
