### ISSUE TITLE
Can we clone only subfolder/folder in git repository

### ISSUE THREAD

**Issue by kunjan13** [libgit2/libgit2sharp#1297]
Hello

Is there a way to specify folder name i want to clone, 
cuurently i only want to checkout a folder and i have to clone whole repository which taking lot of space on server.

Below is my code:
LibGit2Sharp.Repository.Clone(repositoryPath.Value, workingDirPath,
                                                  new CloneOptions
                                                  {
                                                      CredentialsProvider = credHandler,
                                                      IsBare = false,
                                                      BranchName = Constants.GitBranch,
                                                      Checkout = true
                                                  });

**Comment by carlosmn** [comment]
This is not something that is supported by the Git system or the network protocol. If you want to save space you may be able to use shallow cloning (but not via libgit2 as the feature is not supported) or use a deployment which does not rely on the version control but sends out a single state.
