### ISSUE TITLE
How to add all files to the repository (git add *)?

### ISSUE THREAD

**Issue by Rowandish** [libgit2/libgit2sharp#1299]
As explained in the title, I'd like to add all file to the repository working area (`git add *`).
I try the following codes:

`repository.Index.Add("*");`

`repository.Index.Add(".");`

but I always get `Invalid path`.

Is there a way (other than looping through all files in folder) to solve this?

Thanks!

**Comment by carlosmn** [comment]
Looking though all of the files is what you're doing when you run `git add *` on your shell. git receives a list of every file and directory in your current directory and loops over them to add them. The `Index` is the underlying data structure, and not the `git add` command.

We have some code which behaves like `git add` in `Repository.Stage()` (or `Commands.Stage()` if you're running `master`), which you can pass pathspecs to like `*`.

For future reference, we prefer to keep the issue tracker for issues and have questions on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2sharp) which fits better with a Q&A format.

**Comment by Rowandish** [comment]
Ok, thanks!
