### ISSUE TITLE
How to run `git diff origin/master`?

### ISSUE THREAD

**Issue by dragondgold** [libgit2/libgit2sharp#1303]
I have read the wiki [here](https://github.com/libgit2/libgit2sharp/wiki/Git-diff) but couldn't found how would I run `git diff origin/master` using `libgit2sharp`. Is it possible?

**Comment by carlosmn** [comment]
The diff doesn't care where the tree comes from. It can come from `Repository.Head.Tip.Tree` or `Repository.Branches["origin/master"].Tip.Tree` as you can see at https://github.com/libgit2/libgit2sharp/wiki/Git-diff#return-changes-in-index-and-working-directory

For future reference, we prefer to keep the issue tracker for issues. Questions should be on StackOverflow which matches the Q&A format better.
