### ISSUE TITLE
Using NTLM/Kerberos with username/password

### ISSUE THREAD

**Issue by zs-zs** [libgit2/libgit2sharp#1308]
We used libgit2sharp 0.13 in one of our projects, and we needed to implement our own smart subtransport for authenticating to TFS as described in this [blog post](http://gasparnagy.com/2013/11/connect-to-tfs-2013-git-repository-with-libgit2sharp/). (Our requirement is to authenticate to TFS on behalf of a specific user with username/password)

However this solution does not work with the latest version of libgit2sharp. If I use `DefaultCredentials` I am able to connect however it will use my credentials and I cannot specify a username/password.

I also tried to migrate the [old implementation](https://github.com/gasparnagy/Sample_NtlmGitTest) of the subtransport to work with the new version of libgit2sharp with no luck. Now I'm getting AccessViolationExceptions: 

> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Which is not the ideal behavior I guess :)

So the question is it possible at all to use NTLM/Kerberos authentication with username/password with the latest version of libgit2sharp?

**Comment by ethomson** [comment]
I wouldn't recommend using a custom subtransport.

LibGit2Sharp supports NTLM and Kerberos with default credentials out of the box.  At the moment, we don't support specified credentials with NTLM.  If you need to specify credentials, you will have to use Basic.

**Comment by ethomson** [comment]
You can now specify credentials when using NTLM.  We still encourage you to not use a custom subtransport.
