### ISSUE TITLE
Error when trying to update the repository

### ISSUE THREAD

**Issue by dhiogoacioli** [libgit2/libgit2sharp#1319]
After cloning a repository and try to call the PULL command, always gives the same error:

The current branch is configured to merge with the reference 'refs / heads / MASTER' from the remote, but this reference was not fetched.

    public void RecuperarRepositorio()
        {
            if (!Directory.Exists(DS_CAMINHO_DESTINO + @"\.git"))
            {
                CriarRepositorio();
            }
            else
            {
                AtualizarRepositorio();
            }
        }

        private void CriarRepositorio()
        {
            var path = Repository.Clone(DS_CAMINHO_GIT, DS_CAMINHO_DESTINO, RetornaCloneOptions());
        }

        private void AtualizarRepositorio()
        {
            using (var repo = new Repository(DS_CAMINHO_DESTINO + @"\.git\"))
            {
                foreach (Remote remote in repo.Network.Remotes)
                {
                    repo.Network.Fetch(remote, RetornaPullOptions().FetchOptions);
                }

                repo.Network.Pull(RetornaAssinatura(), RetornaPullOptions());
            }
        }

        private CloneOptions RetornaCloneOptions()
        {
            var co = new CloneOptions();
            co.BranchName = NM_BRANCH;
            co.CredentialsProvider = (_url, _user, _cred) => RetornaCredencial();
            co.CertificateCheck += delegate(Certificate certificate, bool valid, string host) { return true; }; 
            return co;
        }

        private PullOptions RetornaPullOptions()
        {
            var po = new PullOptions();
            po.FetchOptions = new FetchOptions();
            po.FetchOptions.TagFetchMode = TagFetchMode.All;
            po.FetchOptions.CredentialsProvider = (_url, _user, _cred) => RetornaCredencial();
            po.FetchOptions.CertificateCheck += delegate(Certificate certificate, bool valid, string host) { return true; };
            po.MergeOptions = new MergeOptions();
            po.MergeOptions.FileConflictStrategy = CheckoutFileConflictStrategy.Theirs;
            return po;
        }

**Comment by ethomson** [comment]
Hi @dhiogoacioli!  Sorry you're having trouble.  I recommend that you post this query on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2sharp):  we use the GitHub issue tracker for tracking bugs and feature requests.  It is relatively low-traffic and used by the core developers.  On the other hand, there are many people following on StackOverflow who use LibGit2Sharp and who can provide assistance.
