### ISSUE TITLE
HG incoming analogue

### ISSUE THREAD

**Issue by MizarSG** [libgit2/libgit2sharp#1321]
Hello. Can I get incoming changes? I found this solution:
git fetch && git log ..@{u}

I call fetch but i can't understand how i can take incoming commits. I don't see them in repository.Commits collection

Thank you

**Comment by txdv** [comment]
After pulling you can access the branch easily:


```csharp
Branch trackedBranch = repo.Branches["origin/theBranch"];
```

Also, the general consensus is that the github issue tracker is for actual issues and not for asking question. If you want to ask a question use StackOverflow instead.

**Comment by carlosmn** [comment]
You can ask the branch for what its upstream is and then ask for the log between those two.
