### ISSUE TITLE
git rev-parse

### ISSUE THREAD

**Issue by gymguy** [libgit2/libgit2sharp#1325]
Hi,

Is git rev-parse available?
I do not see the page?
How can I use it?

Regards
gymguy

**Comment by whoisj** [comment]
What do you want to use it for? Git-rev-parse is a rather generic quiet utility.

**Comment by gymguy** [comment]
Hi,

I want to get the working branch by "git rev-parse --abbrev-ref HEAD" and also the commit hashes like
"git rev-parse --short HEAD" or git rev-parse HEAD".

May be you can suggest me the alternative?

**Comment by whoisj** [comment]
The tests have some fairly good examples of how to use the library. For example, https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp.Tests/ReferenceFixture.cs#L345 looks similar to what you need. Open the library, load up the branches, query for HEAD, read details, etc.

G'luck!

**Comment by carlosmn** [comment]
You can find an object's short id by calling a repository's `ObjectDatabase`'s `ShortenObjectId()` method.

For future reference, we prefer to keep this issue tracker for bugs, and have questions about usage in StackOverflow, which is better suited to that.

**Comment by shangsun** [comment]
How do I get the full hash from short hash using gitlib? Eg: git rev-parse 3cdd5d
Is there any repository feature I can take advantage from?

**Comment by ethomson** [comment]
Hi @shangsun, please ask at [StackOverflow](https://stackoverflow.com/questions/tagged/libgit2sharp).  Thanks!

**Comment by shangsun** [comment]
https://stackoverflow.com/q/47720691/2904711
