### ISSUE TITLE
Git log commit messages

### ISSUE THREAD

**Issue by Odraio** [libgit2/libgit2sharp#1332]
Hello all,

I would like to retrieve all log commit messages of a specific file (based on the name of the file). Is it also possible to retrieve the content of a file of a specific commit (based on the SHA)?

Are these features availabe? Could you point me in the right direction and/ or provide a code snippet?

Thank you in advance!

**Comment by txdv** [comment]
here is an example on how to query using a filename https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp.Tests/FileHistoryFixture.cs#L47

**Comment by ethomson** [comment]
Yep!  @txdv is correct - if you have further questions, [please ask on the LibGit2Sharp tag on StackOverflow](http://stackoverflow.com/questions/tagged/libgit2sharp).  Thanks!

**Comment by Odraio** [comment]
I created a topic on Stackoverflow: http://stackoverflow.com/questions/38272848/retrieve-git-file-commit-messages. Could you help me with the described problem? Thank you in advance!
