### ISSUE TITLE
How to set User Agent?

### ISSUE THREAD

**Issue by AndrewBragdon** [libgit2/libgit2sharp#1333]
Hi,

I need to set the user agent for libgit2sharp.  How to do that?  Seems like CloneOptions object needs to have this.

Thanks!

**Comment by txdv** [comment]
[You can now set your own user-agent to be sent for HTTP requests by using the GIT_OPT_SET_USER_AGENT with git_libgit2_opts().](https://github.com/libgit2/libgit2/blame/ebeb56f0f53803e5c11429b01618e0182ad59fca/CHANGELOG.md#L66)

**Comment by ethomson** [comment]
Fixed via #3851
