### ISSUE TITLE
how to checkout tag on v0.17 version

### ISSUE THREAD

**Issue by wteng** [libgit2/libgit2sharp#1335]
I want to checkout a tag on v0.17 version , is there a sample code  ?

**Comment by shiftkey** [comment]
```
using (var repo = new Repository("path-to-repo"))
{
    var branch = repo.Checkout("master");}
```

**Comment by wteng** [comment]
Dear , 
I can use the code below to checkout a branch,

>
using (var repo = new Repository("path-to-repo"))
{
   Branch branch = repo.Branches["refs/remotes/origin/branch_1.0.0"];
    RepositoryExtensions.Checkout(repo,branch);
}


but to tag , the code 
>
using (var repo = new Repository("path-to-repo"))
{
   // It's write
   Tag tag = repo.Tag["refs/tags/tag_1.0.0"];
   // the branch is null
  Branch branch = repo.Branches["refs/tags/tag_1.0.0"];
}

**Comment by shiftkey** [comment]
@wteng just use the short name for the tag: `repo.Checkout("tag_1.0.0");`

**Comment by wteng** [comment]
you are right , and the code `repo.Checkout("refs/tags/tag_1.0.0")` will do the same thing.

**Comment by wteng** [comment]
thank you for a lot !
