### ISSUE TITLE
RepositoryOptions config locations obsolete

### ISSUE THREAD

**Issue by txdv** [libgit2/libgit2sharp#1340]
The location fields of the configuration files in RepositoryOptions have been obsoleted: https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/RepositoryOptions.cs#L39-L62

I moved [some tests](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp.Tests/RepositoryOptionsFixture.cs#L175-L179) to the GlobalSettings API like this:

``` csharp
            GlobalSettings.SetConfigSearchPaths(ConfigurationLevel.Global, globalLocation);
            GlobalSettings.SetConfigSearchPaths(ConfigurationLevel.Xdg, xdgLocation);
            GlobalSettings.SetConfigSearchPaths(ConfigurationLevel.System, systemLocation);

            var options = new RepositoryOptions();
```

But when I ran it, it returned some exception and I realized that we really can't obsolete those APIs since they are functionally not equal. The error was raised because the tests are running in parallel and with GlobalSettings.SetConfigSearchPath I set the same config path for **every** other in currently parallel running test, which yields exceptions in an non deterministic way (race conditions and what not). Also GlobalSettings.SetConfigSearchPath sets the search paths for the config files, not the config file path directly.

So what is the idea behind removing these?

**Comment by txdv** [comment]
Ok, I investigated a bit further, and there is a [git_repository_set_config](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/Configuration.cs#L65) method, which is invoked from this [internal constructor](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/Configuration.cs#L32) and the only time it is used is in [BuildFrom with the a argument null](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/Configuration.cs#L202).

So the the general functionality is in the code, but it can never be run by a simple user...

**Comment by carlosmn** [comment]
Those tests are there to make sure the feature keeps working during the deprecation period. They should go away once we no longer offer the feature.
