### ISSUE TITLE
Adopt Nuget 3 RID for native asset deployment

### ISSUE THREAD

**Issue by damageboy** [libgit2/libgit2sharp#1341]
Nuget 3.0 add the ability for packages to include (either via dependent packages or via `runtimes/` inside the package) native assets.

For a more complete description:
http://www.natemcmaster.com/blog/2016/05/19/nuget3-rid-graph/

As the current deployment mechanics rely on some custom MSBuild trickery, I would like to start a discussion around adopting a more "standardized" approach for packaging and deploying native dependencies in libgit2sharp (Not that it exists)

Are there any thoughts / previous discussions around this?
I didn't see any nuget 3 / RID related discussions before...

**Comment by bording** [comment]
Hey @damageboy,

This is already in progress!

Take a look at https://github.com/libgit2/libgit2sharp.nativebinaries/pull/40.

**Comment by damageboy** [comment]
Thanks I will follow that issue :)

**Comment by ethomson** [comment]
Note that beginning with [0.23.0-pre20160803182831](https://www.nuget.org/packages/LibGit2Sharp/0.23.0-pre20160803182831), we build packages that are compatible with the new `project.json` standards.

Please open an issue if you have trouble working with net451 `project.json` projects.  (Note that we do _not_ yet support .NET Core).
