### ISSUE TITLE
Unable to load DLL 'git2-785d8c4': The specified module could not be found.

### ISSUE THREAD

**Issue by salmanlone** [libgit2/libgit2sharp#1342]
Hello,

I am using this library in my asp .net core project where the error "Unable to load DLL 'git2-785d8c4': The specified module could not be found." is coming when i try to access IsValid() function of Repository class. What i have figured out, there is no such support in this library for asp .net core. 

I am trying to change this library into .net core but it is taking time to complete. so, i am writing this to ask if anyone can make this library compatible for asp .net core.

Thanks in advance and keep contributing.

Regards,
Salman

**Comment by txdv** [comment]
There is already an effort going on to port it to PCL: https://github.com/libgit2/libgit2sharp/issues/1293
