### ISSUE TITLE
Can't update LibGit2Sharp.NativeBinaries in VS 2015

### ISSUE THREAD

**Issue by zezba9000** [libgit2/libgit2sharp#1343]
Can't update LibGit2Sharp.NativeBinaries. Are the NuGet packages broken?

> Unable to resolve dependencies. 'LibGit2Sharp.NativeBinaries 1.0.137' is not compatible with 'LibGit2Sharp 0.22.0 constraint: LibGit2Sharp.NativeBinaries (= 1.0.129)'.

VS 2015 Update 3 with latest patch.
Win10.

**Comment by ethomson** [comment]
The native binaries are completely tied to a particular version of LibGit2Sharp.  You would segfault if you tried to use a different version of the native binaries.

Why are you trying to update the native binaries?  Are you trying to do development of LibGit2Sharp _itself_, or are you just trying to _use_ LibGit2Sharp in your application?

**Comment by zezba9000** [comment]
Here is a screenshot. It says the native binaries are out of date.
https://s31.postimg.org/lm7j3cvsr/Untitled.png

**Comment by ethomson** [comment]
That's normal and nothing to worry about.  If you use a newer version of LibGit2Sharp (select "Include Prereleases") then you will get the newer native binaries.  Again, a particular build of LibGit2Sharp is 100% tied to a particular build of the native binaries.  You cannot upgrade one without the other, nor should you try to, as that would leave you with a poorly functioning system.

**Comment by zezba9000** [comment]
Ok thanks, will close the issue.
