### ISSUE TITLE
LEAKS_IDENTIFYING and LEAKS_TRACKING are enabled in release build.

### ISSUE THREAD

**Issue by kik** [libgit2/libgit2sharp#1356]
LEAKS_IDENTIFYING and LEAKS_TRACKING seem to be commented out in release build.

https://github.com/libgit2/libgit2sharp/blob/f916e79575bea0a99d3c67249090f51ff62d4e23/LibGit2Sharp/Core/Handles/Libgit2Object.cs#L8

**Comment by ethomson** [comment]
Right you are!  Could you submit a quick pull request to comment those out?
