### ISSUE TITLE
Console.WriteLines in library

### ISSUE THREAD

**Issue by JakeGinnivan** [libgit2/libgit2sharp#1360]
GitVersion received a PR updating to the latest libgit2sharp pre-release and our tests failed because libgit2sharp is writing to the console. https://github.com/GitTools/GitVersion/pull/1024

See https://github.com/libgit2/libgit2sharp/blob/500cc965dfb85806677c2c061e277e3a988b340a/LibGit2Sharp/Commands/Checkout.cs#L43

I assume this snuck in?

**Comment by shiftkey** [comment]
[Yep](https://github.com/libgit2/libgit2sharp/commit/7f4a17f973e11796a644dcdea5a3b618e9d326a4) - :fire: them to the ground
