### ISSUE TITLE
'filename' appears as both a file and a directory

### ISSUE THREAD

**Issue by watashiSHUN** [libgit2/libgit2sharp#1367]
1. create a file "foo" and committed
2. delete file "foo" and create a folder with the **same name**
3. create a file "foo\bar"
4. `repo.Index.Add(@"foo\bar");` throws exception `'foo\bar' appears as both a file and a directory`

I know that at step 4, if I perform `git add` with the **git.exe**, no error would occur, why is libgit2sharp behave differently?

**Comment by ethomson** [comment]
You indicated that you deleted the file, but did you actually remove it from the index?

**Comment by watashiSHUN** [comment]
When I perform `repo.Index.Add(@"foo\bar");` it should update the index (remove `foo`) for me?

comments before calling [check_file_directory_collision()](https://github.com/libgit2/libgit2/blob/c1b370e9313a13df350974e2237997cc651a5d67/src/index.c#L1341) indicates that collision will be removed

**Comment by ethomson** [comment]
No, the function that you're pointing to is the one that is raising that error.  You need to remove the existing index entry before you add the new entry.

**Comment by watashiSHUN** [comment]
The function I am pointing to should **not** cause error

inside [check_file_directory_collision](https://github.com/libgit2/libgit2/blob/c1b370e9313a13df350974e2237997cc651a5d67/src/index.c#L1138), it uses [has_dir_name](https://github.com/libgit2/libgit2/blob/c1b370e9313a13df350974e2237997cc651a5d67/src/index.c#L1088) and verifies that directories of "foo\bar" was presented in the index, if so it would remove for me (I shouldn't do `repo.Index.Remove("foo");` on my own)

![capture](https://cloud.githubusercontent.com/assets/6531400/18533274/9a59bee0-7a96-11e6-80a4-8a384ab09f9f.PNG)

Since `gitlib2` perform a collision checks, it makes perfect sense for it to resolve collision, otherwise I would need to perform a search in the indexes (duplicate the effort in `has_dir_name`) and perform remove

**Comment by ethomson** [comment]
Yes.  It performs a collision check so that it can error.  It will only perform the remove _if_ `ok_to_replace` is true.  I'm relatively sure that it's not in this case, is it?

You can use the higher level functions like `Stage` if you want the behavior you're describing. If you want to use the low level index manipulation functions then you need to resolve directory/file conflicts yourself.

**Comment by watashiSHUN** [comment]
I am looking at the [add()](https://github.com/libgit2/libgit2sharp/blob/84154d6da2e45995885580c908394cbcf423d23b/LibGit2Sharp/Index.cs#L179) function in `repo.Index.Add(@"foo\bar");`, it seems that it is using the native method of `libgit2` [git_index_add_bypath()](https://github.com/libgit2/libgit2/blob/c1b370e9313a13df350974e2237997cc651a5d67/src/index.c#L1497) and `index_insert` is passed with parameter `replace` set to `true` (int 1) when invoked inside

I believe it should perform the replace....

**Comment by carlosmn** [comment]
There is a difference between the index-manipulating functions and the behaviour of `git-add` and the functions that behave like it.

The index-manipulating functions act on the _data structure_ which has a wider use than implementing `git-add`. If you want `git-add` there's `Stage()` or git itself. Using the index-manipulation functions means you're opting into the data structure, and there it is an error to have a path that is both a directory and a file.
