### ISSUE TITLE
Serious perf regression between 0.22.0 and 0.23.0

### ISSUE THREAD

**Issue by AArnott** [libgit2/libgit2sharp#1368]
I recently upgraded Nerdbank.GitVersioning from libgit2sharp 0.22.0 to 0.23.0-pre20160803182831 because it fixed #1338. But after running my tests, I found there was a _huge_ perf regression in the newer version.

Before, with 0.22.0:
![image](https://cloud.githubusercontent.com/assets/3548/18623272/101c1a9a-7df0-11e6-9f66-d4e2836f13fa.png)

After, with 0.23.0-pre20160803182831:
![image](https://cloud.githubusercontent.com/assets/3548/18623253/f150f3c4-7def-11e6-9b92-4f34b754ab55.png)

Repro instructions:

```
git clone https://github.com/AArnott/Nerdbank.GitVersioning.git
cd Nerdbank.GitVersioning
git checkout 4613c2516787
.\init.ps1
src\Nerdbank.GitVersioning.sln
```
In VS, build the solution. 
In Test Explorer set "_roundtrip" to be your test filter and run tests.

**Comment by AArnott** [comment]
I ran an ETL trace on the regression. It seems very clearly due to an added `new StackTrace(int, bool)` call made from the `Libgit2Object` constructor:

```
Name                                                                       	Inc %	      Inc
 libgit2sharp!LibGit2Sharp.Core.Handles.Libgit2Object..ctor(void*,bool)    	 60.8	   18,112
+ mscorlib.ni!System.Diagnostics.StackTrace..ctor(Int32, Boolean)$##6003121	 58.9	   17,563
```

**Comment by AArnott** [comment]
It looks like `LEAKS_TRACKING` was defined for the build that released to nuget. :(

**Comment by biyimaks** [comment]
@ethomson when will a new build be created?

**Comment by ethomson** [comment]
Please see https://www.nuget.org/packages/LibGit2Sharp/0.23.0-pre20160922233542

Thanks again @AArnott for reporting this, and thanks @biyimaks for the ping.
