### ISSUE TITLE
How to check if all the files are cloned or not in LibGit2Sharp package?

### ISSUE THREAD

**Issue by arushi-gupta** [libgit2/libgit2sharp#1373]
I am a developer and I am using LibGit2Sharp packages to clone the repository code using repository.Clone method provided by LibGit2Sharp using c#. Can you please help me understand whether this method will make sure that it copies all the files and does not miss any files while cloning. Or is there a way I can check programmatically after cloning that I have received all files.

**Comment by ethomson** [comment]
It brings everything.  If you're worried about files on the local filesystem, run `git status` (or the libgit2sharp equivalent) and make sure that status is clean.  If you're worried about the repository and history, run `git fsck` (there is no libgit2sharp equivalent).

But there should be no reason to do this extra step of validation.
