### ISSUE TITLE
Repository.Clone fails with "Filename too long" error

### ISSUE THREAD

**Issue by panuganti** [libgit2/libgit2sharp#1374]
My attempt to use Repository.Clone fails with the error..
LibGit2Sharp.NameConflictException: Failed to stat file '<..some long path..>': The filename or extension is too long.

Is there any solution for this ? 
I believe, I need to set core.longpaths in the global config to true. Is there anyway to do that ?

**Comment by carlosmn** [comment]
`core.longpaths` is something that's specific to the Git for Windows distribution of git. libgit2 does not support it, and neither does most of Windows.

**Comment by panuganti** [comment]
So, what is the solution to this problem ?
Setting global config should be supported by LibGit2Sharp. Is there a way  ?

**Comment by Stepan222** [comment]
You must try using Long Path Tool. This tool enables you to rename, delete, or move the file easily. I have used it multiple times and it works perfectly.

**Comment by rivera15071976** [comment]
Please use Long Path Tool

**Comment by klyse** [comment]
Any update on this problem?

**Comment by ethomson** [comment]
> Any update on this problem?

Nope!  Still fails (just like 99% of all Windows applications)

**Comment by coderitual** [comment]
Maybe you will be this 1% ;)

**Comment by MrShoenel** [comment]
I have now successfully circumvented the problem in Windows 10 by disabling the 260 character limit on NTFS (see below). Setting `git config --system core.longpaths true` did not work for (still set it anyways). I have altered the group policy as per this [post](https://superuser.com/questions/811146/windows-7-file-name-length-limited-to-129-characters#answer-811155) (quote the relevant part here):

> Since Windows 10 there's another option by removing MAX_PATH limitation§. You can enable it by setting HKLM\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled in registry or set `Computer Configuration > Administrative Templates > System > Filesystem > Enable NTFS long` paths in *group policy*

**Comment by andrew-allen-work** [comment]
I have this problem when trying to use GitVersion with teamcity. When using a build in teamcity with the  windows git client checking out repos with long filepaths enabled in git configs, works fine.  However, I cannot fix it for GitVersion or more specifically the referenced libgit2sharp libraries. I even built a 2016 svr to run a Teamcity agent on and set git config --system core.longpaths true as our teamcity build server runs on 2012 R2 Server. This library is used by gitversion and on windows it breaks ,this must be fixable happy to do it if someone can point me in the right direction. And I cannot reduce longpaths as it is a website with tons of node modules...

**Comment by MrLiu0635** [comment]
So sorry to mention this issue again. But I have to. I used libgit2sharp in my project. When users try to break 260 character limit, error throws.
When I use win10&vscode&git as develop envirenment, it can do work well. 
And my project is base on dotnet-core-2.0 ,  it can do well on 260 or more characters as creating folders/files.
My english is not good, and i hope i have made myself clear.

**Comment by noontz** [comment]
I'm wondering why this issue is closed.
On windows 10 with no longpath settings what so ever:
Cloning from gitbash / git for windows - no problem.
Cloning from VS - no problem
Cloning with libgit2sharp - big problem

**Comment by andrew-allen-work** [comment]
I would love to know also :-)

**Comment by ethomson** [comment]
> I'm wondering why this issue is closed.

It's not.

![Screen Shot 2020-05-19 at 14 57 30](https://user-images.githubusercontent.com/1130014/82335343-19eee780-99e1-11ea-8857-d149b51a5683.png)

**Comment by noontz** [comment]
@ethomson  UPPS....  Sorry...

**Comment by ethomson** [comment]
No problem!  Sorry this is such a thorny problem.  There's been some work started in libgit2 to address it.

**Comment by smoczas** [comment]
Is there any ETA for the fix to this issue?

**Comment by alinmircea** [comment]
worst attitude. "bla bla windows suchs", guess what git works just fine if "git config --system core.longpaths true"
What is the issue in libgit2sharp ?

**Comment by rupreck** [comment]
Nodegit (which also binds to libgit2) release v26.5 was released in March and included the merged PR #5347 supporting this although this is not yet merged to master in libgit2. See: https://github.com/nodegit/nodegit/pull/1748

Is this an option for libgit2sharp?

Lack of support for this is becoming increasingly a problem with various project package components (including node_modules) and testing frameworks with deep descriptive paths unable to be consumed.

**Comment by Solairw** [comment]
Try using with CloneOptions with flag `IsBare = true`. This solved the issue for me.

**Comment by dcworldwide** [comment]
Any update?

**Comment by bording** [comment]
As of LibGit2Sharp 0.27.0, it should be respecting the core.longpaths setting, so I'm going to close this issue as fixed.
