### ISSUE TITLE
How to Get remote Branches from SourceUrl of the Repo without Clone

### ISSUE THREAD

**Issue by panuganti** [libgit2/libgit2sharp#1377]
Using LibGit2Sharp, how can I fetch the list of all Remote Branches given the repo url ? 

I do not have a clone of the repo on the local disk. What's the simplest way to get the list of Branches and once I get the list of branches, I'd like to get the list of Commit Id's in a branch of my choice.

I do see a way to do all this if I have a Git Repo cloned on my local disk but, I don't want to clone it for obtaining this info.

**Comment by shiftkey** [comment]
I'm not sure of the way to do this with `libgit2sharp`, but here's how you do it with vanilla Git:

```sh
git init test && cd test
git remote add origin https://github.com/octokit/octokit.net.git
git ls-remote origin
```

I don't think `ls-remote` has made it into libgit2sharp yet. It looks like it's there in [libgit2](https://github.com/libgit2/libgit2/blob/master/examples/network/ls-remote.c#L37-L44) though.

**Comment by carlosmn** [comment]
Use `Remote.ListReferences()`. It currently requires a `Repository` instance to exist as a limitation of the underlying implementation, but it doesn't have to be any repository in particular. A newly-created repository would work just fine.

**Comment by shiftkey** [comment]
@carlosmn oh cool, I totally missed that - I thought it'd be an instance method off `Remote`:

Here's a sample that works with the latest release of libgit2sharp:

```csharp
static void Main(string[] args)
{
    const string localFolder = "C:/path/to/clone/somewhere/";
    const string remote = "https://github.com/octokit/octokit.net.git";

    var destination = Repository.Init(localFolder);
    var repo = new Repository(destination);
    var refs = repo.Network.ListReferences(remote).ToList();

    Debug.Assert(refs.Count > 0);

    Console.ReadLine();
}
```

**Comment by panuganti** [comment]
@carlosmn that's cool. I also want to get the list of commits for a remote branch. Can I do that without cloning the repo ?

**Comment by carlosmn** [comment]
That data is available in the repository. If you want do deal with Git data, you should clone the repository or, if your hosting provider supports it, ask the hosting service's API for information. But you will probably be happier working on the repository.

**Comment by panuganti** [comment]
@shiftkey @carlosmn ... I'm confused about the relation between a Reference and a Remote.. 
The list of references that I get this way have names not like origin/<branch_name> etc.. How can I get the list of remote branches which are of the form 'origin/<branch_name> ?

**Comment by shiftkey** [comment]
@panuganti `origin` is just an alias for a given remote URL, if you've setup your local repository to track these remotes using `git remote add origin [url]`.

Because we haven't done that for this scenario, Git is just enumerating the references that the remote repository has. Does that make sense?
