### ISSUE TITLE
Memory leak when manually building a commit history in a bare repo

### ISSUE THREAD

**Issue by Kennethtruyers** [libgit2/libgit2sharp#1378]
When you manually add a blob to the object database and then create a commit with that blob added to the current tree, there is a memory leak. 
It can be avoided by disposing the repo and initializing it between every commit. 

The leak is there at least since v0.13 (the earliest I tested), but has gotten a lot worse on v0.22. 

I've created a repro of this which commits the same blob 2000 times, each time adding a new entry to the current tree. These are the numbers I got:

```
0.13 - 0.21.0.176
Memory usage       Start       After 2000 commits
    With leak:     26.380KB    37.224KB
    Without leak:  30.984KB    30.840KB
	
0.22
    With leak:     26.616KB    226.736KB
    Without leak:  34.416KB    34.736KB
```

Where it says "Without leak" is where the Repository is disposed and reloaded between every commit. As you can see, up to v0.21, there's a small memory leak, from v0.22, the issue has gotten quite a bit bigger.

The project in the attachment reproduces this problem.

[Libgit2Sharp.MemoryLeak.zip](https://github.com/libgit2/libgit2sharp/files/544258/Libgit2Sharp.MemoryLeak.zip)

**Comment by ethomson** [comment]
Thanks for the report!  That doesn't sound like a memory leak, it sounds like caching.  If the memory is freed when you free the repository then that's probably the in-memory object cache.

Is this a problem for you and you want to save those 200kb?  The object cache settings are configurable in libgit2, but I don't believe we have any functionality to configure it in LibGit2Sharp ([the native settings are stubbed](https://github.com/libgit2/libgit2sharp/blob/3f9b415fa1edfc31ce1ec2b4b3d18441c34adfff/LibGit2Sharp/Core/Proxy.cs#L3356) but there are no setters for them).  If this is of interest to you, a pull request would be much appreciated!

Or are you reporting this because you believe it to be in error?  If that's the case, it doesn't _sound_ like a bug to me...

**Comment by bording** [comment]
@Kennethtruyers I spent some time taking a look at your repro, and all of the memory you are seeing being consumed is on the native heap, not the managed heap.

After profiling, it looks like the source of all the memory usage is from when LibGit2Sharp calls into libgit2's `git_object_lookup` function, which eventually calls `git_tree__parse`. Looking at the history of the [tree.c](https://github.com/libgit2/libgit2/commits/master/src/tree.c) file, there were some leaks that have been fixed.

The good news is that the .23 prerelease package on nuget already uses a version of libgit2 that has those changes! Here's what the memory usage looks like for your  repro with `0.23.0-pre20160922233542`:

```
With memory leak
Writing 0001/2000 items Memory Usage: 16,532.00KB
Writing 0501/2000 items Memory Usage: 22,608.00KB
Writing 1001/2000 items Memory Usage: 24,848.00KB
Writing 1501/2000 items Memory Usage: 26,928.00KB
Writing 2000/2000 items Memory Usage: 28,376.00KB
------------------------
Without memory leak
Writing 0001/2000 items Memory Usage: 21,924.00KB
Writing 0501/2000 items Memory Usage: 21,800.00KB
Writing 1001/2000 items Memory Usage: 21,728.00KB
Writing 1501/2000 items Memory Usage: 21,800.00KB
Writing 2000/2000 items Memory Usage: 21,808.00KB
------------------------
```

**Comment by Kennethtruyers** [comment]
@bording Thanks, that's great news!

Do you have any idea when a new stable release will be available?

Also, this does indeed solve the big memory leak on v0.22, but it still seems to be leaking a bit. Do you think this is just normal behavior or is there still something that isn't 100%? 

I realize it's probably something to take up with libgit2, just wanted to know if you have any ideas around this.

**Comment by bording** [comment]
> Do you have any idea when a new stable release will be available?

That would be a question for @ethomson to answer.

> Also, this does indeed solve the big memory leak on v0.22, but it still seems to be leaking a bit. Do you think this is just normal behavior or is there still something that isn't 100%?

From what I can tell, the increase in memory that is still being seen after upgrading to 0.23.0-pre20160922233542 appears to be from the object cache that @ethomson was talking about before, so I believe this is normal and expected.

**Comment by ethomson** [comment]
> Do you have any idea when a new stable release will be available?

Reasonably soon.  I think we're about ready to cut a libgit2 release, and this would follow after that.

Please do note that you can consider 0.23.0-pre20160922233542 to be a stable prerelease.  But we should have a proper release soon.  Thanks!

**Comment by Kennethtruyers** [comment]
OK, perfect! Thanks for the quick and thorough responses!
