### ISSUE TITLE
.NET core support

### ISSUE THREAD

**Issue by danpantry** [libgit2/libgit2sharp#1381]
Hi all,

Sorry if I am jumping the gun a bit here.

In my current workplace we had a requirement to utilise Git in .NET core. This was the first library I turned to, but I noticed that it did not support .NET core, "only" Mono (which is fine, but I'd prefer to have this running on .NET core as everything else does!). As a compromise, I wrapped git calls in `new Process`, which worked fine, but definitely is not as fast as it could be.

I was wondering what the progress was / if there were any plans to migrate to .NET core now that it is released? I created a fork and resolved most of the dependencies that were missing so that libgit2sharp _almost_ compiles with `netstandard1.3`, however unfortunately there are quite a few types missing - almost exclusively, all of these types deal with the native code, which is not surprising.

Related [branch](https://github.com/danpantry/libgit2sharp/tree/dotnetcore) on my fork and [list of missing types](https://github.com/danpantry/libgit2sharp/issues/1).

All of this native code is not something I have had exposure to in the past, so I'm not in the best place to resolve any of the build errors with them.

**Comment by ethomson** [comment]
Hi @danpantry !  This is being worked on over in #1318.  I regret that I'm not super up-to-date on the issues, but it seems like we rely on a handful of .NET components and it seems like they're not all...  um, fully baked yet...

**Comment by danpantry** [comment]
Oh, cool, I hadn't checked the PR section.
