### ISSUE TITLE
Can we diff between two commits without a local copy of the repo ? 

### ISSUE THREAD

**Issue by panuganti** [libgit2/libgit2sharp#1392]
I'm developing an application where I only have the remote url (i.e. github url) of the repo. I'm wondering if there is a way to get a diff between two commits without cloning and then generating the diff.

**Comment by ethomson** [comment]
No, you cannot.  This is a job for the GitHub API.  LibGit2Sharp works only against a (local) repository.

**Comment by suterma** [comment]
Not sure whether this is relevant, but at least now, the library also supports some form of in-memory repo. Still in local memory though.
