### ISSUE TITLE
Exception "Unable to load DLL 'git2-381caf5" while using LibGit2Sharp 0.23.0

### ISSUE THREAD

**Issue by laurentkempe** [libgit2/libgit2sharp#1399]
LibGit2Sharp 0.23.0 is marked as having dependency toward LibGit2Sharp.NativeBinaries (= 1.0.163)

While updating [Git Diff Margin](https://github.com/laurentkempe/GitDiffMargin) to LibGit2Sharp 0.23.0, I also updated LibGit2Sharp.NativeBinaries to 1.0.163 and use git2-75db289.dll

I now get the following exception "Unable to load DLL 'git2-381caf5'"

> 'devenv.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\USERS\LAURENT-SB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_187B054D\EXTENSIONS\M0VGXOLK.KLK\GitDiffMargin.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'devenv.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\USERS\LAURENT-SB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_187B054D\EXTENSIONS\M0VGXOLK.KLK\LibGit2Sharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'devenv.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\USERS\LAURENT-SB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_187B054D\EXTENSIONS\M0VGXOLK.KLK\Tvl.VisualStudio.Text.Utility.10.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'devenv.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\USERS\LAURENT-SB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_187B054D\EXTENSIONS\M0VGXOLK.KLK\Tvl.VisualStudio.Shell.Utility.10.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'devenv.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\USERS\LAURENT-SB\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_187B054D\EXTENSIONS\M0VGXOLK.KLK\GalaSoft.MvvmLight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'devenv.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\Microsoft\Web Tools\PasteJsonAsClasses\Microsoft.VisualStudio.Web.PasteJson.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'devenv.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\Microsoft.CodeAnalysis.CSharp.Features.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.TypeInitializationException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.</Message><StackTrace>   at LibGit2Sharp.Core.NativeMethods.RemoveHandle()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject.Finalize()</StackTrace><ExceptionString>System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---&amp;gt; System.DllNotFoundException: Unable to load DLL 'git2-381caf5': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.RemoveHandle()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject.Finalize()</ExceptionString><InnerException><ExceptionType>System.DllNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Unable to load DLL 'git2-381caf5': The specified module could not be found. (Exception from HRESULT: 0x8007007E)</Message><StackTrace>   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
   at LibGit2Sharp.Core.NativeMethods..cctor()</StackTrace><ExceptionString>System.DllNotFoundException: Unable to load DLL 'git2-381caf5': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.LibraryLifetimeObject..ctor()
   at LibGit2Sharp.Core.NativeMethods..cctor()</ExceptionString></InnerException></Exception></TraceRecord>

So it seems that LibGit2Sharp 0.23.0 has a dependency to 1.0.157 and not 1.0.163 as written on https://www.nuget.org/packages/LibGit2Sharp/

**Comment by carlosmn** [comment]
It does depend on the newer binaries, though we might have not updated the hard-coded hash prefix for the filename. I wonder how the tests passed if that's the case.

**Comment by laurentkempe** [comment]
Yes I have seen the dependency to the nugget, but missed the code with hard-coded hash prefix

**Comment by carlosmn** [comment]
It's not about the nuget package, the libgit2sharp code depends on the newer release of libgit2.

**Comment by laurentkempe** [comment]
ok is there any way I could go around it, or I need to wait a new version of libgit2sharp to fix it?

**Comment by bording** [comment]
I've just pulled down the LibGit2Sharp and LibGit2Sharp.NativeBinaries packages from nuget.org, and they are correct. The LibGit2Sharp.dll in the 0.23.0 package is correctly looking for `git2-75db289`.

@laurentkempe Can you make sure your project is referencing the correct assemblies? Maybe you have an old one leftover that needs to be cleaned up?

**Comment by laurentkempe** [comment]
@bording Here is the vsix file that I created and to me it looks fine, LibGit2Sharp.dll is with version 0.23.0 and there is also git2-75db289.dll in the vsix
[GitDiffMargin.zip](https://github.com/libgit2/libgit2sharp/files/690251/GitDiffMargin.zip)

**Comment by laurentkempe** [comment]
@bording hum I am quickly checking something it might be that I had still a pre of the 0.23 and I have just checked the version in the dll!

**Comment by laurentkempe** [comment]
Thanks @bording 👍 you were right! I had a pre-version still mixed the new git2! so my fault I should I have checked more carefully

**Comment by v-raras** [comment]
InnerException = {"Unable to load DLL 'git2-572e4d8': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

We are also getting the same exception. We are using Azure Function and using v0.26.0 of LibGit2Sharp. This exception arises when we are debugging our azure function using Azure CLI debugger.

We have already tried adding <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects> to csproj file of the project but still no luck. Though it runs fine in console app but is throwing exception in Azure function.

Here is the stack trace of the exception:
StackTrace = "   at LibGit2Sharp.Core.NativeMethods.git_repository_open(git_repository*& repository, FilePath path)\r\n   at LibGit2Sharp.Core.Proxy.git_repository_open(String path)\r\n   at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, Repositor...

**Comment by gvdm90** [comment]
Hi,
I'm having the same issue. I'm using the libgit2sharp NuGet package at version 0.26.0

**Comment by gvdm90** [comment]
I fixed the error. I'm using LibGit2Sharp in a .Net standard module of mine that is referenced by a .Net console application. The console application was not finding the LibGit2Sharp.NativeBinaries of the referenced module. I fixed this by adding the LibGit2Sharp.NativeBinaries NuGet reference also to the console application. Pay attention to the the LibGit2Sharp.NativeBinaries version that must equal the one brought by the referenced LibGit2Sharp.

**Comment by ArmandoA7x** [comment]
> InnerException = {"Unable to load DLL 'git2-572e4d8': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}
> 
> We are also getting the same exception. We are using Azure Function and using v0.26.0 of LibGit2Sharp. This exception arises when we are debugging our azure function using Azure CLI debugger.
> 
> We have already tried adding true to csproj file of the project but still no luck. Though it runs fine in console app but is throwing exception in Azure function.
> 
> Here is the stack trace of the exception:
> StackTrace = " at LibGit2Sharp.Core.NativeMethods.git_repository_open(git_repository*& repository, FilePath path)\r\n at LibGit2Sharp.Core.Proxy.git_repository_open(String path)\r\n at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, Repositor...

@v-raras we have the same issue, any solution?
thanks in advance.

Armando
