### ISSUE TITLE
Get remote repository name, owner and URL

### ISSUE THREAD

**Issue by rc201612** [libgit2/libgit2sharp#1400]
Hi, 

I am wanting to get the remote URL, owner's name and repository name from a local checkout, which I can do by cutting up the URL returned from the below. However, it seems convoluted.. Is there a neater way to get details of the remote repository? 

````c#
var repo = new LibGit2Sharp.Repository(localCheckoutDirectory);
var remoteURL = repo.Config.Get<string>("remote", "origin", "url").Value;
````

Thanks,

**Comment by Szmyk** [comment]
For remote UR; and name you could try with some LINQ:
```C#
var remoteURL = repo.Network.Remotes.First().Url;
var repoName = repo.Network.Remotes.First().Name;
```
I do not know way to have owner's name - I also have the same problem...

**Comment by Therzok** [comment]
You could check out the remote property on the checked out branch `Head.Remote`, then grab that Url.
