### ISSUE TITLE
Determine whether specific branch is locked or not

### ISSUE THREAD

**Issue by PeterV1** [libgit2/libgit2sharp#1405]
Hi,
I reviewed you dll, it look very impressive.
I have a question,
I need to determine whether specific branch is locked or not.
How ca I do it through your dll ?
What class-method I should call ?

Thanks a lot.

**Comment by ethomson** [comment]
I don't understand what you mean "locked"...?  Are you talking about a git concept, or are you talking about some Git hosting site's concept?

**Comment by PeterV1** [comment]
I mean locked through Bitbucket.

**Comment by ethomson** [comment]
This is not something that LibGit2Sharp can do - we only talk to git repositories (either locally, or remote repositories through the git protocols).

A locked branch is not something that is part of git itself.  This is an extension that BitBucket has created.  I'm afraid that you will need to look for a BitBucket specific API that can indicate that to you.

**Comment by PeterV1** [comment]
Is there some bitbucket c# wrapper ?
thanks.

**Comment by ethomson** [comment]
I'm sorry, I don't have any idea, I've never used BitBucket.  I would suggest [StackOverflow](http://stackoverflow.com/).
