### ISSUE TITLE
When is .net core compatible nuget package coming?

### ISSUE THREAD

**Issue by danwalmsley** [libgit2/libgit2sharp#1417]

**Comment by danwalmsley** [comment]
I saw there was a .net core test package, but I couldn't work out the correct version of native binaries for it to work.

 Will there be an official release soon?

**Comment by mxplusb** [comment]
Is .NET Core support coming at all?

**Comment by bording** [comment]
The 0.25.0 preview release on nuget.org already supports it:

https://www.nuget.org/packages/LibGit2Sharp/0.25.0-preview-0033

**Comment by ethomson** [comment]
Yep, this has shipped.  If you have problems with it, please open a separate issue.  Cheers!
