### ISSUE TITLE
RFC: Drop support for _building_ on Mono

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2sharp#1421]
In order to support a portable library (for CoreCLR support), we need to drop support for building on Mono.  (But not _using_ LibGit2Sharp on Mono.)

The details behind this are in #1318, but the summary is:

* Users want a portable library
* A portable library can be built on Visual Studio 2015 and Visual Studio 2017
* The `dotnet` tooling does not properly support Mono yet (https://github.com/dotnet/sdk/issues/335)

The proposal is that we move forward with the portable library.

This means that you can no longer develop LibGit2Sharp itself on mono.  You will have to use Visual Studio 2015 or Visual Studio 2017 to build LibGit2Sharp.

We _will_ still produce a library that will run on Mono.  Our CI system will still run on Mono, but it will no longer do a build; it will take the build produced on Windows and run the tests against it.  This will ensure that we still _run_ on Mono, but until the `dotnet` tooling catches up, we will not build there.

We hope that we can turn the dev/build scenarios on for Mono, but in the meantime, we will keep the _run_ scenario.

Comments?

**Comment by AArnott** [comment]
I suspect if we go this route, build on linux will be restored when we switch to dotnet CLI.
