### ISSUE TITLE
lib directory in project root after upgrading to VS 2017

### ISSUE THREAD

**Issue by clement911** [libgit2/libgit2sharp#1425]
I just upgraded to vs 2017 and I'm now seeing this directory in the root of my project:

![image](https://cloud.githubusercontent.com/assets/3426504/23692981/f8f2ef94-0425-11e7-83f3-9c1b291936fc.png)

If I try to remove it I get the following message: 
![image](https://cloud.githubusercontent.com/assets/3426504/23692993/0e61e646-0426-11e7-8d0d-95b238ba78d6.png)

**Comment by ethomson** [comment]
It looks like this is a function of the newest project system that includes all files in a folder by default.  I'm surprised that the backcompat story here isn't to do a version number check or something.

We still list our files explicitly, and we'll have to for future versions.

Do you know if there's a way to disable this new behavior in the project file?  Or is there an ignore pattern for the new project file format?

**Comment by bording** [comment]
@clement911 Looking at your screenshot, I'm assuming your project is an ASP.NET Core application running on the .NET Framework. Did you migrate from the xproj/project.json project system?

Can you post the contents of your new csproj file? When I created a new application from scratch and then added a reference to LibGit2Sharp, I'm not seeing the lib folder appear like that. I'm guessing that there is something in the migration process that isn't handling it correctly.

You also might try removing and re-adding LibGit2Sharp and see if that makes any difference.

**Comment by clement911** [comment]
Ok I'll give it a shot when I get a chance and will provide the csproj. Yes vs 2017 did the migration from xproj/project.json.
You are correct: asp.net core on top of full.net framework.

**Comment by clement911** [comment]
I didn't quite get to the bottom and I ended up not need libgit2sharp anymore, however I could see that those files were virtual files. There were not physically where they show up in the solution, instead there were point to my .nuget user folder directly...
I will close the ticket...

**Comment by jpreese** [comment]
@bording FWIW I'm having this exact same issue. I've tried uninstalling and reinstalling LibGit2Sharp. The csproj file can be found below. Note that the Removal of lib\ towards the bottom does not really seem to do much. Still investigating.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.1.1-beta" />
    <PackageReference Include="DotLiquid" Version="2.0.145" />
    <PackageReference Include="Humanizer" Version="2.2.0" />
    <PackageReference Include="LibGit2Sharp.Portable" Version="0.24.10" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="serilog" Version="2.4.0" />
    <PackageReference Include="serilog.sinks.literate" Version="2.1.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Output\Templates\*.liquid" />
  </ItemGroup>
  <ItemGroup>
	<Compile Remove="lib\**" />
	<EmbeddedResource Remove="lib\**" />
	<None Remove="lib\**" />
  </ItemGroup>
</Project>
```

**Comment by bording** [comment]
@jpreese Yes, with the new project system, you'll definitely be seeing those now, but we've got a change to how those files are being included that should be in the next preview release.

For now, it's expected that you'll see them.

**Comment by jpreese** [comment]
Thanks for the quick response, @bording ! I'll wait for the next release then.
