### ISSUE TITLE
Is it possible to compare an in memory file rather than a file path?

### ISSUE THREAD

**Issue by georgeduckett** [libgit2/libgit2sharp#1426]
Currently I'm using this to look at a Patch result:

    repo.Diff.Compare<Patch>(new[] { fullFilePath }).SingleOrDefault();

This is great when the changes are saved to disk, however I need this to work when the local changes are still in-memory.

Is this at all possible?

---

For some background I'm developing a [Visual Studio extension](https://github.com/georgeduckett/TeamCoding) to sync caret positions between users. To do this I'm looking at the diff result to adjust the reported caret position according to line additions and deletions locally. This works when the file is saved, but not when the changes are in the editor only. See [this issue](https://github.com/georgeduckett/TeamCoding/issues/9) for some detail.

**Comment by JacobPitts** [comment]
Hello George, I do not know if this is possible using GitLib2Sharp without saving the file to a temporary path (which could be outside the repo, for example under %temp%). On the other hand if you are writing a Visual Studio extension, there is an API you might try from TFS that also performs file comparisions (not using Git but results are similar): [LCSDiff](https://msdn.microsoft.com/en-us/library/dn451395(v=vs.120).aspx)

**Comment by georgeduckett** [comment]
@JacobPitts Thanks. Managed to get that working so my issue is resolved.

Unsure of Git etiquette now as the original query is unanswered, but my particular issue is fixed. Happy for someone to close this issue.
