### ISSUE TITLE
Question: How to get additions made by initial commit?

### ISSUE THREAD

**Issue by DmitriiKozhevnikov** [libgit2/libgit2sharp#1427]
Hello!

I would like to get all the changes (both additions and deletions) made by every non-merge commit.
Normally, it is as simple as that:
```c#
var diff = repository.Diff.Compare<Patch>(commit.Parents.Single().Tree, commit.Tree);
```
However, I got stuck on getting the changes of the initial commit. After quite some reading and searching, I have found that there should be some kind of an empty 'dummy' tree I can diff the initial commit against. I haven't been able to reproduce this solution with libgit2sharp, but I have a feeling I am simply missing something.
 
I would greatly appreciate, if someone could give me a hint on how this can be done!

Thanks in advance.

**Comment by JacobPitts** [comment]
Hey Dmitrii, I believe the following will diff the empty tree to a commit's tree:

`var diff = repository.Diff.Compare<Patch>(default(Tree), commit.Tree);`

You might try:

`var diff = repo.Diff.Compare<Patch>(commit.Parents.SingleOrDefault()?.Tree ?? default(Tree), commit.Tree);`

**Comment by DmitriiKozhevnikov** [comment]
Hey, Jacob! Thanks a lot, works like a charm!
