### ISSUE TITLE
Repository.Discover hangs on C:\\

### ISSUE THREAD

**Issue by KevinMehlhaff** [libgit2/libgit2sharp#1430]
When using Repository.Discover with C:\\, the call hangs.  This is a regression from previous version.
`var resolvedPath = Repository.Discover("C:\\");`

**Comment by ethomson** [comment]
Thanks for reporting this - I think that this is https://github.com/libgit2/libgit2/issues/4106 which was fixed in https://github.com/libgit2/libgit2/pull/4111.

The next time we pull in updated libgit2 binaries, we'll have a fix for this.  I'm hoping that we can do that soon.

**Comment by ethomson** [comment]
We have a new libgit2 now, so this should be fixed!
