### ISSUE TITLE
DllNotFound mac os, mono

### ISSUE THREAD

**Issue by retep007** [libgit2/libgit2sharp#1442]
runing clone results in System.DllNotFoundException git2-a5cf255

**Comment by ethomson** [comment]
I'm sorry to hear that.  Can you provide some more details?

What version of LibGit2Sharp?  Are you using the NuGet package or something you've built yourself?  What version of macOS?  What version of mono?  What architecture?  How are you deploying?  Is the `git2-a5cf255.dylib` getting deployed with your application?  If so, where?  If not, why not?

**Comment by retep007** [comment]
- LibGit2Sharp version 0.23.1 and 0.24.0 prerelease
- using nuget
- mac os v10.12.14
- mono 4.8.1 and 5.0.0 beta
using visual studio beta latest and xamarin latest
lib is getting deployed with apllication in lib/osx/libgit2-a5cf255.dylib

**Comment by bording** [comment]
Since you're using mono, did you make sure to include the `LibGit2Sharp.dll.config` file that gets copied to your output folder as well? That's required for mono to be able to find the native library properly.

**Comment by retep007** [comment]
actually i already checked thaht, here is the content
```
<configuration>
    <dllmap os="linux" cpu="x86-64" wordsize="64" dll="git2-a5cf255" target="lib/linux/x86_64/libgit2-a5cf255.so" />
    <dllmap os="osx" cpu="x86,x86-64" dll="git2-a5cf255" target="lib/osx/libgit2-a5cf255.dylib" />
</configuration>

```
I tried to change path in config to something else like 
```
target="libdwada/osx/libgit2-a5cf255.dylib"
```
but the error remained the same
`"InnerException":{"Message":"An error has occurred.","ExceptionMessage":"lib/osx/libgit2-a5cf255.dylib"`

**Comment by bording** [comment]
In that case, do you have any way for us to reproduce it? Is your code available online for me to take a look at?

**Comment by retep007** [comment]
Yes, repo is here `https://github.com/retep007/code-visualizer`
switch branch to `cloning-parsing`
request for debuging `http://127.0.0.1:8080/api/analyse/analyse?repoUrl=https://github.com/retep007/code-visualizer`
error occurs in `GitController:13`

**Comment by bording** [comment]
Ah, it's an ASP.NET application? You're probably running into a shadow copy problem then. Can you try disabling shadow copying with `<hostingEnvironment shadowCopyBinAssemblies="false" />` and see if that helps?

The shadow copying mechanism doesn't understand native dependencies, so it doesn't copy the lib folder to the correct location.

**Comment by retep007** [comment]
@bording Thanks, man you are a real hero.
