### ISSUE TITLE
https://github.com/libgit2/libgit2sharp/pull/1402/ was never merged onto master

### ISSUE THREAD

**Issue by dbaxa** [libgit2/libgit2sharp#1446]
https://github.com/libgit2/libgit2sharp/pull/1402 was never merged onto master and it should be.

**Comment by ethomson** [comment]
No, not should it be, it's in the 0.23 maintenance branch.  That's distinct from master which will become 0.24.

**Comment by dbaxa** [comment]
@ethomson okay. I didn't see where master had updated to have libgit `0.25.1`.

**Comment by ethomson** [comment]
I would like to try to get LibGit2Sharp following along with libgit2's release schedule, and then mirror the libgit2 release numbers for clarity.  I hope this will help ease some of the confusion - even I don't remember how these things correlate without digging in deeply.
