### ISSUE TITLE
Libgit2sharp won't work in Windows 7 Powershell

### ISSUE THREAD

**Issue by jez9999** [libgit2/libgit2sharp#1449]
When I try to include the Libgit2sharp bundled with Visual Studio 2015 into Windows 7 Powershell, I get:

> Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\LibGit2Sharp.dll' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded."

I'm assuming that this is because, at some point, you started targeting Libgit2sharp at a .NET version later than the Windows 7 Powershell supports.  Could you tell me what the last version of Libgit2sharp was that would work with the Windows 7 Powershell?  I can't assume that everyone using this script will have an upgraded version.  The version I can assume is:

```
PS> $PSVersionTable

Name                           Value
----                           -----
CLRVersion                     2.0.50727.5485
BuildVersion                   6.1.7601.17514
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1
```

**Comment by ethomson** [comment]
We don't support the version of libgit2 and LibGit2Sharp that was included in VS2015.  That version will not work outside of Visual Studio.

Please install the most recent version - either with nuget or by building it - and let us know if _that_ doesn't work.
