### ISSUE TITLE
Crash when using GlobalSettings.Version.ToString() in 0.23.1

### ISSUE THREAD

**Issue by mminns** [libgit2/libgit2sharp#1451]
In 0.23.1 the generated libgit2sharp_hash.txt file contains 'HEAD' rather than a commit hash.

If you call LibGit2.GlobalSettings.Version.ToString() this causes a crash as it tries to extract 7 characters from a 4 character string

see https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/Version.cs#L65 and https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/Version.cs#L72

**Comment by ethomson** [comment]
Thanks for reporting this and for the fix!
