### ISSUE TITLE
there will be a .Net standard compatibile version?

### ISSUE THREAD

**Issue by manuelelucchi** [libgit2/libgit2sharp#1453]
Now that .net standard 2.0 is very close with 20k new apis coming, there will be a Version of libgit2sharp that support it? If yes, when?

**Comment by bording** [comment]
@manuelelucchi It will be coming soon: https://github.com/libgit2/libgit2sharp/pull/1318

**Comment by manuelelucchi** [comment]
thanks for the answer! searching on the code i've seen a reference to the libgit2 c version. how could you port to .net standard if you have a c dependency?

**Comment by bording** [comment]
LibGit2Sharp is a managed wrapper around the native libgit2 library, so it's always had a native dependency. We include versions libgit2 compiled for different platforms via the LibGit2Sharp.NativeBinaries package, which has allowed LibGit2Sharp to be used on linux and macOS via mono.

With the changes I've got [here](https://github.com/libgit2/libgit2sharp.nativebinaries/pull/49) and [here](https://github.com/libgit2/libgit2sharp.nativebinaries/pull/51), we should be able to ship a version of libgit2 for every platform that .NET Core runs on.

**Comment by manuelelucchi** [comment]
thanks for the clarification! i hope i could use it for my UWP git application!

**Comment by bording** [comment]
UWP has a lot of restrictions around using native libraries, so I'm not sure if that's going to be able to work or not.

**Comment by manuelelucchi** [comment]
let's hope, at the worst i can also call non-UWP APIs

**Comment by ethomson** [comment]
#1318 has landed!  😁

**Comment by manuelelucchi** [comment]
Fantastic! Does it still uses directory and file classes? If not i could use it for xamarin and uwp. When will it be published to nuget?

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Edward Thomson<mailto:notifications@github.com>
Inviato: sabato 24 giugno 2017 17:07
A: libgit2/libgit2sharp<mailto:libgit2sharp@noreply.github.com>
Cc: Manuele Lucchi<mailto:manuelelucchi@live.com>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [libgit2/libgit2sharp] there will be a .Net standard compatibile version? (#1453)


#1318<https://github.com/libgit2/libgit2sharp/pull/1318> has landed! 😁

**Comment by ethomson** [comment]
I don't know if it will work in UWP or not, it still keeps the native component (libgit2).

I'll publish a prerelease package to nuget soon.  Looks like the nuget versioning needs some adjustment.

**Comment by manuelelucchi** [comment]
Ok, i will wait

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: Edward Thomson<mailto:notifications@github.com>
Inviato: sabato 24 giugno 2017 17:18
A: libgit2/libgit2sharp<mailto:libgit2sharp@noreply.github.com>
Cc: Manuele Lucchi<mailto:manuelelucchi@live.com>; Mention<mailto:mention@noreply.github.com>
Oggetto: Re: [libgit2/libgit2sharp] there will be a .Net standard compatibile version? (#1453)


I don't know if it will work in UWP or not, it still keeps the native component (libgit2).

I'll publish a prerelease package to nuget soon. Looks like the nuget versioning needs some adjustment.

**Comment by MikhailTymchukDX** [comment]
If I use libgit2sharp on Linux inside a .NET Core project, will it work?

**Comment by ethomson** [comment]
Hi @MikhailTymchukDX - it will _however_ there are issues with CentOS, which gives its SSL library a nonstandard name.  Debian and Ubuntu should be 👍 though.
