### ISSUE TITLE
Cherry-Pick not working - 'System.AccessViolationException' in LibGit2Sharp.dll

### ISSUE THREAD

**Issue by TheDrLamb** [libgit2/libgit2sharp#1455]
I am using a windows form application that I wrote to make an extremely simple "Git" GUI client, if it can even be called that. The issue that I am running into is that when you click a button with the commit name the program is supposed to cherry pick that commit into master branch ... however, this doesn't happen. The file with the changes is added into the correct directory but it does not get committed. The file remains unstaged and the error: 'System.AccessViolationException' in LibGit2Sharp.dll is thrown. A try catch block does nothing to stop the error as the error occurs in the Libgit2sharp library.

The code that I am using is attached here
'using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using LibGit2Sharp;

namespace CherryPickingTests
{
    public partial class Form1 : Form
    {
        string root = @"C:\Users\path\to\repo";
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            
        }
        private void DrawGraph() {

            int top = 10;
            int left = 10;

            List<Branch> branches = new List<Branch>();
            using (var repo = new Repository(root)) {
                foreach (Branch bran in repo.Branches) {
                    branches.Add(bran);
                }
                for (int j = 0; j < branches.Count; j++)
                {
                    Commands.Checkout(repo,branches[j]);
                    List<Commit> commits = new List<Commit>();
                    foreach (Commit com in repo.Commits.Take(10))
                    {
                        commits.Add(com);
                    }
                    for (int i = 0; i < commits.Count; i++)
                    {
                        Button button = new Button();
                        button.Left = left;
                        button.Top = top;
                        this.Controls.Add(button);
                        button.Text = commits[i].MessageShort;
                        ButtonEventArgs ev = new ButtonEventArgs(commits[i], branches[j]);
                        button.Click += (sender, e) => ButtonHandler(button, ev);
                        top += button.Height + 2;
                    }
                    left += 80;
                    top = 10;
                }
                Commands.Checkout(repo, "master");
            }
        }
        private void button1_Click(object sender, EventArgs e)
        {
            if (sender == button1)
            {
                DrawGraph();
            }
        }
        private void ButtonHandler(object sender, EventArgs e) {
            ButtonEventArgs ev = (ButtonEventArgs) e;
            using (var repo = new Repository(root)) {
                Signature sign = new Signature(new Identity("Automated", "--"), DateTime.Now);
                try
                {
                    MessageBox.Show(ev.commit.ToString());
                    CherryPickResult result  = repo.CherryPick(ev.commit, sign);
                }
                catch (Exception except) {
                }
                Commands.Stage(repo, "*");
                repo.Commit("Cherry Picked: " + ev.commit.MessageShort, sign, sign);
                DrawGraph();
            }
        }
    }
    public class ButtonEventArgs : EventArgs
    {
        public Commit commit { get; internal set; }
        public Branch branch { get; internal set; }
        public ButtonEventArgs(Commit _commit, Branch _branch)
        {
            this.branch = _branch;
            this.commit = _commit;
        }
    }
}'

Every step of the program works up until the Cherrypick command. I had attempted to clear up the unstaged and uncommitted file by placing a Stage all and Commit command following the Cherrypick. However, unsurprisingly this didn't work as the error is thrown prior. Any help or suggestions towards solving this will help immensely.

**Comment by TheDrLamb** [comment]
Through some investigation I think it is not an issue with Cherry pick itself. It seems that the commit that is being passed to through the event handler is not keeping the same Id. I am not sure if this is do to the Event argument structure I used, which is highly possible as I am new to event arguments, or if this in fact the commit Id changing between instances of repo.

**Comment by ethomson** [comment]
You've disposed the repository but you're passing a commit that was used by that repository (in the event arguments).  But that commit was disposed (along with the repository that owns it).

Either pass the ID and look it up again in your new repository instance or keep the repository instance alive.

**Comment by TheDrLamb** [comment]
Thank you very much for your quick response.

I tried switching the EventArgs around to only pass an ObjectId but it doesnt seem to like that either.
However I should be able to find a work around where I can keep the repository instance alive.

Thank you very much for your help.
