### ISSUE TITLE
My desktop build never works

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2sharp#1462]
I am now in a place where I simply cannot build.  Every build I perform in VS - even against `origin/master` with no changes - fails with:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4057	The target "GetBuildVersion" does not exist in the project.	LibGit2Sharp	C:\LibGit2\LibGit2Sharp\LibGit2Sharp\CodeGenerator.targets	78	

@AArnott what is going on here?  How can I debug this?

**Comment by ethomson** [comment]
I deleted my repository and re-cloned it.  No amount of quit vs -> `git clean -dfx` -> restart vs worked.

I have gotten into this situation before and `git clean`ing my repo did eventually unwedge me.  But what on earth does this error message actually mean and how can I act on it?

**Comment by AArnott** [comment]
Have you run a package restore on it?

**Comment by ethomson** [comment]
I did, with no effect.

**Comment by AArnott** [comment]
How did you do your package restore?
For me, I opened a VS 2017 developer prompt and ran `msbuild /t:restore`
After that, I opened the sln in VS and it built successfully. Granted, for some reason it took 2-3 minutes to build the first time, but it built.

**Comment by AArnott** [comment]
As for how to debug it if it's still failing for you... the `GetBuildVersion` target comes from the Nerdbank.GitVersioning nuget package. So if it can't be found, it would seem that package restore isn't adding the imports for your libgit2sharp.csproj project properly.

**Comment by AArnott** [comment]
I'm on VS 2017 15.3 Preview. After interacting with it for a few minutes on this solution, it tends to hang, spinning the CPU very hard. I suspect it has to do with the code generation we use. I'll look more into that.

**Comment by ethomson** [comment]
I'll try restoring the packages on the command line the next time I get into this state.  Generally I let VS restore the packages which usually works...  It would be a pity if that were the cause.

**Comment by deeja** [comment]
```
C:\Users\[My User Name]\.nuget\packages\codegeneration.roslyn.buildtime\0.4.11\build\CodeGeneration.Roslyn.BuildTime.targets(19,5): error MSB6006: "dotnet" exited with code -2147450749. [C:\projects\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
```
I get this when building using the script.

**Comment by ethomson** [comment]
Closing this; I haven't had problems in a long time.
