### ISSUE TITLE
Can't get LibGit2Sharp to build

### ISSUE THREAD

**Issue by sir-chester** [libgit2/libgit2sharp#1476]
I downloaded the zip file on windows 10 and ran the buildandtest.cmd, after which i tried to build the solution in VS 2017. I get back the error: "Error reading resource 'LibGit2Sharp.libgit2sharp_hash.txt' -- 'Could not find file '...\libgit2sharp-master\obj\LibGit2Sharp\Debug\net40\libgit2sharp_hash.txt'.'
Please help. Thank you.

**Comment by ethomson** [comment]
Thanks for the bug report.  I can confirm that building from the zip file that GitHub creates does not work.  We make some assumptions that you're building LibGit2Sharp within a Git repository.

We should unwind those assumptions and enable building from a zip file.

In the meantime, please clone the LibGit2Sharp repository and build from there.  Apologies for the inconvenience.

**Comment by sir-chester** [comment]
I have been able to confirm that cloning the repository fixes the issue.
Thank you!
