### ISSUE TITLE
Code Generation produces invalid signature

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2sharp#1480]
I'm trying to change `NativeMethods.git_rebase_commit`:

```
        [DllImport(libgit2)]
        internal static extern unsafe int git_rebase_commit(
            ref GitOid id,
            git_rebase* rebase,
            git_signature* author,
            git_signature* committer,
            [CustomMarshaler(typeof(StrictUtf8Marshaler), typeof(string))] byte* message_encoding,
            [CustomMarshaler(typeof(StrictUtf8Marshaler), typeof(string))] byte* message);
```

Which seems reasonable, but the code generator produces the following output:

```
        internal internal static unsafe int git_rebase_commit(ref GitOid id, git_rebase*rebase, git_signature*author, git_signature*committer, string message_encoding, string message)
        {
            ICustomMarshaler _StrictUtf8Marshaler = StrictUtf8Marshaler.GetInstance();
            IntPtr _message_encoding = _StrictUtf8Marshaler.MarshalManagedToNative(message_encoding);
            IntPtr _message = _StrictUtf8Marshaler.MarshalManagedToNative(message);
            try
            {
                int _result = git_rebase_commit(ref id, rebase, author, committer, (byte *)_message_encoding, (byte *)_message);
                return _result;
            }
            finally
            {
                _StrictUtf8Marshaler.CleanUpNativeData(_message_encoding);
                _StrictUtf8Marshaler.CleanUpNativeData(_message);
            }
        }
```

Notice the `internal internal`, which the compiler chokes on.

@AArnott do you have any insight here?

**Comment by ethomson** [comment]
See https://github.com/libgit2/libgit2sharp/tree/ethomson/rebase_commit_strings for a branch where this occurs.

**Comment by ethomson** [comment]
Also, looking at this generated code, the `MarshalManagedToNative` should be within the `try` block, since it can throw.  (The example given in the docs for `UTF8Encoding` is `"abc\uD801\uD802d"`).

If the second of these threw, it would leak the first native string that was allocated.

I poked around at the code generation but it's quite over my head.  If you could provide some guidance here, too, that would be nice.

Thanks!

**Comment by AArnott** [comment]
Sure. I'll work toward a fix by tomorrow.

**Comment by AArnott** [comment]
@ethomson Can I ask why you defined your method to be `internal`? Generally when there are generated interop methods the one you define should be `private` to encourage use of the friendlier generated method.

**Comment by AArnott** [comment]
If you mark your method `private`, then fix the compiler errors in Proxy.cs since it must call the friendly generated overload, it works.
I'll fix the memory leak problem though.

**Comment by ethomson** [comment]
I didn't define it `internal`.  It's `internal` right now.  As are most (all?) of the methods in `NativeMethods`?

I only changed the `IntPtr`s to `string`s, which seems like a reasonable change and I wouldn't expect such an error.

**Comment by ethomson** [comment]
Well, now that I'm in front of my computer, changing it from `internal` to `private` does indeed fix the problem, but it's not even a little bit clear to me how I was supposed to figure this out.

**Comment by AArnott** [comment]
The rule is this: if you use custom marshalers, the method should be private. If you look at the `NativeMethods` class, all the `internal` methods do *not* use custom marshalers. So if you add a marshaler to a method for the first time, you must also mark it private.

I'm working to change the codegen to fix the potential memory leak. I'll fix the bad code emit and also emit an error that teaches the user this rule.

**Comment by ethomson** [comment]
Where did you document this rule?

**Comment by ethomson** [comment]
Sorry - I'm quite cross with this code generation because it's quite dense and quite difficult to debug.  If you add an error here that would be very helpful.

**Comment by AArnott** [comment]
> Where did you document this rule?

I don't know that I did. It's just the pattern in the file. I had to study it for a few minutes myself today before I convinced myself that the rule existed as I'd forgotten it, myself. 

> I'm quite cross with this code generation because it's quite dense and quite difficult to debug.

Quite so. It's the most opaque thing in the whole repo, probably. I've gotten used to it since I have such code in several repos now (for all different reasons).

**Comment by ethomson** [comment]
> I don't know that I did. It's just the pattern in the file. I had to study it for a few minutes myself today before I convinced myself that the rule existed as I'd forgotten it, myself.

That's fair.  Again, I appreciate all your work here, and I apologize for venting a bit.  <3

**Comment by AArnott** [comment]
The code generator memory leak is fixed. PR coming soon.

If you use anything other than `private` visibility for an interop method with marshaled parameters, you'll now see an error in the build like this:
> Core\NativeMethods.cs(210,9): error CODEGEN001: The method NativeMethods.git_rebase_commit uses custom marshalers, so it should be private. The build-generated wrapper method will be internal. [C:\git\libgit2sharp\libgit2sharp\LibGit2Sharp.csproj]

**Comment by Zoxive** [comment]
Just a note, i ran into this exact problem while updating my branch. After much trial and error I figured out I had to swap my `internal `to `private`. (Noted semi frustration here #1479)
