### ISSUE TITLE
Cloning any repository results in "remote 'origin' already exists"

### ISSUE THREAD

**Issue by tylercamp** [libgit2/libgit2sharp#1487]
I'm using latest LibGit2Sharp (0.24.0) and NativeBinaries (1.0.185) off NuGet.

Whenever I try to invoke Repository.Clone(..) I always get the error "remote 'origin' already exists".

The clone example off the Wiki also shows the error. (https://github.com/libgit2/libgit2sharp/wiki/git-clone)

I can reproduce this by making a new project, adding the LibGit2Sharp NuGet package, and copy/pasting the code from the wiki example.

**Comment by tylercamp** [comment]
Possibly related - When I create a new Repository object (`new Repository()`) it already has an `origin` defined pointing to another repo that I had been using, even though I had not yet assigned anything to the Repository object or done any operations.

**Comment by ethomson** [comment]
I don't think that LibGit2Sharp is going to know about that other repository on its own.  I suspect you have that remote in your global config.  What does Git itself do in a new repository?  What does `git config --list` do in that repository?

**Comment by tylercamp** [comment]
You're right, an origin was configured globally.. I have no clue how that got there.

Thank you for your quick support!

**Comment by ethomson** [comment]
Glad it was an easy solution!
