### ISSUE TITLE
Attempted to read or write protected memory. 

### ISSUE THREAD

**Issue by exuviae** [libgit2/libgit2sharp#1489]
I get this every time I try to work with a repository.  

   at LibGit2Sharp.Core.NativeMethods.git_revwalk_new(git_revwalk*& walker, git_repository* repo)
   at LibGit2Sharp.Core.Proxy.git_revwalk_new(RepositoryHandle repo)
   at LibGit2Sharp.CommitLog.CommitEnumerator..ctor(Repository repo, CommitFilter filter)
   at LibGit2Sharp.CommitLog.GetEnumerator()
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

The code is:

public static ICommitLog GetAllCommitsBetweenBranches()
        {
            using (var repo = new Repository(@"C:\Users\myrepo"))
            {
                var filter = new CommitFilter
                {
                    ExcludeReachableFrom = repo.Branches["refs/remotes/origin/Release-1.03"],
                    IncludeReachableFrom = repo.Branches["refs/remotes/origin/master"]
                };
                return repo.Commits.QueryBy(filter);
            }
        }

        private static void Main(string[] args)
        {
            var stuff = GetAllCommitsBetweenBranches();
            foreach (var commit in stuff)
            {
                Console.WriteLine(commit.Message);
            }
        }

**Comment by ethomson** [comment]
It looks like you're trying to use LibGit2Sharp after you've disposed the `Repository`.  I presume that if you query the `commit.Message`s in that loop _before_ disposing the `Repository` that this works?

**Comment by exuviae** [comment]
yes, that was it thank you.

**Comment by ethomson** [comment]
You bet, glad it's working.
