### ISSUE TITLE
How to pull latest from a specific remote branch without having to need to provide credentials?

### ISSUE THREAD

**Issue by nawfalhasan** [libgit2/libgit2sharp#1495]
### Requirement: 

I want to pull (fetch + merge) latest from a **specific git remote branch** to my **currently checked out local branch**, without having to pass any other argument, like user credentials etc. Basically I am trying to replicate `git pull origin my-remote-branch`

### Details:

I want to automate certain Git operations from C#. I can simply do what I want by invoking `git.exe` (if I know the path), like `git.exe --git-dir=my-repo-directory pull origin my-remote-branch`. Notice that here the only external parameters I have to supply are `my-repo-directory` and `my-remote-branch`. Git gets everything right, like the name, password, email, current working branch (even if it doesnt have remote attached) and git pull simply works. I dont have to pass any of those parameters manually. I assume Git gets them from current Git settings for the repo (from %HOME% folder?).

Is there a way to simulate that in LibGit2Sharp?

### What I tried: 

            using (var repo = new Repository("my-repo-directory"))
            {
                var trackingBranch = repo.Branches["remotes/origin/my-remote-branch"];
                PullOptions pullOptions = new PullOptions()
                {
                    MergeOptions = new MergeOptions()
                    {
                        FastForwardStrategy = FastForwardStrategy.Default
                    }
                };

                MergeResult mergeResult = Commands.Pull(
                    repo,
                    new Signature("my name", "my email", DateTimeOffset.Now), // I dont want to provide these
                    pullOptions
                );
            }

Which fails since it says there is no tracking branch. I dont necessarily need a tracking remote branch. I just want to fetch latest from a specific random remote repo and perform automerge if possible.

Just to see if it works I tried: 

            using (var repo = new Repository("my-repo-directory"))
            {
                var trackingBranch = repo.Branches["remotes/origin/my-remote-branch"];

                if (trackingBranch.IsRemote) // even though I dont want to set tracking branch like this
                {
                    var branch = repo.Head;
                    repo.Branches.Update(branch, b => b.TrackedBranch = trackingBranch.CanonicalName);
                }

                PullOptions pullOptions = new PullOptions()
                {
                    MergeOptions = new MergeOptions()
                    {
                        FastForwardStrategy = FastForwardStrategy.Default
                    }
                };

                MergeResult mergeResult = Commands.Pull(
                    repo,
                    new Signature("my name", "my email", DateTimeOffset.Now),
                    pullOptions
                );
            }

This fails with

> request failed with status code: 401

### Additional info: 

I dont want to invoke git.exe directly because I cant hardcode the git exe path. It will be different in every user's machine. Or otherwise,  If not, is there a way to programmatically get git.exe path via libgit2sharp? Our users may not have git added in _path_ env variable. Also, since I cant pass username, email etc at runtime, is there a way libgit2sharp get them by itself from the repository settings, like how git.exe does?

**Comment by ethomson** [comment]
Yes, LibGit2Sharp supports the equivalent of a `git pull`.  As you may know, a "pull" is a fetch combined with a merge.  You can see examples of fetches in our [fetch tests](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp.Tests/FetchFixture.cs) and examples of a merge in our [merge tests](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp.Tests/MergeFixture.cs).

LibGit2Sharp operates directly on git repositories, it does not invoke `git` and will not help you locate the `git` executable.  It has no concept of what it is.

I'm closing this issue - our issue tracker is for recording bugs and tracking feature progress.  For help using LibGit2Sharp, please open an issue on [StackOverflow](https://stackoverflow.com/questions/tagged/libgit2sharp), where we can assist.

**Comment by nawfalhasan** [comment]
@ethomson I have posted question on [SO](https://stackoverflow.com/questions/46833568/how-to-pull-latest-from-a-specific-remote-branch-without-having-need-to-provide). Those pull and fetch examples from tests classes didnt help. I have provided the error messages in those cases.
