### ISSUE TITLE
.NET Standard 2.0

### ISSUE THREAD

**Issue by Zoroknash** [libgit2/libgit2sharp#1507]
(When) can you guys get a pre-release on NuGet for .NET standard 2.0? 

We're eager to test it!

**Comment by bording** [comment]
@Zoroknash The current 0.25.0-preview-0033 release on nuget.org includes support for `netstandard1.3`, so it will already work with anything that supports `netstandard2.0`. Is there a reason you're looking specifically for a `netstandard2.0` assembly?

Its looking like the next preview will be `netstandard2.0` only, but I'm not exactly sure when that will be released.

**Comment by Zoroknash** [comment]
Hey @bording, thanks for your reply!

I was not aware of the fact that the current release includes the netstandard1.3 support, I just quickly checked the active branches you were working on. I'll try to download the abovementioned preview! :)
