### ISSUE TITLE
DLL is not found on Debian

### ISSUE THREAD

**Issue by bo20202** [libgit2/libgit2sharp#1532]
So, I've installed latest preview version (0.25.0-preview-0073) and when I try to use this library on Linux (Debian 9.2)  I get this exception. 

System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module or one of its dependencies could not be found.

 On Windows it works fine.

Maybe I miss some deps?

Just checked, lib and runtimes directories are in place.

**Comment by bording** [comment]
@bo20202 See the discussion in #1484. At the moment, the version of the linux binary we ship has a dependency on libssl.so.1.0.0, and Debian 9 does not include that. If 1.0.0 can be installed on Debian 9, it should work.

There are plans to include binaries that will work with more distros out of the box, but there are some .NET Core issues I'm waiting to be resolved before I can make it happen.

**Comment by bo20202** [comment]
@bording Thanks! Installing libssl.so.1.0.0 did the trick.
