### ISSUE TITLE
Repository.Clone is marking files as owned by Administrator and Read Only...

### ISSUE THREAD

**Issue by verxion** [libgit2/libgit2sharp#1535]
Repository.Clone(“https://github.company.com/org/repo”,@“C:\some\path\to\repo”, co);

This clones the repo, which is great, but the resultant files are marked as owned by Administrator and are Read Only, so I have no way to delete or modify them after the clone is done.  How do I resolve this?

**Comment by ethomson** [comment]
Are you intentionally running your application as Administrator?

**Comment by verxion** [comment]
I confirmed that task manager shows Visual Studio is in fact running as a non administrative user, so that isn’t the issue...

**Comment by ethomson** [comment]
_Something_ is elevating your application - I'm not super familiar with elevation...  I think asking on [StackOverflow](https://stackoverflow.com/questions/tagged/libgit2sharp) might get some more 👀 on this.

**Comment by verxion** [comment]
Ok, I’ve posted it here for reference: https://stackoverflow.com/questions/48914940/libgit2sharp-repository-clone-is-marking-files-as-owned-by-administrator-and-rea

**Comment by ethomson** [comment]
Thanks for that; it looks like upon further investigation, VS is indeed running as Administrator.  I'm afraid I don't know why that would be happening, but this seems like it's not a problem with LibGit2Sharp, so I'm closing this.  Thanks!
