### ISSUE TITLE
"unknown certificate check failure" when pulling changes from GitHub

### ISSUE THREAD

**Issue by splatteredbits** [libgit2/libgit2sharp#1547]
When I use LibGit2Sharp 0.24.0 to pull changes into my local repository from GitHub, I get an exception:

```
LibGit2Sharp.LibGit2SharpException: unknown certificate check failure
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_fetch(RemoteHandle remote, IEnumerable`1 refSpecs, GitFetchOptions 
fetchOptions, String logMessage)
   at LibGit2Sharp.Commands.Fetch(Repository repository, String remote, IEnumerable`1 refspecs, FetchOptions 
options, String logMessage)
   at LibGit2Sharp.Commands.Pull(Repository repository, Signature merger, PullOptions options)
   at CallSite.Target(Closure , CallSite , Object , Object , Object )
```

What do I need to do to get LibGit2Sharp to pull my changes in? I can get to https://github.com without any errors.

Here's the PowerShell code I'm using to pull:

```
$repo = New-Object 'LibGit2Sharp.Repository' ((Get-Location).ProviderPath)
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$pullOptions = New-Object LibGit2Sharp.PullOptions
$mergeOptions = New-Object LibGit2Sharp.MergeOptions
$mergeOptions.FastForwardStrategy = [LibGit2Sharp.FastForwardStrategy]::FastForwardOnly
$pullOptions.MergeOptions = $mergeOptions
$signature = $repo.Config.BuildSignature((Get-Date))
$repo.Network.Pull($signature, $pullOptions)
```

**Comment by ethomson** [comment]
Windows 7, I assume?

This, like all problems, is because GitHub has deprecated prior versions of TLS without really telling anybody!  Ideally, please upgrade to one of the 0.25 prereleases.  (They’re much better.)

You can also enable TLS 1.2 by following the instructions at https://support.microsoft.com/en-gb/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in - you should not need to update LibGit2Sharp a time all

0.24.2 will be out shortly which will also fix this.  (But the 0.25 prereleases are far superior.)

**Comment by splatteredbits** [comment]
I had that patch already installed. I needed to download and run the "Easy fix" installer to enable the patch. Now I can clone.

Out of curiosity, what did you change in your code to fix the problem?

I'm scared to upgrade to 0.25 because 1) it's a prerelease and 2) when I went from 0.22 to 0.24, it broke a lot of backwards compatibility which I only discovered through trial and error. I'd like to see release notes for each release so I can plan/test accordingly when I upgrade.

**Comment by ethomson** [comment]
Sorry about that.  We’ve gotten better about not breaking API changes.  We’ve _especially_ gotten better between minor releases.  We provide deprecation warnings for at least a release - so if you’re on 0.24 we should not break you moving to 0.25 but will instead just give you warnings if we changed public API in a breaking way.

I don’t think we did but it’s possible that the move to .NET core was uglier than I remember.

Anyway.  We set the TLS 1.2 bit in libgit2 itself now, that’s the fix going forward for the projects independent of your default settings and should work on Vista and better.

**Comment by ethomson** [comment]
The libgit2 fix is https://github.com/libgit2/libgit2/pull/4550

**Comment by splatteredbits** [comment]
Unfortunately, I use LibGit2Sharp in PowerShell, which gives no messages about obsolete members. :( I totally support deprecating and then removing things (I maintain several open-source projects myself) so release notes would really help.

**Comment by ethomson** [comment]
Very reasonable.  Thanks for the reminder.
