### ISSUE TITLE
Install the package reference problem.

### ISSUE THREAD

**Issue by 386845154a** [libgit2/libgit2sharp#1557]
vs 2017 
You are trying to install this package into a project with the target ".netframework,Version=v4.5.2 ", but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by bording** [comment]
@386845154a Version 0.25.0 only ships a .NET Standard 2.0 assembly, so that means the minimum supported version of the .NET Framework is 4.6.1. You'll need to update to that version of the framework if you want to use the latest version of LibGit2Sharp.

**Comment by ethomson** [comment]
Hi @386845154a - what @bording said is correct.  You can continue with the v0.24.0 release, which was the last release before our upgrade to .NET Core support.
