### ISSUE TITLE
git log -15 is slow

### ISSUE THREAD

**Issue by battlmonstr** [libgit2/libgit2sharp#1558]
## Environment:
libgit2sharp version: 0.24.1 from NuGet
.NET version: 4.5
OS: Windows 7, 32 bit.
CPU: Intel Core i7 @ 1.8 GHz.
storage: local SSD

## Test case:
1. Clone a large Git repo. (I try with https://github.com/python/cpython ).
1. Run [git log example](https://github.com/libgit2/libgit2sharp/wiki/git-log) on this repo.

## Expected results:
Should be almost instant, because of "Take(15)" is limiting to just 15 commits.
The time should be similar to running `git log -15 | cat` from command line, which is almost instant to me.

## Actual results:
It takes about 1.5-2 seconds to start iterating over the commits.

## Notes:
The iteration time doesn't change significantly if you change to Take(10000) or Take(3).
It seems that it reads the entire history (or a huge chunk of it) into memory before the iteration starts.

If have changed the test sample to sleep after every 1000 items. It has shown that there's almost no significant delay for reading over the first 10K after it gets to the first item.

The task manager shows that my process takes about 6 Mb before the loop starts, and about 80 Mb on the first line of the loop (Console.WriteLine) right after it starts, which also indicates that.

Also this is a screenshot of the .NET profiler that shows that the most of the time is spent inside `NativeMethods.git_revwalk_next`, which I don't know how to profile inside (is it a C function?).

![capture](https://user-images.githubusercontent.com/11477595/38094184-68c7b72e-336d-11e8-8f93-6c9bca562c85.PNG)

_Question:_ Is there a workaround? I would like to get a few commits really fast by something like `Commits.Skip(N).Take(50)`. Is there an alternative API that can be used for this use case? Is there a setting somewhere that tweaks how much of the history does it load/preload internally?

**Comment by ethomson** [comment]
It is a C function, yes.  (That's libgit2 itself.)  And yes, that probably _does_ need to walk the entirety of history in order to sort it properly.  It's not clear to me immediately whether this is a LibGit2Sharp issue, a libgit2 issue, or simply a function of the size of your repository.  How long does `git log --graph` take?

**Comment by battlmonstr** [comment]
A minimal code test example:
```C#
using System;
using System.Linq;
using LibGit2Sharp;
using System.Diagnostics;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var stopwatch = Stopwatch.StartNew();
            using (var repo = new Repository(@"c:\Users\Daniel\Projects\cpython"))
            {
                foreach (Commit c in repo.Commits.Take(1))
                {
                    Console.WriteLine("Time to start getting the log: {0}", stopwatch.Elapsed);
                    break;
                }
            }
        }
    }
}
```

Outputs:

    Time to start getting the log: 00:00:01.6240654

**Comment by battlmonstr** [comment]
`git log --graph` takes a about that time - 1.4 sec:

```
Daniel@Daniel-PC MINGW32 ~/Projects/cpython (master)
$ time git log --graph | head
* commit b9e7fe38a07a16942cb65cb922c234c95e2823a0
| Author: Ned Deily <nad@python.org>
| Date:   Thu Mar 29 08:47:27 2018 -0400
|
|     bpo-32726: macOS 10.6+ installer now builds Tcl/TK 8.6 (GH-6307)
|
|     Build and link with private copy of Tcl/Tk 8.6 for the macOS 10.6+
|     installer. The 10.9+ installer variant already does this.  This means that
|     the Python 3.7 provided by the python.org macOS installers no longer need or
|     use any external versions of Tcl/Tk, either system-provided or user-

real    0m1.408s
user    0m0.000s
sys     0m0.046s
```

Is there a way to disable "--graph" somehow in libgit2sharp or libgit2?

**Comment by ethomson** [comment]
You may have luck with (`CommitSortStrategies`)[https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/CommitSortStrategies.cs)

**Comment by battlmonstr** [comment]
Don't see an easy way to test this. CommitLog constructors are "internal" and the class is "sealed", so can't pass or redefine "SortBy". Maybe I'll try reflection. The hardcoded strategy is CommitSortStrategies.Time.

**Comment by battlmonstr** [comment]
Changing a sort strategy doesn't make any significant difference.

Here's my test code:
```C#
using System;
using System.Linq;
using LibGit2Sharp;
using System.Diagnostics;
using System.Reflection;

namespace ConsoleApp1
{
    class Program
    {
        static T CreateInstance<T>(params object[] args)
        {
            var type = typeof(T);
            var instance = type.Assembly.CreateInstance(
                type.FullName, false,
                BindingFlags.Instance | BindingFlags.NonPublic,
                null, args, null, null);
            return (T)instance;
        }

        static void Main(string[] args)
        {
            Test(CommitSortStrategies.None);
            Test(CommitSortStrategies.Reverse);
            Test(CommitSortStrategies.Time);
            Test(CommitSortStrategies.Topological);
        }

        static void Test(CommitSortStrategies sortStrategy)
        { 
            var stopwatch = Stopwatch.StartNew();
            using (var repo = new Repository(@"c:\Users\Daniel\Projects\cpython"))
            {
                var filter = new CommitFilter();
                filter.SortBy = sortStrategy;
                var log = CreateInstance<CommitLog>(repo, filter);
                foreach (Commit c in log)
                {
                    Console.WriteLine("Time to start getting the log: {0}", stopwatch.Elapsed);
                    break;
                }
            }
        }
    }
}
```

**Comment by battlmonstr** [comment]
Related issue: https://github.com/libgit2/libgit2/issues/4428

**Comment by battlmonstr** [comment]
Trying an older version of libgit2sharp, it used to work fast indeed:

```
Time to start getting the log: 00:00:00.0575839  - None
Time to start getting the log: 00:00:03.4696467  - Reverse
Time to start getting the log: 00:00:00.0067906  - Time
Time to start getting the log: 00:00:03.4959112  - Topological
```

Actually it seems that "Reverse" and "Topological" modes became quite faster (2x), but "Time" is much much slower.

Still trying to find the first broken version.

**Comment by battlmonstr** [comment]
This is a regression in 0.23 between

libgit2sharp 0.23 + LibGit2Sharp.NativeBinaries.1.0.163
libgit2sharp 0.22 + LibGit2Sharp.NativeBinaries.1.0.129

0.22 WFM.

**Comment by carlosmn** [comment]
This is probably due to what libgit2/libgit2#4606 is fixing

**Comment by nebosite** [comment]
I have a really big repository (many GB) and repository.Commits.Take(100) takes around **200 seconds** to run.   Compare to git log -n 100 which takes about 1 second.     The culprit is this line in libgit2sharp:

            int res = NativeMethods.git_revwalk_next(out ret, walker);

**Comment by battlmonstr** [comment]
Hello. Just reading up and trying to catch up with the progress done on this issue in libgit2 + libgit2sharp.

The good news is that some related fixes were merged and included in libgit2sharp v0.26.0 (based on libgit2 v0.28.0):
https://github.com/libgit2/libgit2/pull/4606
https://github.com/libgit2/libgit2/pull/4809
and it improved performance of the commit log with CommitSortStrategies.None option. Good stuff! :+1:

On the opposite side, the CommitSortStrategies.Time option became about 30% slower. Testing on the same repo:
libgit2sharp v0.26.0 - 1.7-1.8 sec
libgit2sharp v0.23.0 - 1.3 sec

Thinking more about this, I would actually like default `.Time` option to be fast too.
From some of the comments I have understood that when you need sorting you are reading the whole history to memory first,
and so it gets slow on big repositories. Is it correct?
With that said, and knowing that libgit2sharp v0.22.1 was working instantly with `.Time` sorting,
does it mean that v0.22.1 was doing the sorting wrong and therefore it was fast,
or does it mean that it was actually more optimized back then?
Could you clarify that @carlosmn @ethomson ?

Here's the updated test case code:

	using System;
	using LibGit2Sharp;
	using System.Diagnostics;

	namespace ConsoleApp1
	{
	    class Program
	    {
	        static void Main(string[] args)
	        {
	            Test(CommitSortStrategies.None);
	            Test(CommitSortStrategies.Reverse);
	            Test(CommitSortStrategies.Time);
	            Test(CommitSortStrategies.Topological);
	        }

	        static void Test(CommitSortStrategies sortStrategy)
	        {
	            var stopwatch = Stopwatch.StartNew();
	            using (var repo = new Repository(@"c:\Users\Daniel\Projects\nitrogit\test\cpython"))
	            {
	                var filter = new CommitFilter();
	                filter.SortBy = sortStrategy;
	                foreach (Commit c in repo.Commits.QueryBy(filter))
	                {
	                    Console.WriteLine("Time to start getting the log with sortStrategy = {0}: {1}", sortStrategy, stopwatch.Elapsed);
	                    break;
	                }
	            }
	        }
	    }
	}

P.S. While looking at this, this issue popped up, not sure if it is related though: https://github.com/libgit2/libgit2/issues/4736

**Comment by battlmonstr** [comment]
Thanks for help to figure this out. The `.None` case works with v0.26.0 and I have a decent workaround for `.Time`, which is to use .None, Take(15 + 100), and Sort by commit date.

**Comment by ethomson** [comment]
> Thanks for help to figure this out. The `.None` case works with v0.26.0 and I have a decent workaround for `.Time`, which is to use .None, Take(15 + 100), and Sort by commit date.

This is a clever solution; I'd be interested to hear how it works out for you.  Please do let us know if you run into problems or if this remains effective.
