### ISSUE TITLE
Cloning halts when the local directory does not exist

### ISSUE THREAD

**Issue by alaashafaee** [libgit2/libgit2sharp#1560]
Cloning works well for me when the local directory exists, i.e. localPathToRepo in Repository.Clone(repoUrl, localPathToRepo, co). It halts when it does not exist instead of throwing an exception (or creating it).

**Comment by ethomson** [comment]
I'm not sure that I understand what you mean exactly when you say "halts".  Crashes?  Returns successfully but does not do anything?

**Comment by ethomson** [comment]
Hi!  I hope that you've sorted your issues out - if you have further questions please do feel free to ask!
