### ISSUE TITLE
401 error on push to Gogs Git with public repository

### ISSUE THREAD

**Issue by SoftwareArchitec** [libgit2/libgit2sharp#1561]
Hello,

a Push to a remote will throw exception if repository is public. Same code will work if repository is private. The second call will also throw 401 error. Push with commandline or Sourcetree is possible. How will push work with ligbit2sharp with public repositories?

Exception: 
{Name = "LibGit2SharpException" FullName = "LibGit2Sharp.LibGit2SharpException"}
message="request failed with status code: 401"
innerException=null
HResult=-2146233088

Stack:
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_remote_push(RemoteHandle remote, IEnumerable`1 refSpecs, GitPushOptions opts)
   at LibGit2Sharp.Network.Push(Remote remote, IEnumerable`1 pushRefSpecs, PushOptions pushOptions)
   at LibGit2Sharp.Network.Push(Remote remote, IEnumerable`1 pushRefSpecs)
   at LibGit2Sharp.Network.Push(Remote remote, String pushRefSpec)
....

Version:
0.24.0.0 with Visual Studio 2015

1)
```
            CredentialsHandler newt = 
new CredentialsHandler((url, fromUrl, types) => 
new UsernamePasswordCredentials { Username = userName, Password = userPass });

            var options = new PushOptions();
            options.CredentialsProvider = newt;
            options.OnPackBuilderProgress = packBuilderProgressHandler;
            options.OnPushTransferProgress = pushTransferProgressHandler;
            options.OnPushStatusError = pushStatusErrorHandler;

            repo.Network.Push(
                repo.Network.Remotes["origin"], 
                @"refs/heads/master:refs/heads/master", 
                options);
```
2)
`repo.Network.Push(remote, pushRefSpec);`

**Comment by ethomson** [comment]
Hi!  Thanks for the question, and sorry that you're having trouble using LibGit2Sharp.

We use the issue tracker for issues (bugs and features) - we use [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2sharp) for questions and for help with the API.  That lets your questions get much more visibility, persist longer and be much more searchable.  It lets us help you better, and helps the people who have the same question after you.

So I'm going to close this, and I'd encourage you to ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2sharp) (making sure to add the [LibGit2Sharp](http://stackoverflow.com/questions/tagged/libgit2sharp) tag!)

**Comment by SoftwareArchitec** [comment]
Thanks for your answer. I created this issue on StackOverflow. 
[https://stackoverflow.com/questions/49757591/401-error-on-push-to-gogs-git-with-public-repository](url)
