### ISSUE TITLE
RetrieveStatus with WorkDirOnly returns ignored files

### ISSUE THREAD

**Issue by battlmonstr** [libgit2/libgit2sharp#1566]
LibGit2Sharp version: 0.22
.NET version: 4.5
32-bit process

### Test code:

    var repository = new lg.Repository(...);
    var options = new StatusOptions();
    options.Show = StatusShowOption.WorkDirOnly;
    foreach (var entry in repository.RetrieveStatus(options)) {
    	Console.WriteLine("{0}", entry.FilePath);
    }

### Output:
```
.vs\
.packages\
myproject\bin\
myproject\myproject.csproj.user
```

.gitignore inside the repo has:
```
/.vs/
/packages/ 
bin/
*.user 
```

### Expected

Expected to not have the ignored files & folders in the output.

Just as `git status`.

**Comment by ethomson** [comment]
As the documentation for `StatusOptions` states:

> Include ignored files when scanning for status
> ignored meaning present in .gitignore. Defaults to true for back compat but may improve perf to not include if you have thousands of ignored files.

You can either filter out the entries that are ignored, or you can set `StatusOptions.IncludeIgnored = false`.

**Comment by battlmonstr** [comment]
Thanks for explanation. I didn't find this option in 0.22. But I've found a workaround for now, so that's fine.
