### ISSUE TITLE
Pull operation not on Network object

### ISSUE THREAD

**Issue by ntregillus** [libgit2/libgit2sharp#1575]
### Reproduction steps
https://github.com/libgit2/libgit2sharp/wiki/git-pull method described here does not exist
### Expected behavior
LibGit2Sharp.Network should have a Pull method to retrieve the current branches contents
### Actual behavior
LibGit2Sharp.Network does not have a Pull method as the documentation describes
### Operating system(s) tested; .NET runtime tested
  <package id="LibGit2Sharp" version="0.25.0" targetFramework="net461" />
attempting to run on azure web app

**Comment by PHMarc** [comment]
Hello,
You can use  Commands.Pull() for pull

**Comment by kobake** [comment]
Now I fixed the wiki so as to match the current spec.
https://github.com/libgit2/libgit2sharp/wiki/git-pull

**Comment by ethomson** [comment]
Thanks!
