### ISSUE TITLE
How to use this code in VS.NET 2015?

### ISSUE THREAD

**Issue by krishnasegu21** [libgit2/libgit2sharp#1578]
Hi Team, 

I want to use this library in my Vs.Net 2015 & Net 4.6.2 framework project. Could you please help me how to use this in VS.NET 2015?

Regards,
RK

**Comment by bording** [comment]
What problem are you having when trying to use LibGit2Sharp with VS 2015? 

I'm going to guess that it might be that you're having trouble installing the NuGet package? If so, then you need to make sure you have the latest version of the NuGet tooling installed to support .NET Standard 2.0 packages.

You need to have 3.6.0 installed: https://dist.nuget.org/visualstudio-2015-vsix/v3.6.0/NuGet.Tools.vsix

**Comment by ethomson** [comment]
Hi @krishnasegu21 - it looks like you've got things working!  If not, please feel free to ask a question on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2Sharp).  Thanks!
