### ISSUE TITLE
is it friendly to dotnet core?

### ISSUE THREAD

**Issue by MrLiu0635** [libgit2/libgit2sharp#1579]
I'm working on cross platform app based on dotnet core. when I try to use libgit2sharp in my app, It can work on windows, but it don't work correctly on cent os 7.

Error:System.DllNotFoundException: Unable to load DLL 'git2-6311e88': The specified module or one of its dependencies could not be found.

I wonder if it had been fitted to dotnet core?

thx

**Comment by bording** [comment]
LibGit2Sharp requires a native libgit2 binary in addition to the managed LibGit2Sharp managed assembly. At the moment, the only linux distro that is likely to work out of the box is going to be Ubuntu.

However, that should be changing very soon. The goal is to have all linux distros supported by .NET Core to be covered.

**Comment by MrLiu0635** [comment]
thx for your reply. Do you mean that it has been verified it can work on ubuntu & dotnet core?

**Comment by bording** [comment]
Yes, the linux binary that is currently shipped in the LibGit2Sharp.NativeBinaries package was built on Unbuntu, so it will work.

**Comment by MrLiu0635** [comment]
thx, I have made it. It works on centos / ubuntu.

this issue gave me a workable solution. thx to @goranmaricic.
[https://github.com/cake-contrib/Cake_Git/issues/61](https://github.com/cake-contrib/Cake_Git/issues/61)
