### ISSUE TITLE
NuGet Package error

### ISSUE THREAD

**Issue by cagdasumay** [libgit2/libgit2sharp#1584]
I wanted to install this package to my project. But it gives the following error.

I downloaded the nuget version  https://dist.nuget.org/visualstudio-2015-vsix/v3.6.0/NuGet.Tools.vsix
And I am using vs2015pro.

Could not install package 'LibGit2Sharp 0.25.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by bording** [comment]
The package only works on platforms that support .NET Standard 2.0, so you'll need to update to at least .NET Framework 4.6.1 if you want to use it.

**Comment by cagdasumay** [comment]
Thank you for your response.
Is there any version I can use with .NETFrameworkVersion=v4.5.2

**Comment by bording** [comment]
You can use 0.24.1 or older if you require .NET Framework 4.5.2. LibGit2Sharp 0.25.0 and newer only support platforms that implement .NET Standard 2.0.

**Comment by cagdasumay** [comment]
thank you very much.
