### ISSUE TITLE
Is there any way to rename or delete the GitHub remote master branch?

### ISSUE THREAD

**Issue by verxion** [libgit2/libgit2sharp#1589]
I’ve created this question over on StackOverflow, but it hasn’t generated much interest.  I’m hoping it has a simple answer.  :)

https://stackoverflow.com/questions/51034730/is-there-a-way-to-rename-a-remote-github-repo-using-libgit2sharp

-Verxion

**Comment by ethomson** [comment]
Thanks for asking on StackOverflow, that's the correct place for questions like this.  Thanks!
