### ISSUE TITLE
Issue Installing LibGit2Sharp 0.25.2

### ISSUE THREAD

**Issue by jspencer92** [libgit2/libgit2sharp#1598]
### Reproduction steps
Attempt Nuget install of LibGit2Sharp 0.25.2 on project targeting .Net versions 4.5.x, 4.6.x, 4.7.x

### Expected behavior
Install without error

### Actual behavior
Install fails with error:
Could not install package 'LibGit2Sharp 0.25.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Version of LibGit2Sharp (release number or SHA1)
0.25.2

### Operating system(s) tested; .NET runtime tested
Windows 7, VS2015, .Net 4.5.2, 4.6.1, 4.7.1, 4.7.2

**Comment by bording** [comment]
You're still using Visual Studio 2015? You need additional tooling installed to work with .NET Standard 2.0 libraries.

First, you need to install NuGet 3.6.0: https://dist.nuget.org/visualstudio-2015-vsix/v3.6.0/NuGet.Tools.vsix

Once you have that installed, you should see a different error message telling you that you need to install something else to have .NET Standard 2.0 support, and it will include a link. Install that, and then  you should be able to use any .NET Standard 2.0 library, including LibGit2Sharp.

However, what you should really do is start using Visual Studio 2017 instead.

**Comment by jspencer92** [comment]
Thanks for the quick reply. Hoping to upgrade to 2017 soon, but in the meantime your workaround works just fine.
