### ISSUE TITLE
File is staged for deletion when calling `repo.Index.Add()` then `repo.Index.Commit()`

### ISSUE THREAD

**Issue by apuchkov** [libgit2/libgit2sharp#1620]
It is mentioned in [Git add wiki](https://github.com/libgit2/libgit2sharp/wiki/Git-add) to call `    repo.Index.Add();` to stage a file. However, doing so causes a newly added file to be staged for deletion after commit. Then it gets deleted on the following commit.

Maybe it is related to #1412

### Reproduction steps

```c#
using (var repo = new Repository("path/to/your/repo"))
{
    //there's a new untracked file at this point
    repo.Index.Add("file/with/changes.txt");
    //file still shows as untracked in git status at this point
    repo.Commit(message, author, committer);
    //a new commit is created with the new file, but deletion of the file is also staged.
    //see git status at this point below
}
```

git status output after commit:
```console
>git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    file/with/changes.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        file/with/changes.txt
```

It works correctly if `repo.Index.Write();` is called after `repo.Index.Add("file/with/changes.txt");`
It also works correctly if `Commands.Stage(repo, "file/with/changes.txt");`  is called instead of `repo.Index.Add()` 

If this is intended behavior I wonder if `repo.Index.Add()` should call `repo.Index.Write();` internally or maybe `repo.Commit();` should check if `repo.Index.Write();` was called.

### Expected behavior
Empty stage after commit

### Actual behavior
File staged for deletion after commit.

### Version of LibGit2Sharp (release number or SHA1)
0.23.1 & 0.25.3 
I didn't test it on 0.21.0.176 now, but we used that version a while before and I believe we didn't have this issue back then.

### Operating system(s) tested; .NET runtime tested
Windows 10, .NET 4.5.1 & .NET 4.6.1

**Comment by apuchkov** [comment]
I added a `repo.Index.Write();` call to [Git add wiki](https://github.com/libgit2/libgit2sharp/wiki/Git-add).

**Comment by ethomson** [comment]
Thanks.  The wiki needed to be updated to reflect the actual behavior.
