### ISSUE TITLE
Remove unused branches

### ISSUE THREAD

**Issue by simondel** [libgit2/libgit2sharp#1622]
This repo has a lot of branches that have already been merged. They could probably be removed. There are also a bunch of branches that have a single commit, which was made more than a year ago. In order to know what should and shouldn't be merged/worked on in the future, it may be nice to remove these branches.

Note: the current contribution docs in the wiki mention that PRs should target the vNext branch, but that does not seem to be the case anymore.

**Comment by bording** [comment]
> This repo has a lot of branches that have already been merged. They could probably be removed.

@ethomson What are your thoughts on this? I prefer to delete branches once they've been merged, but I have noticed you tend to keep them around. Any specific reason to keep them?

> Note: the current contribution docs in the wiki mention that PRs should target the vNext branch, but that does not seem to be the case anymor

This should definitely be updated now that we've moved away from that branching model and just have `master`.

**Comment by ethomson** [comment]
> @ethomson What are your thoughts on this? I prefer to delete branches once they've been merged, but I have noticed you tend to keep them around. Any specific reason to keep them?

Nope, no reason.

**Comment by bording** [comment]
I've gone through and removed a lot of old and merged branches.

I've also updated the wiki to remove reference to the vNext branch.
