### ISSUE TITLE
linux-x64 libcurl.so.4 ABI incompatibility

### ISSUE THREAD

**Issue by akihikodaki** [libgit2/libgit2sharp#1626]
`libcurl.so.4` linked to the binary has a bug described at https://github.com/curl/curl/issues/2433. Please do not link to Debian libcurl when you build one.

### Reproduction steps

Use Linux-x64 runtime on a Linux system which is not Debian or its derivatives.

### Expected behaviour

It  works.

### Actual behavior

It triggers https://github.com/curl/curl/issues/2433.

### Version of LibGit2Sharp (release number or SHA1)

0.26.0-preview-0027

### Operating system(s) tested; .NET runtime tested

Arch Linux

**Comment by ethomson** [comment]
We're working on several fronts to remove the dependency on libcurl for this and other reasons.  I'm going to close this issue, since it's (basically) a dup, but this is my top priority for libgit2 and LibGIt2Sharp.

**Comment by ethomson** [comment]
Hmm, in fact, I don't see an issue for this in this repo.  I'll leave it open, but #1618 will fix this.

**Comment by bording** [comment]
@akihikodaki I'd like to point out that Arch Linux is not a distro supported by .NET Core: https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1-supported-os.md

Are you trying to use Arch Linux on .NET Core, or are you using Mono?

**Comment by akihikodaki** [comment]
> Are you trying to use Arch Linux on .NET Core, or are you using Mono?

Both.

**Comment by bording** [comment]
This has been fixed in 0.26.0 because the native binaries no long have a curl dependency.
