### ISSUE TITLE
Git2Sharp repository commits differences (vs Git)

### ISSUE THREAD

**Issue by VE-2016** [libgit2/libgit2sharp#1638]
Dear Sirs,
I have noticed that git2sharp commit history as repo.Commits , for example of https://github.com/pytorch/glow differs from commits history presented by Git bash or Visual Studio branch history. 

### Reproduction steps

Open repo.Commits for https://github.com/pytorch/glow from git2sharp

Compare to git history from Git bash

The sequence of commits differs for both. 

### Expected behavior

The sequence is the same

### Actual behavior

There are differencies

### Version of LibGit2Sharp

Current github repository

### Operating system(s) tested; .NET runtime tested
Windows 10, .NET Framework 4.7.2

**Comment by ethomson** [comment]
How are they different?  What is your sorting mechanism?  Can you show some code?

**Comment by VE-2016** [comment]
With no sorting, looping by
foreach (Commit commit in repo.Commits)
{
         Console.WriteLine("{0} | {1}", commit.Sha, commit.MessageShort);   }
}
gives slight differences.

Best regards,
JK
