### ISSUE TITLE
Failed to authenticate SSH session: Callback returned error

### ISSUE THREAD

**Issue by ymcymc** [libgit2/libgit2sharp#1641]
hi
i got some error like title when i call "ssh clone command", how can i fix this error?

vs 2017
C# .net 4.5
window 10 Pro N
libgit2sharp-ssh   1.0.22

CloneOptions clone = new CloneOptions()
            {
                CredentialsProvider = (url, user, cred) => new SshUserKeyCredentials()
                {
                    Passphrase = "123456",
                    PrivateKey = @"D:\id_rsa",
                    Username = "git",
                    PublicKey = @"D:\id_rsa.pub"
                }
            };
Repository.Clone("git@github.com:username/repo.git", @"d:\abcde", clone);

**Comment by bording** [comment]
libgit2sharp-ssh is not an official package that we released. We don't ship any packages that include SSH support.

**Comment by ymcymc** [comment]
got it,
thanks
