### ISSUE TITLE
Help with PAT Token

### ISSUE THREAD

**Issue by ChrisCalzaretta** [libgit2/libgit2sharp#1660]
How can I connect with a Pat Token
Personal Access Token. When I try to connect I don't see an option for a pat token only a user name and password
The pat token url would be something like
https://{PATTOKEN}@{dev.azure.com/OrgName}/_git/{Repo}

Can you please add this feature?

Thanks

Chris

**Comment by ethomson** [comment]
A PAT token enables HTTP Basic authentication to systems that have more complex authentication requirements, like 2FA.  You should use it exactly like a username and password.

**Comment by ChrisCalzaretta** [comment]
Fair enough. I am using the username and password field with success

Thanks for the response.

Chris

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by ethomson** [comment]
Awesome, thanks for letting me know.  👍
