### ISSUE TITLE
DefaultCredentials() doesn't appear to work for remote TFS git repository

### ISSUE THREAD

**Issue by david-shortman** [libgit2/libgit2sharp#1671]
I am trying to list the branches of a remote git repository hosted in TFS.

I appear to be having an authentication issue; my local machine has the credentials for this git repo stored in Credential Manager, and I can connect to it through Powershell and through Visual Studio.

### Reproduction steps
Tried to list remote branches using the following code:

`Repository.ListRemoteReferences("http://{serverName}:{port}/tfs/Development/_git/{projectName}", New Handlers.CredentialsHandler(Function(_url, _user, _cred) New DefaultCredentials())) .Where(Function(x) x.IsLocalBranch) .Select(Function(x) x.CanonicalName).ToList()
`

### Expected behavior
Get a list of branches

### Actual behavior
Get the following exception:

```
Error: this remote has never connected
Inner Exception:    N/A
Source: LibGit2Sharp
Stack Trace: at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) 
    at LibGit2Sharp.Core.Proxy.git_remote_ls(Repository repository, RemoteHandle remote) at LibGit2Sharp.Repository.ListRemoteReferences(String url, CredentialsHandler credentialsProvider) 
    at Composer.Web.ConfigurationTools.EditAzureEnvironment.GetMobileGitBranches() in C:\TFS2010\DiamondComposer\Code\Development\DiamondComposer\ASPNET\ConfigurationTools\DaaP\EditAzureEnvironment.ascx.vb:line 289
```

### Version of LibGit2Sharp (release number or SHA1)
0.26.0.0

### Operating system(s) tested; .NET runtime tested
Windows 10 16299.904
.NET Runtime 4.7.2

**Comment by SephirotJustin** [comment]
Im not sure its there a relation to your problem but i have too a problem with a tfs repository.
I can not push to the remote. When i try to push, im getting a http exception with error code '503'. But when i create just a new process with git push then its works. 

Do you have similar problems to push your repo?

**Comment by sharpSteff** [comment]
@SephirotJustin '503' happens also to me see #1682 
via git clone cmd everything works fine (also other tools like tortoisegit have no problems)

**Comment by lstefano71** [comment]
As far as I know, the token should go in the Password and the User field should contain the user which created the token. It certainly works for me that way...

**Comment by david-shortman** [comment]
closing since this doesn't seem to be a hot issue and it's not something I need resolved anymore

**Comment by ethomson** [comment]
Hey @david-shortman - sorry that this never got replied to, I'm just seeing it in my notifications now.  Just in case it's useful in the future or somebody else comes across this:

> I appear to be having an authentication issue; my local machine has the credentials for this git repo stored in Credential Manager, and I can connect to it through Powershell and through Visual Studio.

In that case, `DefaultCredentials` are not the appropriate choice here.  You should use `UsernamePasswordCredentials` if you need to use a username and password.  LibGit2Sharp has no mechanism to get those credentials out of Credential Manager, you'll need to get them out yourself and supply them.

DefaultCredentials is for Kerberos or NTLM2 single sign-on, using your existing domain credentials.  I'm assuming that a "remote" TFS server is one without a domain bindings to your current logon domain.  (Something like `dev.azure.com`.)  DefaultCredentials will not work in these cases.  They'll only work against an on-premises Azure DevOps (formerly TFS) server with domain trust.
