### ISSUE TITLE
Custom marshaling not supported

### ISSUE THREAD

**Issue by jjschweigert** [libgit2/libgit2sharp#1688]
### Reproduction steps
1. Create UWP gui app targeting Windows 10 1809 Build 17763
2. Attempt to clone repo using example from: https://github.com/libgit2/libgit2sharp/wiki/git-clone with CloneOptions set, valid URl, valid path, and valid username/password. Also tested with invalid parameters (empty strings) and the error message occurs regardless.

Url given in form "https://github.com/path/to/repo.git"
Folder path given as: @"C:\Source\" and @"C:/Source/"

Not sure what all information is needed but here's some info from the exception object:

HResult: -2146233031
Source: "LibGit2Sharp"
Message: "Custom marshalers are not supported"
StackTrace:

"   at LibGit2Sharp.Core.NativeMethods.git_clone(git_repository*& repo, String origin_url, FilePath workdir_path, GitCloneOptions& opts)\r\n   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)\r\n   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)\r\n   at GitManager.UWP.Views.Settings.Button_Click_1(Object sender, RoutedEventArgs e)"

### Expected behavior
Either seeing expected errors such as bad url, bad username/password, no permissions to local path for repo, or a successful clone.

### Actual behavior
Call fails with error: "Custom marshalers are not supported"

### Version of LibGit2Sharp (release number or SHA1)
0.26.0

### Operating system(s) tested; .NET runtime tested
Visual Studio 2019 on Windows 10
Runtime error

This is probably an issue with something in a UWP app with what libgit2sharp is written for but just checking if there is anything that can be done.

Thanks!

**Comment by bording** [comment]
Unfortunately, there's not really anything we can do. LibGit2Sharp requires custom marshalers, so if UWP doesn't support them, then it's not going to work.

**Comment by jjschweigert** [comment]
> Unfortunately, there's not really anything we can do. LibGit2Sharp requires custom marshalers, so if UWP doesn't support them, then it's not going to work.

Hey bording, I'm rebuilding using a WPF app which appears to work with this. Thanks for clarifying!

**Comment by andygikling** [comment]
So the only .NET Standard library for git doesn't support UWP?  C'mon!!!  What are we doing here?  If you support .NET Standard, it should work in UWP.

**Comment by ethomson** [comment]
> So the only .NET Standard library for git doesn't support UWP? C'mon!!! What are we doing here? If you support .NET Standard, it should work in UWP.

Do you know how to resolve the marshaling problem?

**Comment by bording** [comment]
From my understanding of UWP, despite the platform claiming to support `netstandard2.0`, there are parts of the API that it does not support, custom marshaling being one of those.

Custom marshaling is something that LibGit2Sharp requires to operate, so there's nothing we can do to make LibGit2Sharp work on UWP. 

Microsoft would have to add support for things like custom marshaling first, but if they didn't do that initially when adding `netstandard2.0` support, I would think that there were legitimate reasons they didn't.

**Comment by areading314** [comment]
I'm not a C# expert but am working on a Windows app for making certain git workflows easier. If its not possible for this library to work from UWP, what are the alternatives? I see that using a WPF/C# app is one, would writing the UWP application in C++ instead work too, thus bypassing the need for this library?
