### ISSUE TITLE
libgit2sharp-ssh NPM package file conflict

### ISSUE THREAD

**Issue by heyitsfranklin** [libgit2/libgit2sharp#1717]
### Reproduction steps

1. Create a new Visual Studio Project
2. Install libgit2sharp v0.24.1 from NPM
3. Install libgit2sharp-SSH v1.0.22 from NPM
4. Build the solution

### Expected behavior
Build should succeed

### Actual behavior
The following errors are thrown:
- Resource identifier 'MyProject.libgit2_hash.txt' has already been used in this assembly
- Resource identifier 'MyProject.libgit2_filename.txt' has already been used in this assembly

![screen](https://user-images.githubusercontent.com/11930733/65144511-6b3c7680-da0f-11e9-9563-ddaa6db53948.png)

If I uninstall libgit2sharp-SSH the error goes away.

### Version of LibGit2Sharp (release number or SHA1)
libgit2sharp v0.24.1
libgit2sharp-SSH v1.0.22 

### Operating system(s) tested; .NET runtime tested
Windows 10 x64
.NET 4.5.1

**Comment by ethomson** [comment]
You can't use these side-by-side.  You need to pick one or the other.

In fact, you shouldn't use libgit2sharp-SSH _at all_, it's a several year old build by a random person that includes cryptographic libraries that are probably outdated and may have security holes in them.  It's not an official build.

**Comment by heyitsfranklin** [comment]
I see! Thanks for clearing that up. I did some more digging around and found an alternative method

https://github.com/cake-contrib/Cake_Git/issues/94
