### ISSUE TITLE
This application has failed to start because the application configuration is incorrect

### ISSUE THREAD

**Issue by cilerler** [libgit2/libgit2sharp#1718]
I have a WPF application, and I'm getting the error message below upon adding the library.

- Removing the library makes it work again
- Compared the solution directories before and after the install. Literally the only difference are in **packages.config** and **myProject.csproj** which I provided below.  I also added "additional few lines hoping that may give you a clue.

> This application has failed to start because the application configuration is incorrect. Review the manifest file for possible errors. Reinstalling the application may fix this problem. For more details, please see the application event log.

![image](https://user-images.githubusercontent.com/385958/65389719-3e49d580-dd27-11e9-83bd-0525dd86e569.png)

#### packages.config

```
  <package id="LibGit2Sharp" version="0.26.1" targetFramework="net472" />
  <package id="LibGit2Sharp.NativeBinaries" version="2.0.289" targetFramework="net472" />
```

#### myProject.csproj

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333, processorArchitecture=MSIL">
      <HintPath>..\..\packages\LibGit2Sharp.0.26.1\lib\net46\LibGit2Sharp.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <Error Condition="!Exists('..\..\packages\LibGit2Sharp.NativeBinaries.2.0.289\build\net46\LibGit2Sharp.NativeBinaries.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\LibGit2Sharp.NativeBinaries.2.0.289\build\net46\LibGit2Sharp.NativeBinaries.props'))" />
  </Target>
  <Import Project="..\..\packages\LibGit2Sharp.NativeBinaries.2.0.289\build\net46\LibGit2Sharp.NativeBinaries.props" Condition="Exists('..\..\packages\LibGit2Sharp.NativeBinaries.2.0.289\build\net46\LibGit2Sharp.NativeBinaries.props')" />
</Project>
```

#### Event logs - SideBySide
```
Activation context generation failed for "C:\Source\github\myProject\src\MyApp\bin\Debug\MyApp.exe.Manifest".Error in manifest or policy file "C:\Source\github\myProject\src\MyApp\bin\Debug\MyApp.exe.Manifest" on line 1207. The value "lib\alpine.3.9-x64\native\..\libgit2-7ce88e6.so" of attribute "name" in element "urn:schemas-microsoft-com:asm.v1^file" is invalid.
```

#### Manifest file line 1207
```
  <file name="lib\alpine.3.9-x64\native\..\libgit2-7ce88e6.so" size="1328560">
    <hash>
      <dsig:Transforms>
        <dsig:Transform Algorithm="urn:schemas-microsoft-com:HashTransforms.Identity" />
      </dsig:Transforms>
      <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha256" />
      <dsig:DigestValue>dB4Q60wN4VMMMXxILRlbKYEReOqrxvLr0+IXJaLy5HA=</dsig:DigestValue>
    </hash>
  </file>
```

**Comment by cilerler** [comment]
I appreciate it if this issue can get any attention

**Comment by bording** [comment]
@cilerler This doesn't really have anything to do with fact that it's a WPF project, but that you've enabled manifest generation in your project.

Do you have a specific reason to need the manifest? From my understanding, the primary reason you'd have that enabled is when using ClickOnce as a deployment method.

Overall, I'd recommend never using ClickOnce, because it's a pretty terrible deployment method, with all sorts of problems you can run into with it, and they are often things that there are no workarounds for.

**Comment by bording** [comment]
If for some reason you can't just disable the manifest generation, adding the following to your project file should help:

```
  <Target Name="RemoveNonWindowsLibGit2SharpLibraries" BeforeTargets="_DeploymentComputeClickOnceManifestInfo">
    <ItemGroup>
      <ContentWithTargetPath Remove="@(ContentWithTargetPath)" Condition="'%(Extension)' == '.so'"/>
      <ContentWithTargetPath Remove="@(ContentWithTargetPath)" Condition="'%(Extension)' == '.dylib'"/>
      <ContentWithTargetPath Remove="@(ContentWithTargetPath)" Condition="'%(Filename)%(Extension)' == 'LibGit2Sharp.dll.config'"/>
    </ItemGroup>
  </Target>
```

The assumption here is that since you're writing a WPF app, you don't need any of the non-Windows files. Those are included by default to enable support for mono.

**Comment by cilerler** [comment]
@bording unfortunately, the application gets deployed via ClickOnce, and have to continue with that method. But the solution you suggested worked like a charm; I appreciate your help, thank you very much. 🤗

**Comment by abulhasanlakhani** [comment]
Thank you so much. This workaround helped me!

**Comment by dliedke** [comment]
Thanks a lot @bording  working fine here as well!!
