### ISSUE TITLE
DllNotFoundException with dotnet core 3

### ISSUE THREAD

**Issue by felixfbecker** [libgit2/libgit2sharp#1740]
You are opening a _bug report_ against the LibGit2Sharp project: we
use GitHub Issues for tracking bug reports and feature requests.  If
you have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2sharp.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

### Reproduction steps

Using libgit2sharp in dotnet core 3 always errors.

### Expected behavior

Should work in dotnet core 3.

### Actual behavior

It compiles fine, however when using `dotnet publish`, the output folder no longer contains a `runtimes` folder with the native libraries for every OS as it did before.

Then when actually executing anything in libgit2sharp, it fails with:

```
"The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception." ---> System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-ef5a385' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libgit2-ef5a385, 1): image not found
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
   at LibGit2Sharp.Core.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at LibGit2Sharp.Core.NativeMethods.git_repository_open_ext(git_repository*& repository, FilePath path, RepositoryOpenFlags flags, FilePath ceilingDirs)
   at LibGit2Sharp.Core.Proxy.git_repository_open_ext(String path, RepositoryOpenFlags flags, String ceilingDirs)
   at LibGit2Sharp.Repository.IsValid(String path)
   at CallSite.Target(Closure , CallSite , Type , String )
```

I cannot figure out how to get the needed DLLs, I have tried every flag of `dotnet publish`.
The release notes contain a hint that now dotnet supports bundling even native dependencies into a single file, but I cannot get it to work. https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables

### Version of LibGit2Sharp (release number or SHA1)

`0.27.0-preview-0029` and `0.26.1`

### Operating system(s) tested; .NET runtime tested

```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
```

**Comment by bording** [comment]
I can't reproduce this with a simple console app. When I `dotnet publish`, the publish output includes the  `runtimes` folder, as expected.

Can you provide a sample project that demonstrates the problem?

**Comment by felixfbecker** [comment]
Interesting. You can check out the branch `dotnet-3` of this repo: https://github.com/felixfbecker/PowerGit/pull/19

**Comment by bording** [comment]
Okay, now I see what the difference is. 

This really doesn't have anything to do with LibGit2Sharp specifically, but the changes to the .NET Core 3.0 SDK.

The .NET Core 3.0 SDK has changed how things work regarding build and publish output. Since your project file is `netstandard2.0`, that is a a non-executable library assembly, so they aren't copying the `runtimes` folder into the output. If you change the TFM to something executable, `netcoreapp3.0` for example, and add `<OutputType>Exe</OutputType>` to the project file, you'll see the runtimes folder.

I do have a workaround for you: https://github.com/felixfbecker/PowerGit/pull/20

**Comment by felixfbecker** [comment]
Thank you so much! 🙏
