### ISSUE TITLE
Support Ubuntu 20.04 (Focal)

### ISSUE THREAD

**Issue by gitfool** [libgit2/libgit2sharp#1747]
Not sure if this is related to #1585, so creating a separate issue.

See [Cake.Dungeon](https://github.com/gitfool/Cake.Dungeon) Docker [build](https://github.com/gitfool/Cake.Dungeon/runs/366382730) where I'm doing a [Cake](https://github.com/cake-build/cake) build in a Docker container [based](https://github.com/gitfool/cake-docker/blob/12343a74846e4a940e34ec4be7a0ac40daf795a9/Dockerfile#L1) on Ubuntu 20.04 (Focal) using the .NET Core 3.1 SDK [nightly](https://hub.docker.com/_/microsoft-dotnet-core-nightly-sdk/) preview ([Dockerfile](https://github.com/dotnet/dotnet-docker/blob/nightly/3.1/sdk/focal/amd64/Dockerfile)). The build [fails](https://github.com/gitfool/Cake.Dungeon/runs/366382730#step:6:241) with error:
```
System.DllNotFoundException: Unable to load shared library 'git2-106a5f2' or one of its dependencies...
```
I'm using [GitVersion](https://github.com/GitTools/GitVersion) 5.1.3, which is already using the [latest](https://github.com/GitTools/GitVersion/blob/master/src/Directory.Build.props#L20-L21) LibGit2Sharp libraries AFAICT.

**Comment by patrolez** [comment]
I can see that this is related to OpenSSL version.

Since Ubuntu Eoan it looks like OpenSSL 1.0 was taken out from the repository in favour of OpenSSL 1.1.

```
$ ldd libgit2-106a5f2.so 
        linux-vdso.so.1 (0x00007ffe315c9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc11351a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc1134f7000)
        libssl.so.1.0.0 => not found
        libcrypto.so.1.0.0 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc113306000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc11386c000)
```

**Comment by patrolez** [comment]
It looks like <https://github.com/libgit2/libgit2sharp/pull/1714> solves this issue. It is included in 0.27-preview releases in NuGet.

**Comment by patrolez** [comment]
~@gitfool It looks like <https://github.com/libgit2/libgit2sharp/pull/1714> solves this issue. It is included in `0.27-preview` releases in NuGet.~

Nope. It is not. Publishing packages still bundles wrong library - linked against OpenSSL 1.0 instead of 1.1 if target is `linux-x64`.

The solution is to target Ubuntu bionic runtime: `dotnet publish -r ubuntu.18.04-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true`

**Comment by dnperfors** [comment]
Any change that this bug will be fixed soon? Github will move their default linux agents to Ubuntu 20.04 which means that a lot of people will get breaking builds soon.

**Comment by ethomson** [comment]
libssl is no longer a dependency for the LibGit2Sharp builds, thanks to libgit2/libgit2sharp#1618. Upgrading to the latest nuget package will fix this. https://www.nuget.org/packages/LibGit2Sharp/0.27.0-preview-0096
