### ISSUE TITLE
Unable to load DLL 'git2-106a5f2'

### ISSUE THREAD

**Issue by jjhayworth** [libgit2/libgit2sharp#1780]
### Reproduction steps
1. Open .NET Framework 4.6 project
2. Install LibGit2Sharp.NativeBinaries v2.0.312 NuGet package.
3. Install LibGit2Sharp v0.26.2 NuGet Package.
4. In a .cs file,  insert
`Repository repo = new Repository();`
### Expected behavior
Works.
### Actual behavior
System.TypeInitializationException
  Message=The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
Inner Exception 1:
DllNotFoundException: Unable to load DLL 'git2-106a5f2': The specified module could not be found. 

### Version of LibGit2Sharp (release number or SHA1)
v0.26.2
### Operating system(s) tested; .NET runtime tested
Windows 10, .NET Framework 4.6

**Comment by bording** [comment]
@jjhayworth LibGit2Sharp requires specific versions of the LibGit2Sharp.NativeBinaries package, which is why its shipped with the package version locked.

The 0.26.2 package requires you to use LibGit2Sharp.NativeBinaries 2.0.306 only. You should be getting a warning or error in your project to even have a newer version installed.

**Comment by jjhayworth** [comment]
@bording changing my NativeBinaries version from .312 to .306 got things working, thank you.

**Comment by Georgeeden** [comment]
> @jjhayworth I have
> 
> ```
> <package id="LibGit2Sharp" version="0.26.2" targetFramework="net472" />
>  <package id="LibGit2Sharp.NativeBinaries" version="2.0.306" targetFramework="net472" />'
> ```
> 
> but still same issue
> 
> `Unable to load DLL 'git2-106a5f2': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

Hi, Did you ever manage to fix this? I have been having the same problem but have not been able to find a way to solve it.

**Comment by NPatch** [comment]
Having the same issue as well. I have the same version for both libgit2sharp and the binaries package, yet in the bin folder, only libgit2sharp dll exists.
