### ISSUE TITLE
Lists with addedLines and deletedLines in ContentChanges

### ISSUE THREAD

**Issue by Stijn-Rutten** [libgit2/libgit2sharp#1789]
I would like to have the possibility to have `IEnumerables` of `deletedLines` and `addedLines` in `ContentChanges` these would contain an instance of the following struct for each line containing the line number and the added or deleted content on that line.

```
struct Line {
    public int LineNumber { get; }
    public string Content { get; }
}
```
This modification would make it easier to navigate through the compare different states of files. Instead of having to parse the `patch`

**Comment by bording** [comment]
Implemented in #1790
