### ISSUE TITLE
Git object is too large to materialize into memory

### ISSUE THREAD

**Issue by marncosta** [libgit2/libgit2sharp#1803]
### Reproduction steps
Try to do a pull request with a project that has about 105 Mb 

### Expected behavior
To have pull request finalized

### Actual behavior
It generates a error: by policy the git object is too large to materialize into memory

### Version of LibGit2Sharp (release number or SHA1)
Azure Devops Server UPDATE 1

**Comment by marncosta** [comment]
I saw one issue, that you answered, that you have forced this limit for TFS 2017. But It was in 2017 year. Is it valid this limit for Azure Devops 2019?

**Comment by ethomson** [comment]
I don't know; I don't think that this issue has anything to do with libgit2 or LibGit2Sharp.  I think that this is a limit built in to Azure DevOps Server.  (I also think that it's configurable.)  But I don't know, I haven't worked on this product in many years.

**Comment by marncosta** [comment]
The mentioned issue was #1486

**Comment by ethomson** [comment]
I see.  Yes, this is still a limitation in Azure DevOps Server 2019, and this is still not a bug in LibGit2Sharp.

**Comment by marncosta** [comment]
OK. I am closing the issue. Thanks..
