### ISSUE TITLE
how to check if everything is up to date before pushing?

### ISSUE THREAD

**Issue by jalil1408** [libgit2/libgit2sharp#1815]
how to check if every thing is up to date before pushing?
something like :
       git push remote --all --dry-run

**Comment by ethomson** [comment]
You've deleted the important part of the issue template:

> You are opening a _bug report_ against the LibGit2Sharp project: we
use GitHub Issues for tracking bug reports and feature requests.  If
you have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2sharp.

I would encourage you to do exactly that - ask this question on StackOverflow: http://stackoverflow.com/questions/tagged/libgit2sharp
