### ISSUE TITLE
NuGet Package Manager prompts to update LibGit2Sharp.NativeBinaries package, but it will not let me

### ISSUE THREAD

**Issue by astrohart** [libgit2/libgit2sharp#1826]
### Bug

I think someone meant to put a '>=' sign for a dependency, and instead, a typographical error happened in the package definition, resulting in an '=' sign being placed instead.  This causes Visual Studio to (a) prompt to update the `LibGit2Sharp.NativeBinaries` NuGet package, and then refuse to do so because the dependency is broken (see below), thus causing user confusion.

### Reproduction steps

**NOTE:** The following assumes that the **NuGet Package Manager** is installed in your copy of Visual Studio.

1. Open Visual Studio 2019.
2. Open a C# project or create a new one that does not have the `LibGit2Sharp` NuGet package installed yet.
3. Right-click the project's **References** folder and then click **Manage NuGet Packages**.
4. In the NuGet Package Manager, click the **Browse** tab, and then type `LibGit2Sharp` in the **Search** box.  
5. Install the `LibGit2Sharp` package, latest stable version (0.26.2 at the time of this post).
6. The **Updates** tab lights up with a number '1' showing 1 update available.  Click the **Updates** tab.
7. The package `LibGit2Sharp.NativeBinaries` package is listed as needing an update.
8. On the right-hand pane of the NuGet Package Manager's **Update** tab, click **Update** to attempt to update the package.

### Expected behavior

The package update completes successfully.

### Actual behavior

The update fails with the error:

![image](https://user-images.githubusercontent.com/8261875/90956276-06757180-e453-11ea-989c-859b089f7e66.png)

This is a screenshot of my NuGet Package Manager after Step 6:

![image](https://user-images.githubusercontent.com/8261875/90956325-8c91b800-e453-11ea-818f-110cf4cc697a.png)

### Suggested fix:

Edit the dependency constraint on the `LibGit2Sharp` NuGet package to be `LibGit2Sharp.NativeBinaries **>=** 2.0.306`.

### Version of LibGit2Sharp (release number or SHA1)

0.26.2

### Operating system(s) tested; .NET runtime tested

.NET Framework 4.8

### Additional information:

I think there is a typo somewhere in the definition of the `LibGit2Sharp` package configuration.  See, e.g., the screenshot of the error window above.  Did someone make a typographical error and put an '=' sign where there should have been a '>=' sign?

**Comment by ethomson** [comment]
Is there a better way to reduce the noise for you?  I'm not super familiar with this - is it recommending semver compatible updates?  If so, maybe the natives should update their major version number per build.

**Comment by bording** [comment]
> Is there a better way to reduce the noise for you? I'm not super familiar with this - is it recommending semver compatible updates? If so, maybe the natives should update their major version number per build.

That UI screen just sees that there is a newer package version than the one being referenced in the project, so bumping the major version wouldn't solve anything.

This is only going to be an issue for projects that are still using packages.config since that file will list all packages, including transitive dependencies.

For newer projects using package references, only the main LibGit2Sharp package would be referenced by the project, so the NuGet UI page wouldn't see the native binaries package to offer an update.
