### ISSUE TITLE
Failed to start SSH session: Unable to exchange encryption keys by using LibGit2Sharp-SSH-updated-libssh2 in asp.net core

### ISSUE THREAD

**Issue by mounikakatt** [libgit2/libgit2sharp#1846]

**Comment by Gredys** [comment]
SSH is not suppoorted, as I know. And `LibGit2Sharp-SSH-updated-libssh2` is different library and not maintained by this repository.

**Comment by bording** [comment]
As @Gredys mentioned, LibGit2Sharp does not support SSH, so any package you are using that claims to support it did not come from this repo.
