### ISSUE TITLE
Partial staging are not doing actual changes to repository or filesystem

### ISSUE THREAD

**Issue by Gredys** [libgit2/libgit2sharp#1847]
I've searched for a way to add partial changes to index and found this issue: [Teach the library to provide support for partial staging](https://github.com/libgit2/libgit2sharp/issues/195)

I tried to use those examples (as along with other examples from stackoverflow related to my topic) and got strange results, which I think is not correct.

I am trying to add programmatically modified file in repository to index changes. But after adding to index, as shown in issue above, weird things are happening to repository instance.

### Reproduction steps
What I did:
1. Cloned existing repository
2. Picked specific file blob from working set by its Id from patch diff 
```
var workingTreeChanges = repository.Diff.Compare<Patch>();
...
var selectedChanges = workingTreeChanges[...];
...
var blob = repository.Lookup<Blob>(selectedChanges.OldOid);
```
3. Converted blob to string, made some changes, converted to stream
4. Added modifed blob to object database and than to index (as was shown in other closed issue)
```
var blob = repository.ObjectDatabase.CreateBlob(stream);
repository.Index.Add(blob, selectedChanges.Path, Mode.NonExecutableFile);
```
5. Index changes was applied after checking with code below
```
var indexTreeChanges = repository.Diff.Compare<Patch>(repository.Head.Tip.Tree, DiffTargets.Index);
```
6.. Closed application and checked whats in index using same code below. Its empty. Checking with other git UI makes same results.
```
var indexTreeChanges = repository.Diff.Compare<Patch>(repository.Head.Tip.Tree, DiffTargets.Index);
```

**P.S. For some reason resulting patch for step 5 is messed up. All lines are removed and than added back, including added few in step 3.**

### Expected behavior
Adding blob to index must actually add that blob to index and do changes to filesystem
Added blob must be visible to any other git UI
Added blob to index must display actual changes and not `all lines removed and added back`

### Actual behavior
Index is changed only in current `Repository` instance and not actually on filesystem
Looking on index thought any other git UI wont show any changes (tested with git extensions)
Restarting application after made changes also wont show changes made in previous launch
Added blob to index will result in messed up patch that will contain `all lines removed and added back`

### Version of LibGit2Sharp (release number or SHA1)
Version: 0.26.2

### Operating system(s) tested; .NET runtime tested
Windows Server 2019
.NET Framework 4.8

**Comment by ethomson** [comment]
> Adding blob to index must actually add that blob to index and do changes to filesystem

Sorry I'm not sure when you say the filesystem whether you mean just the index on disk, or if you also intend to change the files in the working tree.

You'll need to write the index in order for other clients to see it.  You'll need to check the index out if you want those changes reflected in the working tree.

> P.S. For some reason resulting patch for step 5 is messed up. All lines are removed and than added back, including added few in step 3

This sounds like your line ending configuration is not set correctly.  See this for more information: https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

**Comment by Gredys** [comment]
> Sorry I'm not sure when you say the filesystem whether you mean just the index on disk, or if you also intend to change the files in the working tree.

Hello, I mean that there is no any change to any file in git directory, i.e. runtime changes to index are not saved anywhere in repository. Which is strange.

> You'll need to write the index in order for other clients to see it.

I've used method that @nulltoken mentioned in his last comment of #195 issue. Didn't helped.
So what u mean about `you need to write the index`? Can you, please, write a bit more about it?

> This sounds like your line ending configuration is not set correctly. See this for more information:

That could be the problem for added/removed lines, thx. I will check it.
But still - problem with not saved changes to index is neagating everything that I am done at current stage :\

**Comment by ethomson** [comment]
> So what u mean about you need to write the index? Can you, please, write a bit more about it?

You need to call [`Index.Write`](https://github.com/libgit2/libgit2sharp/blob/7fc4be5193dbdd08538b4b150332b5a73770e0f6/LibGit2Sharp/Index.cs#L307).

**Comment by Gredys** [comment]
Hm, wasn't intuitive. But that answers why changes made to index are not saved. Thx.
Seems that all my problems was only just becouse of me. Sry.
