### ISSUE TITLE
Port to .Net 5 and or Net Standard

### ISSUE THREAD

**Issue by litch0** [libgit2/libgit2sharp#1854]
## Feature Request
Hello, Good day, Is it possible to port it to .Net 5.0 and, or .Net Standard?

**Comment by bording** [comment]
LibGit2Sharp already works with .NET Standard 2.0 and .NET Core, so I'm not sure what you're asking for here.

**Comment by litch0** [comment]
ok, I tried installing but i got a compatible error, when using .net 5, but I recently updated so I will try again

**Comment by litch0** [comment]
forget it, it worked now
