### ISSUE TITLE
Hard crash on Alpine 3.13

### ISSUE THREAD

**Issue by jirikopecky** [libgit2/libgit2sharp#1872]
### Reproduction steps
Trying to use libgit2sharp 0.27.0-preview-0096 on Alpine 3.13 causes hard crash of dotnet runtime. Not even catch/finally blocks are executed.

The same code executes just fine on Alpine 3.12.

I've created minimal repro here: https://github.com/jirikopecky/libgit2sharp-alpine3.13-bug-repro

### Expected behavior

Git Log is displayed in the repro application

### Actual behavior

Dotnet process crashes with exit code 139

### Version of LibGit2Sharp (release number or SHA1)

0.27.0-preview-0096

### Operating system(s) tested; .NET runtime tested

Used latest version of docker images `mcr.microsoft.com/dotnet/sdk:5.0-alpine3.12` and `mcr.microsoft.com/dotnet/sdk:5.0-alpine3.13`.
OS: Alpine Linux x64
.NET Runtime 5.0.4

**Comment by altinnadmin** [comment]
We have the same problem, .NET 5 + Alpine 3.12 works fine, updating to Alpine 3.13 causes hard crash and restart loop.
We're on 0.27.0-preview-0034.

**Comment by motion-x86** [comment]
We have same problem as well Alpine 3.13 hard crash

**Comment by altinnadmin** [comment]
Probably related to https://github.com/dotnet/runtime/issues/50739

**Comment by jirikopecky** [comment]
Seems to be fixed with .NET 5.0.10, the repro no longer crashes and also GitVersion is working for me again. Closing the issue.
