### ISSUE TITLE
.Net 5 issues with RetrieveStatus

### ISSUE THREAD

**Issue by joost-morsink** [libgit2/libgit2sharp#1889]
LibGit2Sharp .Net 5 problems

### Reproduction steps

Install the dotnet verbump command line tool (version 0.1.0, runs on both .Net 5 and .Net Core 3.1):

```
dotnet tool install --global verbump --version 0.1.0
```

Run the following command in the root of a git repo:

```
verbump info
```

The source code for this version can be found [here](https://github.com/joost-morsink/VerBump/releases/tag/v0.1.0).

I worked around the issue by making a 0.1.1 version of my tool with the .Net 5 target removed.

### Expected behavior

The expected behaviour is that my app does not crash.

### Actual behavior

On Mac there is a hang (on the `IRepository.RetrieveStatus` extension method) on Windows it crashes with an AccessViolationException (on the `IRepository.RetrieveStatus` extension method). 
This happens because I have .Net 5 installed on both machines, I created a patched version of my tool with the .Net 5 target removed and it behaved as expected (but running on .Net Core 3.1).

### Version of LibGit2Sharp (release number or SHA1)

I used version v0.26.2 (latest at time of writing) 

### Operating system(s) tested; .NET runtime tested

Mac&Windows -> .Net 5 has an issue, .Net core 3.1 does not.

**Comment by bording** [comment]
This is fixed in the latest preview release.

**Comment by joost-morsink** [comment]
Okay, I will test this in the morning, and will upgrade to release package as soon as available and possible. Thanks for the quick reply!

**Comment by bording** [comment]
> Okay, I will test this in the morning, and will upgrade to release package as soon as available and possible. Thanks for the quick reply!

You should probably just use the preview package. There's not a lot of activity on this repo at this point, so there's no plan for for a release package.

**Comment by joost-morsink** [comment]
oh... not even a patch (0.26.3)?

**Comment by joost-morsink** [comment]
Looks good. I still am not a fan of depending on preview packages, though.
