### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pde-cds** [libgit2/libgit2sharp#1943]
Are there any plans for new releases?
There are a lot of improvements and fixes in libgit2 1.3.0 which could be usefull

**Comment by ethomson** [comment]
Selfishly, I hope so @pde-cds!  I think that there's a lot of goodness in v1.3.0 - in fact there's a v1.4.0 right around the corner - and I'd love to see a new "official" release of LibGit2Sharp!

**Comment by bording** [comment]
The preview releases are based on on 1.3.0 already, so it is possible to use LibGit2Sharp with 1.3.0 already.

I do want to put out a non-preview release, but I need to find the time to get things ready, for example, the changelog needs to be updated.

**Comment by hoerup** [comment]
@bording any update on a new release ?

**Comment by bording** [comment]
LibGit2Sharp v0.27 has been released on [nuget.org](https://www.nuget.org/packages/LibGit2Sharp/0.27.0).
