### ISSUE TITLE
When is the release 0.27.0?

### ISSUE THREAD

**Issue by ww898** [libgit2/libgit2sharp#1983]
Hi, the release version 2.0.315 of LibGit2Sharp.NativeBinaries is ready. When we can expect the release version 0.27.0 of LibGit2Sharp?

**Comment by codewing** [comment]
I would also love to see a release since the 0.27 preview contains fixes that make it possible to run my tool on Linux which the current version doesn't

**Comment by bording** [comment]
LibGit2Sharp v0.27 has been released on [nuget.org](https://www.nuget.org/packages/LibGit2Sharp/0.27.0).
