### ISSUE TITLE
libgit2sharp published for linux-x64 doesn't work on Fedora.

### ISSUE THREAD

**Issue by tmds** [libgit2/libgit2sharp#1985]
Applications that use `libgit2sharp` work on Fedora if they are published for no rid, or when they are published for a Fedora rid (e.g. `fedora.36-x64`).

The don't work when they are published for the _"portable"_ `linux-x64` rid:

```
 dotnet new console -o console
 cd console
 dotnet add package libgit2sharp
 dotnet publish -r linux-x64
```
The native library that gets included for the `linux-x64` build doesn't work on Fedora:
```
ldd bin/Debug/net6.0/linux-x64/publish/libgit2*.so
	linux-vdso.so.1 (0x00007ffd93ca0000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe1d3da3000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe1d3d9e000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007fe1d37fe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe1d3dbb000)
```

cc @bording @omajid

**Comment by bording** [comment]
@tmds Which version of LibGit2Sharp are you using? The latest previews should should have this problem.

**Comment by tmds** [comment]
I was using `0.26.2`. When I switch to `0.27` preview build, this is working.

Thanks!
