### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by mario881** [libgit2/libgit2sharp#1987]
there is a date for new version?

thanks

**Comment by ethomson** [comment]
I'd like to see one, too. @bording do you have any interest in publishing a new release proper? I'm happy to do it if you're busy.

**Comment by bording** [comment]
@ethomson Do you think you could spend some time of figuring out https://github.com/libgit2/libgit2sharp/pull/1957? That's where I got stuck and then just haven't had the time to get back to it.

I wanted to get that merged before trying to do a new release.

**Comment by Miepee** [comment]
Something that should be looked into before doing a release would also be to fix the crashes on linux. Not sure if they're related to the PR you mentioned above, but I'm encountering #2003 and #1994 regularly.

**Comment by bording** [comment]
LibGit2Sharp v0.27 has been released on [nuget.org](https://www.nuget.org/packages/LibGit2Sharp/0.27.0).
