### ISSUE TITLE
Changelog of preview nuget builds?

### ISSUE THREAD

**Issue by Miepee** [libgit2/libgit2sharp#1988]
After the release of 0.26.2, several 0.27 [prerelease nuget versions have been published](https://www.nuget.org/packages/LibGit2Sharp/0.27.0-preview-0182).
However, I cannot find a changelog for them on the nuget site, nor on the release site here, nor in the changes file in this repo.
Is there a public changelog for those versions? I can't even check out all the commits, as none of the commits are tagged with prereleases.
If I am on 0.26.2, do I have any reason to upgrade to the preview versions? Or would it be better to wait until #1983 is solved?

**Comment by bording** [comment]
LibGit2Sharp v0.27 has been released on [nuget.org](https://www.nuget.org/packages/LibGit2Sharp/0.27.0).
