### ISSUE TITLE
Push my commit

### ISSUE THREAD

**Issue by AndreZila01** [libgit2/libgit2sharp#1993]
I try make a commit and push in same function but, the program cannot do a push. I see the commit in github desktop, but program doesn't push the commit and return this errors:
![image](https://user-images.githubusercontent.com/56931353/198409232-12ccabe4-2828-4e58-95f6-0a80206cd7c5.png)

My code at the moment is this:
```
string directory = @"REPOSITORY";
	using (var repo = new Repository(directory))
	{
		// Create the committer's signature and commit
		LibGit2Sharp.Signature author = new LibGit2Sharp.Signature("USERNAME", "EMAIL", DateTime.Now);
		LibGit2Sharp.Signature committer = author;

		// Commit to the repository
		Commit commit = repo.Commit("MESSAGE COMMIT", author, committer);
	}

	using (var repo = new Repository(directory))
	{
		Remote remote = repo.Network.Remotes["origin"];
		var options = new PushOptions();
		options.CredentialsProvider = (_url, _user, _cred) =>
			new UsernamePasswordCredentials { Username = "USERNAME", Password = "PASSWORD" };
		repo.Network.Push(remote, @"refs/heads/master", options);
	}
```

**Comment by ethomson** [comment]
Your username and password are not being accepted by the remote.

**Comment by AndreZila01** [comment]
Ehn ok and how i make to repository will accepted my user?
I need do a git remote??

**Comment by AndreZila01** [comment]
Ehn, ok @ethomson and how i make to repository will accepted my user?
I added my account to "Contributors" on repository and do pushed on git cmd and worked, when i try do on program returned the same error.

**Comment by ethomson** [comment]
What hosting provider? Most providers don't let you use http basic with your username and password and instead require you to create an auth token. Use *that* as your password.

**Comment by AndreZila01** [comment]
OHHHH ok thanks. Now i understand ethomson. Thanks for helped!
