### ISSUE TITLE
Clone set proxy

### ISSUE THREAD

**Issue by Arnaud-17** [libgit2/libgit2sharp#2018]
### public static void Clone()
        {
            var url = @"https://github.com/repo.git";
            var path = "C:\\temp\\GitSharpTest";

            var co = new CloneOptions();
            co.CredentialsProvider = (_url, _user, _cred) => new UsernamePasswordCredentials { Username = "Username", Password = "Password" };

            Repository.Clone(url, path);
        }

**Comment by DUWENINK** [comment]
the same as to me ,

**Comment by bording** [comment]
LibGit2Sharp 0.29.0 has been released, which [adds proxy options](https://github.com/libgit2/libgit2sharp/pull/2065) to make proxies fully configurable.
