### ISSUE TITLE
Repository.Worktrees.Add leaves now worktree empty

### ISSUE THREAD

**Issue by AArnott** [libgit2/libgit2sharp#2037]
Somewhere in the 0.27.0-preview-0182 to 0.27.2 range, LibGit2Sharp broke creation of work trees. 

### Reproduction steps

Given a `Repository` object that points to a valid git repo with at least 2 commits in its history,
call `Repository.Worktrees.Add("HEAD~1", "myworktree", "../somePath", isLocked: false);`

See this [test method](https://github.com/dotnet/Nerdbank.GitVersioning/blob/942ba6d1baa48510122d6ad39e179d7e0401916b/test/Nerdbank.GitVersioning.Tests/VersionOracleTests.cs#L594-L624) for a full repro.

### Expected behavior

The worktree directory is created with a `.git` file and all files from the ref/commit that was specified when it was created.

### Actual behavior

The worktree directory is created with a `.git` file in it, but otherwise it is empty.

### Version of LibGit2Sharp (release number or SHA1)

0.27.0-preview-0182

### Operating system(s) tested; .NET runtime tested

Windows
Fails on .NET Framework 4.8 and .NET 7.

**Comment by barry-bvl** [comment]
Is there any update on this issue?

**Comment by enriqueraso** [comment]
@bording, @AArnott  Any updates on this issue? 0.26.2 is the last release that creation of a worktree worked fine. I already tested with 0.30.0 and 0.29.0

**Comment by ethomson** [comment]
Thanks for the investigation @enriqueraso - this needs a fix in LibGit2Sharp.

**Comment by ethomson** [comment]
(IIUC that is - I think that the default opts structure for worktrees is wrong.)

**Comment by enriqueraso** [comment]
@ethomson ok, I will create a PR for it

**Comment by enriqueraso** [comment]
@ethomson @AArnott @bording, I created this PR https://github.com/libgit2/libgit2sharp/pull/2099 but I cannot assign you as reviewers.

**Comment by bording** [comment]
Fixed by #2099

**Comment by enriqueraso** [comment]
Thank you guys :)
