### ISSUE TITLE
Exception: repository path not owned by current user 

### ISSUE THREAD

**Issue by fellsoft** [libgit2/libgit2sharp#2039]
I have a Windows server application that runs as a system user (non-interactive, no home directory etc) that accesses a git repository using libgit2sharp. Code that was working with v0.26.2 breaks in v.0.27.0 & later.

The application breaks when creating a Repository object at this point:

using (Repository repo = new Repository(pathToRepo));

with exception:

LibGit2Sharp.LibGit2SharpException: repository path '[path]' is not owned by current user

Code works fine prior to v.027.0.

The process definitely has full access to the repository location (e.g. can write files).

I've seen various references to this error in relation to libgit (e.g. https://github.com/libgit2/libgit2/issues/6279)

They recommend adding a git config setting like this:
[safe]
	directory = *

I've manually added this to the repository config file (.git\config) but the exception still occurs.

Am I missing something or is this a bug? Should I be adding the setting somewhere else, and if so, where (given this is a system user)?

**Comment by fellsoft** [comment]
After further testing & research, it seems the only way to get this setting recognised is to add it to the [ProgramFiles]\Git\etc\gitconfig file.

**Comment by fellsoft** [comment]
Further note: if git is not installed, the setting will be read from
[ProgramData]\Git\config

**Comment by 13xforever** [comment]
Why is this issue closed? The library clearly ignores standard global gitconfig settings and breaks when the standalone git works.

**Comment by fellsoft** [comment]
A fix for the issue was added to libgit2sharp v0.31.0, see https://github.com/libgit2/libgit2sharp/pull/2093

You can now do this:
GlobalSettings.SetOwnerValidation(false);

**Comment by 13xforever** [comment]
This is a workaround requiring changes to the code, I can't modify 3rd-party apps that use this library, and it ignores the git settings set by the user in user global config, again requiring manual manipulations with non-standard per-machine configs instead.

**Comment by ethomson** [comment]
What version of libgit2sharp are you (they) using? This functionality has existed in the library for years.

**Comment by 13xforever** [comment]
It's hard to tell as it's merged in one executable, but I think it's 0.31.0.
What do you refer to by "this functionality" though? The ability to disable the check, or the support for standard global git config file settings.
All I want from lib2git library is to follow the same settings as the official git command does, so there's no unexpected behavior discrepancy when I use git and when I use tools using lib2git on the same repository.

**Comment by ethomson** [comment]
Both. libgit2 should honor `safe.directory = *` but safe directory handling is a bit of a... strange beast so there are certainly corner cases both in git and libgit2. I'll try to take a look at libgit2sharp today.

**Comment by gitfool** [comment]
I'm hitting this issue with libgit2 used via [GitTools/GitVersion](https://github.com/GitTools/GitVersion) to build [gitfool/Cake.Dungeon](https://github.com/gitfool/Cake.Dungeon). This is building a few combinations on linux, mac, windows & via docker, on both Azure Pipelines and GitHub Actions, but only fails in the one case when run via docker on GitHub Actions; e.g. [PR113](https://github.com/gitfool/Cake.Dungeon/actions/runs/19777929237/job/56673555332?pr=113) fails the cake build [step](https://github.com/gitfool/Cake.Dungeon/actions/runs/19777929237/job/56673555332?pr=113#step:5:24) with:
> Executing: /__w/Cake.Dungeon/Cake.Dungeon/tools/dotnet-gitversion -output json -verbosity Verbose
ERROR [25-11-29 2:53:06:50] An unexpected error occurred:
LibGit2Sharp.LibGit2SharpException: repository path '/__w/Cake.Dungeon/Cake.Dungeon' is not owned by current user
Error: GitVersion: Process returned an error (exit code 1).

Despite the following in the checkout source [step](https://github.com/gitfool/Cake.Dungeon/actions/runs/19777929237/job/56673555332?pr=113#step:3:34) before it:
> Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /__w/Cake.Dungeon/Cake.Dungeon
