### ISSUE TITLE
`LibGit2SharpException` when cloning repository within a Docker container

### ISSUE THREAD

**Issue by simple0x47** [libgit2/libgit2sharp#2067]
### Reproduction steps
Running the following code within a Docker container:
`Repository.Clone(_config["GitDownloader:Repository"], path, _cloneOptions);`

### Expected behavior
Cloning the specified repository correctly.

### Actual behavior
Throws a `LibGit2SharpException` exception whose stack trace is the following one:
```at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 172
at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 793
```

### Version of LibGit2Sharp (release number or SHA1)
0.28.0

### Operating system(s) tested; .NET runtime tested
Works properly on MacOS 14.1.1 with .NET 8.0
Doesn't work on mcr.microsoft.com/dotnet/aspnet:8.0 container with .NET 8.0

**Comment by bording** [comment]
What is the actual exception error message?

My guess for the problem is that the way you are creating the docker image is resulting in the correct native binaries not being included in the image.

**Comment by simple0x47** [comment]
I forgot to mention that the exception's message is the following one: `Object reference not set to an instance of an object.`

**Comment by simple0x47** [comment]
The way I am building the docker image is by taking the complete build directory and copying it into the Docker build using the command `COPY`.

**Comment by bording** [comment]
> I forgot to mention that the exception's message is the following one: Object reference not set to an instance of an object.

Based on that, I would check and see if the way you obtaining the values you're passing into `Repository.Clone` is working when you're running from inside your container. Sound like you're passing a null value in.

**Comment by simple0x47** [comment]
I tried executing the code on a Linux machine and it seems to be throwing the same exception.

**Comment by bording** [comment]
At this point I'd really need more to go on to be able help further. If you could provide a repo that has a sample project that to reproduce the issue, that would be perfect.

**Comment by simple0x47** [comment]
In the end it seems it was due to a missing environment variable by my side which didn't full fill the CloneOptions correctly. So there's nothing wrong with libgit2sharp! Sorry for that!

**Comment by bording** [comment]
Glad to hear you figured it out!
