### ISSUE TITLE
The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception: Unable to load shared library 'git-106a5f2'.

### ISSUE THREAD

**Issue by afkhan517** [libgit2/libgit2sharp#2125]
I am currently using the LibGit2Sharp library for Git operations in my .NET 6 application, and it works as expected. However, after upgrading to .NET 8, I am encountering the following error:

The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception: Unable to load shared library 'git-106a5f2'.

Environment:
LibGit2Sharp Version: 0.26.2
.NET Version: 8.0

Steps to Reproduce:
Upgrade the project from .NET 6 to .NET 8.
Attempt to perform any Git operation using LibGit2Sharp.
Observe the error message.

Expected Behavior:
The library should function correctly without throwing any exceptions after upgrading to .NET 8.

Actual Behavior:
An exception is thrown indicating that the shared library git-106a5f2 cannot be loaded.

**Comment by bording** [comment]
You're using a very old and outdated version of LibGit2Sharp. Update to the latest version and it should work fine with .NET 8.

**Comment by afkhan517** [comment]
Hey @bording , 

Thank you for your prompt reply. I updated the LibGit2Sharp library to the latest version available on NuGet, **0.30.0**, but I am encountering the following error:

LibGit2Sharp.LibGit2SharpException: The SSL certificate is invalid
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) in /_/LibGit2Sharp/Core/Ensure.cs:line 154
   at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts) in /_/LibGit2Sharp/Core/Proxy.cs:line 278
   at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options) in /_/LibGit2Sharp/Repository.cs:line 824

The exception occurs during the repository cloning process, and here’s the relevant code I am using:

var cloneOptions = new CloneOptions()
{
    BranchName = string.IsNullOrEmpty(checkoutBranch) ? "Main" : checkoutBranch,
    Checkout = true,
    FetchOptions = {
        CredentialsProvider = _credentialsHandler
    }
};


I am building the project through AWS codebuild :

![image](https://github.com/user-attachments/assets/7945a4c3-692c-4d53-92d2-f8aa2332bdd0)


I would greatly appreciate any suggestions you might have, as I’m currently stuck on this issue.

Thank you!

**Comment by bording** [comment]
> The exception occurs during the repository cloning process, and here’s the relevant code I am using:

What repository are you cloning? What logic is in `_credentialsHandler`?

**Comment by afkhan517** [comment]
What repository are you cloning?
>> I'm cloning my own private repository.

What logic is in _credentialsHandler?
>> It contains only the username and password.

Code with **.net8**

var cloneOptions = new CloneOptions()
{
  BranchName = string.IsNullOrEmpty(checkoutBranch) ? "Main" : checkoutBranch,
  Checkout = true,
  FetchOptions = {
  CredentialsProvider = _credentialsHandler
  }
};

Code with **.net6**

var cloneOptions = new CloneOptions()
{
  BranchName = string.IsNullOrEmpty(checkoutBranch) ? "Main" : checkoutBranch,
  Checkout = true,
  CredentialsProvider = _credentialsHandler
};


One thing to note here : **The code works fine while building and running it using .net6**

**Comment by OddQuesadilla** [comment]
I am also having the same problem as described here. My code was originally .NET 6, recently upgraded to .NET 8. Even after updating to .NET 8 I can run the code locally fine (Windows 11) and there are no issues, however when I upload my code to an AWS Lambda I encounter the exact same exception as @afkhan517. 

My clone options look like the following:

```
new CloneOptions
    {
        FetchOptions =
        {
            CredentialsProvider = (_, _, _) => new UsernamePasswordCredentials { Username = "default", Password = pat }
        }
}
```

Let me know if I can provide any more details to help diagnose the issue.

**Comment by AbdulFahimKhan** [comment]
Hey @OddQuesadilla Have you found any solutions for it?

**Comment by afkhan517** [comment]
Hey @OddQuesadilla  Have you found any solutions for it?

**Comment by OddQuesadilla** [comment]
@afkhan517 No I haven't. For the moment we have rolled back our lambda to .NET 6 to keep it functional.

**Comment by afkhan517** [comment]
I've finally resolved the issue. The solution is to disable the SSL check. Below is the code I used, which worked fine for me—you can give it a try as well. I'll go ahead and close the issue now.

![image](https://github.com/user-attachments/assets/eb2fb211-b484-453d-9f12-b562ba9bdd8b)
