### ISSUE TITLE
Shallow clone support

### ISSUE THREAD

**Issue by dougrathbone** [libgit2/libgit2sharp#229]
Hi there 

I was hoping for support for `git  clone --depth 1` so that we can support init'ing repos without all the history data.

I'd be happy to have a go but am totally new to the project (as in, 5 mins new)

**Comment by burdges** [comment]
Appears the recent discussion is here : https://github.com/libgit2/libgit2sharp/issues/229

**Comment by litetex** [comment]
This issue is now nearly 8 years old. 
The corresponding issue at https://github.com/libgit2/libgit2/issues/3058 is 5 years old. 

Will this get implemented soon? 
Is there any new information?
(libgit2 has [a open PR](https://github.com/libgit2/libgit2/pull/5254), but there is currently no progress / was forgotten?; however when it is implemented in libgit2, it must still get implemented here to make it finally working, but I have no idea how long that would take)

In my use-case I just want to use ``git fetch --prune --unshallow`` but with the API 😄

**Comment by tschissler** [comment]
Any progress on this issue?

**Comment by PGoodeBDO** [comment]
Is this on the horizon?

**Comment by shaybenh7** [comment]
any progress here guys? this ticket is 11 years old

**Comment by hoerup** [comment]
With this merged https://github.com/libgit2/libgit2/pull/6396, then it should be feasable to add to libgit2sharp

**Comment by painhardcore** [comment]
Legendary 🥇

**Comment by DUWENINK** [comment]
wait 11 years

**Comment by RyanGaudion** [comment]
🤷‍♂️ bump and +1 here.

@bording with https://github.com/libgit2/libgit2/pull/6396 merged - please can we make this a high priority? It will provide significant performance benefits for a range of use-cases

**Comment by hoerup** [comment]
https://github.com/libgit2/libgit2/releases/tag/v1.7.0 

libgit2 has made a new release including the shallow clone feature

**Comment by Regenhardt** [comment]
@dougrathbone It's been a few years but as you now have 11 experience with this repository, would you reimplement your initial changes with shallow cloning now available in libgit2?

**Comment by AlessandroLenzo** [comment]
Is this supported now or not? Not clear from here. Any code sample? Any documentation?
Please let us know, thanks.

**Comment by Regenhardt** [comment]
libgit2sharp does not support shallow cloning yet. Anyone is invited to implement it in a pull request although I do not know how much time the maintainers take for this repository lately, it seems there was very little activity the last few months.

**Comment by hoerup** [comment]
@bording is it correct to assume that this ticket is solved with https://github.com/libgit2/libgit2sharp/pull/2066/commits/cd6936506ca7808c2fab7454fe5df95c99188d2d ??

**Comment by bording** [comment]
@hoerup No, that just adjusts the format of the internal struct so that the interop continues to work. For now, I've just hardcoded it to always be a full fetch, same as it's always been.

There would need to be more work done to enable shallow clones.

**Comment by omdathetkan** [comment]
Shallow cloning would be amazing..,

**Comment by dayadam** [comment]
This can be achieved with `cloneOptions.FetchOptions.CustomHeaders = new string[] { "git-clone-depth: 1" };`
