### ISSUE TITLE
Getting a compatible git branch name from a given string

### ISSUE THREAD

**Issue by pmiossec** [libgit2/libgit2sharp#244]
For a development in the project git-tfs, I need to create automaticaly branches for each Tfs branches.

I want to create a git branch from the name of the tfs one.

That's why I need from a string (the tfs branch name) to determin the compatible git branch the name the nearer possible like what's done with the command :
git check-ref-format--branch myExpectedStringName

Is it possible to do it?

**Comment by TheSavior** [comment]
Long dead thread, but I came across this when searching on Google. I have created an npm module to support converting a string to a valid git ref name. For those that might come across this post in the future, perhaps this is what you are looking for: https://github.com/TheSavior/clean-git-ref
