### ISSUE TITLE
Repository.Clone doesn't support SSH

### ISSUE THREAD

**Issue by JustinBeckwith** [libgit2/libgit2sharp#255]
When performing a Repository.Clone against an SSH uri, it fails with the following message:

An error was raised by libgit2. Category = Net (Error).
This transport isn't implemented. Sorry

I'm guessing this just isn't implemented in libgit2 yet, though it looks to be on its way:
https://github.com/libgit2/libgit2/pull/1103

**Comment by yannisgu** [comment]
The WIP mentioned by @nulltoken is now implemented: https://github.com/libgit2/libgit2/pull/2600

Should be a bit eeasier now to implement it..

**Comment by nulltoken** [comment]
Related #771 and #852

**Comment by dannyzhan** [comment]
Guys, is ssh still not supported in libgit2 and libgit2sharp, right?
I really need ssh support, it's more secure than http.

**Comment by nulltoken** [comment]
@dannyzhan See my answer to your very similar question in https://github.com/libgit2/libgit2sharp.nativebinaries/issues/7

**Comment by CumpsD** [comment]
Which issue exactly is the main one now to follow progress of SSH implementation? https://github.com/libgit2/libgit2sharp/pull/1072?

Trying to figure out the current state to fetch repo's using an SSH key (used as deployment key in github)

**Comment by carlosmn** [comment]
libgit2 and libgit2 do support SSH. The libgit2 we ship does not, as we do not want to ship 3rd-party crypto software in our packages.

**Comment by mback2k** [comment]
@carlosmn If libgit2 already requires libssh2 to use ssh, then you do not need to shop an additional 3rd-party crypto software in your package, since libssh2 now has native Windows support using WinCNG.

**Comment by ethomson** [comment]
I think _libssh2_ is the third-party crypto that he was referring to.

**Comment by carlosmn** [comment]
Yes. While the cryptographic primitives are implemented by OpenSSL or
Windows, libssh2 is still crypto code and packaging that means having to
keep up with its releases and security updates.

And on UNIX we want to use the system libraries, but that would make the
nuget package not be self-contained anymore.

dload/GetProcAddress is an alternative to linking directly, but nobody has
done the work to make that work.

**Comment by ckuhn203** [comment]
I'm a little confused about the state of this issue. Is the ssh protocol supported for windows?

**Comment by ethomson** [comment]
@ckuhn203 Not out of the box, you have to build it and link it yourself.

**Comment by ckuhn203** [comment]
Got it. Thanks @ethomson.

**Comment by smuda** [comment]
@ethomson is there some documentation how to do that?
