### ISSUE TITLE
Better way to identify conflict in a status

### ISSUE THREAD

**Issue by yishaigalatzer** [libgit2/libgit2sharp#271]
When Calling Index.RetrieveStatus(path) and the underlying file is in a conflict state the returned value is currently multiple flags.

This behavior is changing from version to version and a bit hard to code reliably against.

It would be beneficial to consider a FileStatus.Conflict and return it in this case.

**Comment by ethomson** [comment]
This is stale and we've got conflicts now.  Whee!
