### ISSUE TITLE
Make a PreRelease Nuget package version available

### ISSUE THREAD

**Issue by theluk** [libgit2/libgit2sharp#273]
1. edit file "test.txt"
2. make a commit (1st commit)
3. edit file "test.txt" again
3 make a commit (1st commit)

if you now use "git checkout 1stcommit" you will be in detached head mode but no files are dirty(if all were previously commited)

in libgit2sharp if you do checkout(1stcommit) (sharef) you will be also in detached head mode BUT the files did not change and there are now dirty / did not change to the previous commit

**Comment by nulltoken** [comment]
Superseded by #911 

Cheers!
