### ISSUE TITLE
Resolve conflict without staging

### ISSUE THREAD

**Issue by yishaigalatzer** [libgit2/libgit2sharp#328]
Currently libgit2sharp allows resolving conflict implicitly only by staging/adding a file. However an explicit method is required as well (example scenarios below).

It would be super nice to support the following
1. Resolve conflict for a specific file in one of the following ways:
1.a Keep file with markers on disk (or even nicer have a marker detection logic built in - though not necessary) and resolve the conflict.
2. Grab theirs or yours version and resolve the conflict

After resolving the conflict none of the results is staged, and the user can keep editing from that stage.

Since we can obviously resolve conflicts today using stage/add I'm assuming there is a private method in libgit2 to allow resolving the conflicts explicitly.

Example Scenarios:
1. I am working on a piece of code, and one of my team mates added some resources I want to use. My code is not ready to commit (nor I want to have a commit with broken code), so I want to pull from origin. Integrate the new resources and just keep working.
2. I'm doing a pull from origin, and in my tree view conflicts show up. The markers break my code from running although these are all pretty simple things to fix. I just want to "fix" the conflict and continue working.

So for my case I'm looking at building a conflict merge flow, that does not require commit at the end. Of course I can hack it today by calling stage, then unstage but that is just an awful practice.

**Comment by ethomson** [comment]
Conflict resolution is - by definition - staging something.  There's no way to remove a conflict without staging some change.
