### ISSUE TITLE
Following example repo fails in status result & branch switching

### ISSUE THREAD

**Issue by yishaigalatzer** [libgit2/libgit2sharp#340]
Version taken from 2/18/2013 libgit2sharp vNext branch

See example zipped repo:
https://github.com/yishaigalatzer/BranchCheckoutAndStatusFail/blob/master/Branched.zip

status will return modified for one of the files, but CLI returns (correctly) unchanged.
branch checkout fails in libgit2sharp but not in CLI.

To create this repo:

Use libgit2sharp for all actions unless CLI is specified.

Init an empty folder
Drop a text file 
stage and commit 
Create a new local branch
Checkout the branch
Drop a second text file

OPEN CLI
{CLI}git add -A
{CLI}git commit -m "message"

Back to libgit2sharp
checkout the original master branch (FAIL)

This is the first and more critical issue.

Now zip up the folder (which I was doing just to get a neat repro example)
Extract all the files to another folder

Get Status from libgit2sharp (the second file shows up as modified)
{CLI}git status -> no changes detected
Back to libgit2sharp (the second file shows as no changes)

Branch checkout still does not work

** Comment: I don't always see the branch checkout fail. I haven't figured out when it doesn't but having a CLI window open in the folder helps to make it fail

**Comment by carlosmn** [comment]
We've had a ton of fixes around the workdir which should have taken care of all of this. If there are issues, it's bound to be a brand new bug, so I'm closing this report.
