### ISSUE TITLE
Encoding issue with commit name

### ISSUE THREAD

**Issue by Haacked** [libgit2/libgit2sharp#387]
Not sure if this is a LibGit2 or LibGit2Sharp bug but thought I'd start here. :)

Try cloning this repository here: https://github.com/CoolDevs/Mets-palopeli

```
git show d527f20
```

Shows the author as: Lassi Hämäläinen

But if you load the commit in LibGit2Sharp, you get: Lassi H�m�l�inen

Phil

**Comment by Haacked** [comment]
> @Haacked Do you have two cloned repositories? I see that some commits have good encoding and some have bad. It is weird as they are commited in short time span with good and bad encoding.

Sorry I missed this all these years. :stuck_out_tongue: 

This is not my repository, so I don't know much about the context for why there are good and bad commits.

**Comment by ethomson** [comment]
We talked about this in-person at Git Merge 2015 (wow, this issue is old) and decided that we would not try to do any fallbacks, as they would almost always be incorrect on the host machine.
