### ISSUE TITLE
Local Repository.Clone performance is terrible

### ISSUE THREAD

**Issue by powercode** [libgit2/libgit2sharp#403]
Hi,
I'm using libgit2sharp to write PowerShell cmdlets for git.

I am running into problems with Repository.Clone/git_clone: It is dog slow. On a repository where git clone takes about a second, Repository.Clone takes over two minutes.

This is happening when cloning a local repo on an SSD drive.
 
Looking with process monitor, I get loads of 
 
01:35:48,8113026  Powershell.exe CreateFile  ...\libgit2sharp\.git\objects\6a\2d99ecdf35288df88c0e6fe8985969042d82a6      PATH NOT FOUND  Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

01:35:48,8115033  Powershell.exe CreateFile  ...\GitHub\libgit2sharp\.git\objects\6b\b488fee8a87c9234facf29301f78e38b9251e2  PATH NOT FOUND Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
 
There are no files under .git\objects, it seems like everything is in 
 
.git\objects\pack\pack-26a89e060e3ded2c7127d832f055c5c96dfe093f.idx
.git\objects\pack\pack-26a89e060e3ded2c7127d832f055c5c96dfe093f.pack
.git\objects\pack\pack-4bf1c2bd03f29feff47fe019abcace0431d6b89b.idx
.git\objects\pack\pack-4bf1c2bd03f29feff47fe019abcace0431d6b89b.pack

Here's what it looks like in a performance analysis:

![GitClone](https://f.cloud.github.com/assets/3505151/400634/556146e8-a8b5-11e2-87e9-9b76d28d1c9f.PNG)

**Comment by nulltoken** [comment]
Related https://github.com/libgit2/libgit2/issues/2836#issuecomment-82734390

**Comment by carlosmn** [comment]
And also libgit2/libgit2#3120 which swaps the priorities, and everything mentioned in libgit2/libgit2#2836

**Comment by carlosmn** [comment]
We now perform local "clones" when git would, and for actual clones we activate multiple threads, so performance has gotten better. There's libgit2/libgit2#2836 to track we still haven't ported some optimisations from git. I'm closing this as the source this this issue has been resolved.
