### ISSUE TITLE
Make potentially long running operations cancelable

### ISSUE THREAD

**Issue by powercode** [libgit2/libgit2sharp#404]
When using libgit2sharp from PowerShell, there is a frequent need to be able to cancel operations (user pressing Ctrl+C).

Having a mechanism like System.Threading.CancellationToken/CancellationSource would be very helpful.

The only other option that I can think of to safely accomplish the same thing is by spawning the long running operations in new processes, but that seems like overkill.

I know that I can cancel for example Repository.Clone by returning -1 from the TransferProgress handler, but when it takes 90 seconds before I get the first callback, it is not really a solution.

**Comment by carlosmn** [comment]
This is tracked in libgit2/libgit2#3334
