### ISSUE TITLE
Improve behaviour of Index.Remove()

### ISSUE THREAD

**Issue by yorah** [libgit2/libgit2sharp#411]
While implementing #398, some area for improvements were highlighted:
- [ ] Add support for the `git rm -f` semantic
- [ ] ~~~Handle `TypeChanged` records (make sure `Index.RetrieveStatus(string)` correctly reports it)~~~
- [x] Make it so that conflicts clearing through `Index.Remove()` work for files which don't exist in the workdir (see comment of `ConflictFixture.CanClearConflictsByRemovingFromTheIndex()` test)

**Comment by ethomson** [comment]
Moved the typechange information to #1016.

**Comment by carlosmn** [comment]
We do have tests to unstage modified files, so number 1 is also done. the typechange is tracked in a different issue, so closing.
