### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by ChuckSavage** [libgit2/libgit2sharp#44]
I've successfully created a Repository:

UriAgility gitUri = UriAgility.Parse("~/App_Data/SCommunity/wikiRepo/.git");
if (!gitUri.FileInfo.Directory.Exists)
    Repository.Init(gitUri.FileInfo.DirectoryName);

using (var repo = new Repository(gitUri.PhysicalPath))
{       
    HttpContext.Current.Response.Write(string.Format("Working directory: {0}<br />", repo.Info.WorkingDirectory));
    HttpContext.Current.Response.Write(string.Format("Repository path: {0}<br />", repo.Info.Path));

  ...
What do I put here to Add file to the repository?
What do I do to get the file once it is in?
How do I get the diff between versions?
  ...
}

**Comment by carlosmn** [comment]
An emulation of the file history support was implemented in #963
