### ISSUE TITLE
The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.

### ISSUE THREAD

**Issue by joaoferreira** [libgit2/libgit2sharp#446]
I'm build a Windows Form application and each time I try to make a clone of a repository I get this error The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. without any further detail.

Anyone knows what could be causing this, I'm getting crazy trying to figure it out.

**Comment by DavidHooper** [comment]
In case anyone comes across this again. Here is how I solved the issue of native binaries not being copied across.

Have a project property file that references LibGit2Sharp
LibGit2Sharp.props
```XML
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <None Include="path-to\git2-e0902fb.dll">
            <Link>NativeBinaries\amd64\git2-e0902fb.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="path-to\git2-e0902fb.pdb">
            <Link>NativeBinaries\amd64\git2-e0902fb.pdb</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="path-to\x86\git2-e0902fb.dll">
            <Link>NativeBinaries\x86\git2-e0902fb.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="path-to\x86\git2-e0902fb.pdb">
            <Link>NativeBinaries\x86\git2-e0902fb.pdb</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
```

Reference it in your library.
MyProject.csproj
```XML
<Import Project="LibGit2Sharp.props" Condition="Exists('LibGit2Sharp.props')" />
```

In your run project (the main project). Add the following.
MyExecutable.csproj
```XML
<ItemGroup>
    <Content Include="$(OutputPath)\NativeBinaries\**\*.dll">
      <Link>NativeBinaries\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <Visible>false</Visible>
      <PublishState>Include</PublishState>
    </Content>
  </ItemGroup>
```

**Comment by chrisRedwine** [comment]
New user - I created a simple console application in VS2015, installed LibGit2Sharp 0.22.0 via Nuget, and got the same error as above (The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception) when running the following hello world example:

```cs
using System;

namespace GitTest
{
    class Program
    {
        static void Main(string[] args)
        {
            LibGit2Sharp.Repository.Clone(@"https://github.com/libgit2/libgit2sharp.git", @"H:\");
        }
    }
}
```

I wonder why a basic Nuget Install doesn't work for me for this package? None of the above solutions work...

**Comment by bording** [comment]
@chrisRedwine Does your project also include the LibGit2Sharp.NativeBinaries package?

**Comment by chrisRedwine** [comment]
@bording Yes, installing LibGit2Sharp v0.22.0 also installed LibGit2Sharp.NativeBinaries v1.0.129 for me.

**Comment by bording** [comment]
@chrisRedwine Do you have your example online anywhere that I could see if I can repro the problem locally?

**Comment by chrisRedwine** [comment]
@bording Not sure if this will work for you, but I added it as a dummy repo to my profile (https://github.com/chrisRedwine/GitTest), with no gitignore. First commit is before adding LibGit2Sharp, second commit is after. Thanks!

**Comment by bording** [comment]
@chrisRedwine Everything looks fine with that project, and once I adjusted for the non-existent H: drive on my machine, it runs without errors.

**Comment by chrisRedwine** [comment]
@bording Interesting. Well, that's helpful info - thanks so much for looking into it.
