### ISSUE TITLE
Support "git log --path"

### ISSUE THREAD

**Issue by xieyubo** [libgit2/libgit2sharp#463]
Do we support git log --path? It seems there is no path parameter in Filter. Is there another way to implement "git log --path"?

**Comment by carlosmn** [comment]
This functionality was added by #963

**Comment by deepak-arya** [comment]
Hi @carlosmn i tried #963 but could not achieve it. below is what i am doing. can u check if i am doing it correct. help is much appreciated.

public static void GetFileHistory(string filepath,string repopath)
        {
            using (var repo = new Repository(repopath))
            {
// here i am using absolute file path
                IEnumerable<LogEntry> history = repo.Commits.QueryBy(filepath);
//problem is here. it does not go into loop. 
                foreach(LogEntry e in history)
                {
                    Console.WriteLine(e.Commit.Message);
                }
            }
        }

/// here is what i get
GetEnumerator() result view is always null
![image](https://cloud.githubusercontent.com/assets/20082634/16640728/1bcf2ce0-4418-11e6-8ede-448b553be40e.png)
