### ISSUE TITLE
NTFS junctions reported as missing

### ISSUE THREAD

**Issue by ivan-danilov** [libgit2/libgit2sharp#488]
If you have part of the repo as a NTFS junction - it is reported as missing in the `Repository.Index.RetrieveStatus()` results.

For example, `C:\repo` is the root folder of repository, `C:\repo\.git` is present, and there're two subfolders: `C:\repo\A` and `C:\repo\B` with some files in each of them. If you move `C:\repo\B` -> `C:\B` and create NTFS link (e.g. with `junction.exe C:\repo\B C:\B` command using [junction](http://technet.microsoft.com/en-us/sysinternals/bb896768) util from SysInternals suite) - libgit2sharp is reporting that all contents of `C:\repo\B` is missing while it is there.

I'm not sure if this is a problem of Libgit2 or Libgit2sharp actually, but msysgit correctly reports that no changes are there.

P.S. I'm not using the last version - I'm afraid I can't just take one and check right now easily. So I'm sorry if the issue is fixed already, feel free to close it.

**Comment by fantaclaus** [comment]
I have the same issue with the latest version of liblit2sharp (0.26.1) installed with nuget package.

`repo.RetrieveStatus` reports the status of all junction items as `DeletedFromWorkdir`, and the status of the junstion itself as `NewInWorkdir`.

GlobalSettings.Version returns 0.26.1+gd638aa1da1.libgit2-7ce88e6.

`git status` says that there is no changes in working dir.

**Comment by hguy** [comment]
This is still a problem and should be open.
Nuget 0.26.2
Winform Project Framework 4.7.2
Junction added with `MKLINK /J`.

Unfortunately that make the package unusable for me.

#### `git status -suall` can see all files recursively.
![image](https://user-images.githubusercontent.com/31834707/186630148-3cc5a750-1d6f-41ac-9c9d-91deb1b94a28.png)

#### Debug
![image](https://user-images.githubusercontent.com/31834707/186629879-ec16a012-931d-4fa9-ba5b-c9e2417dfc60.png)
