### ISSUE TITLE
Add `Tag.PeeledTarget` property

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#551]
Although quite uncommon, annotated tags may be chained.

It might be handy to also provide the consumer with a shortcut to directly return the recursively peeled target of a `Tag` and make the following test pass

```csharp
[Fact]
public void CanRetrieveThePeeledTargetOfATagPointingToATag()
{
    using (var repo = new Repository(BareTestRepoPath))
    {
        Tag tag = repo.Tags["test"];

        Assert.True(tag.Target is TagAnnotation);
        Assert.True(tag.PeeledTarget is Commit);
    }
}
```

**Comment by bording** [comment]
I know this issue is a bit old, but is this still something you'd think would be useful to have? If so, I'll take a look at adding it.

**Comment by nulltoken** [comment]
>I know this issue is a bit old, but is this still something you'd think would be useful to have?

I think so. Labelled as `in-progress`. Thanks!
