### ISSUE TITLE
Support mirror clone

### ISSUE THREAD

**Issue by Aimeast** [libgit2/libgit2sharp#577]
Hi,

I want a choose that can clone repository with `--mirror`. Maybe this one not supported by `libgit2` yet.

https://github.com/libgit2/libgit2/blob/5bfead1dba919f6b47f52da675ea94407e8baf49/include/git2/clone.h#L48-L58

**Comment by MrTomWhite** [comment]
It looks like #1199 is closed. Can this issue be closed now? @aimeast @nulltoken

**Comment by nulltoken** [comment]
@MrTomWhite Indeed. Thanks for pointing out to this. It's been made available in LibGit2Sharp through https://github.com/libgit2/libgit2sharp/pull/731

Closing this now, then

**Comment by longlostbro** [comment]
It seems, from this series of comments, that someone was able to implement a clone --mirror and a push --mirror

Could someone share example code for that implementation?

**Comment by Myster** [comment]
Here's my SO question and answer (I'm not sure it's 100%) so if anyone wishes to offer corrections that would be great. :-) https://stackoverflow.com/questions/54759264/mirror-a-repo-using-libgit2sharp-or-other-c-sharp-library

**Comment by anrichter** [comment]
> 
> 
> It seems, from this series of comments, that someone was able to implement a clone --mirror and a push --mirror
> 
> Could someone share example code for that implementation?

Hi,

use it in ma GitLabToGitHub migration tool.
You can find an example for clone --mirror in my [GitLabConnector](https://github.com/anrichter/GitLabToGitHub/blob/30534b1671425594db68f85aec0c42abf514d751/GitLabToGitHub/GitLabConnector.cs#L113) class. And an axample for push --mirror is locatet in the [GitHubConnector](https://github.com/anrichter/GitLabToGitHub/blob/30534b1671425594db68f85aec0c42abf514d751/GitLabToGitHub/GitHubConnector.cs#L62) class.

Hope that helps.

Greetings
Andreas
