### ISSUE TITLE
List modified files for a commit

### ISSUE THREAD

**Issue by ghost** [libgit2/libgit2sharp#59]
Hi,
How to, with a specific commit, get a list of modified files?

Thanks

**Comment by ColinNg** [comment]
Hi, I think the original question isn't actually answered. 
The Hitchhiker's guide on [git-log-name-status] (https://github.com/libgit2/libgit2sharp/wiki/git-log-name-status) returns a different list of files than what I get through:
    git log --name-only 0138ef5..899809f
It also takes a LOT longer than git log --name-only (instant) vs. 20.633 seconds. 
I have also tried [StackOverflow](https://stackoverflow.com/questions/36456718/libgit2sharp-get-files-in-all-commits-between-two-tags)
