### ISSUE TITLE
Submodules are incorrectly reported on some branches

### ISSUE THREAD

**Issue by robnasby** [libgit2/libgit2sharp#604]
Scenario:
In a repository, a submodule is added in the DEV branch, but not the PROD branch.  In LibGFit2Sharp v0.14.1.0, submodules are reported regardless of which branch is checked out.  This is contrary to how Git behaves, which only reports the submodule for DEV.

**Comment by jamill** [comment]
I think you will want to check the status on the submodule via `Submodule.RetrieveStatus()` to determine where the submodule exists (.gitmodules, , index, head commit, work dir, etc...)

The current API might not be the clearest, but I don't think we want to change this for the stabilization push.

**Comment by nulltoken** [comment]
There are chances it may be already be fixed. Maybe, some test coverage should however be added.

Labeling it as `up-for-grabs` and dropping the `stabilization` label.

**Comment by dahlbyk** [comment]
> Maybe, some test coverage should however be added.

Brought old repro up to date in #1051 - tests pass locally.
