### ISSUE TITLE
Commit messages are prettified by default when the history is rewritten

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#621]
cf @amibar's findings in #619

 - **Now:** Prevent rewriting of the commit messages and fix the tests so they don't fail because of this.
 - **Later:** Maybe should we find a way to extend `RewriteHistoryOptions` and let the caller control this behavior?

**Comment by ethomson** [comment]
@nulltoken This seems like a bug to me, and / or an additive API change to `RewriteHistoryOptions`...?  I think we can drop the stabilization tag here (but I may not understand this issue fully.)

**Comment by nulltoken** [comment]
> I think we can drop the stabilization tag here (but I may not understand this issue fully.)

Agreed

**Comment by carlosmn** [comment]
We accept the prettify option via the history rewriter options, so the caller is in control. Closing thus.
