### ISSUE TITLE
Test a branch can merge or not

### ISSUE THREAD

**Issue by Aimeast** [libgit2/libgit2sharp#628]
In order to make a opened Git platform like the feature Pull-Request, I proposal introduce a instance method `bool Repository.CanMerge(Commit first, Commit second)` that return true if `second` can merge into `first`, otherwise return false.

**Comment by shiftkey** [comment]
We had this same need recently with GHfW and came up with a different solution - exposing `git_merge_trees` to managed code and resolving both trees (and their ancestor if possible).

If you're still interested in adding this support, I can help bring it across for review.

cc @joshvera
