### ISSUE TITLE
NoMemory exception on fetch

### ISSUE THREAD

**Issue by steamos** [libgit2/libgit2sharp#641]
Been advised by nulltoken to open an issue re: http://stackoverflow.com/questions/22155904/libgit2sharp-nomemory-exception-on-fetch
There's a bit more info on the StackOverflow thread but I'll summarise below.

I seem to be having an issue using fetch with a BitBucket repo over HTTPS, the code I'm using is:

this._repo = new Repository(workingDir);
Credentials credentials = new Credentials() {Username = this._username, Password = this._password};
Remote remote = this._repo.Network.Remotes["origin"];
FetchOptions fetchOptions = new FetchOptions();
fetchOptions.Credentials = credentials;
var branch = @"refs/heads/TestBranch:refs/remotes/origin/TestBranch";
this._repo.Network.Fetch(remote, new string[] { branch }, fetchOptions);

Only the final line it gives the following exception:

An error was raised by libgit2. Category = NoMemory (User).

Out of memory

I've added a public repo (https://bitbucket.org/matthewrouse1/testrepo/overview) or to use with git: htttps: https://bitbucket.org/matthewrouse1/testrepo.git this wasn't the original repo that I used however I have been able to reproduce the problem with.

The reproduction steps are pretty simple:
Initialise repo (create bitbucket, do intiial commit etc)
From libgit2sharp, try to pull using the above code.

**Comment by carlosmn** [comment]
We were never able to reproduce this issue, and the code has changed so much since then that even if we did, a fix wouldn't make sense.
