### ISSUE TITLE
Consistent signature/logMessage usage

### ISSUE THREAD

**Issue by dahlbyk** [libgit2/libgit2sharp#655]
Reflog-writing method signatures (e.g. `BranchCollection.Add()`) should be consistent. The majority of such signatures look like this:

```csharp
   public void Foo(…, Signature signature = null, string logMessage = null, … = …)
```

However, there are some instances where other overloads' default parameters prevent these default for the reflog-writing version. Ideally that would be consistent.

c.f. https://github.com/libgit2/libgit2sharp/pull/612#discussion_r10769940

**Comment by nulltoken** [comment]
@dahlbyk Now that @shiftkey killed the default parameters, are there any remaining things to work on wrt this topic?

**Comment by dahlbyk** [comment]
It looks like https://github.com/libgit2/libgit2sharp/pull/965 removed most reflog-writing signatures, leaving only methods in `Network` and `ReferenceCollection` that appear to have `logMessage`-less overloads (and none accept a `Signature`). So I guess we're good?
