### ISSUE TITLE
Alternate database implementation

### ISSUE THREAD

**Issue by ericnewton76** [libgit2/libgit2sharp#666]
So I just read that libgit2 C library supports alternative database implementations, are there plans for this?

I ask because I have a business need to store the git object database inside a "proper" database (mysql laugh, or SQLserver, etc) for enabling version tracked assets via Git's style of commit snapshots.

If there's none, I would be interested in building one for SqlServer and possibly forward-porting some of the others already built in C, for MySql, SqlLite, and memcached.

**Comment by Aghlara** [comment]
Any instruction how we can setup and use the existing salute implementation of libgit2 in libgit2sharp? I don't seem to find any documents around?
