### ISSUE TITLE
libgit2 StdCall (/Gz) calling convention

### ISSUE THREAD

**Issue by tritao** [libgit2/libgit2sharp#693]
I've been trying to get an SSL/SSH2 enabled build of libgit2 going on, but unfortunately OpenSSL is pretty hard to compile with `/Gz`. It'd be best if LibGit2Sharp could consume a usual (`cdecl`) build of libgit2.

Is there some specific reason that LibGit2Sharp needs libgit2 to be compiled as `stdcall`?

**Comment by carlosmn** [comment]
We're keeping stdcall. There is no need for OpenSSL for libssh2 to work, so they no longer set the calling convention. If libssh2 does not support stdcall when using Windows crypto that's a bug to be filed with them.
