### ISSUE TITLE
Deleted remote branches remain when Fetch

### ISSUE THREAD

**Issue by sergiodebst** [libgit2/libgit2sharp#695]
When you perform a ```Fetch```, if in the origin have been added new branches, these branches are correctly added to the local Repository, however, if in the origin have been deleted any branches, these branches remain in the local Repository

**Comment by nulltoken** [comment]
Would be partially dealt with through #925.

**Comment by dahlbyk** [comment]
> Would be partially dealt with through #925.

Partially? Looks like `git_remote_prune` was included, too, unless I'm missing something.

**Comment by nulltoken** [comment]
@dahlbyk Is far as I understood it, `FetchOptions.Prune` would be an "on-the-fly" request to prune without altering (or relying on) the configuration. Do I read this wrong?

**Comment by dahlbyk** [comment]
I read the same as you, which is how I understand `git_remote_prune` to work:

> The remote object has learnt to prune remote-tracking branches. If  the remote is configured to do so, this will happen via  `git_remote_fetch()`. You can also call `git_remote_prune()` after  connecting or fetching to perform the prune.

So in addition to the config-related changes proposed by #925, we should be able to support:

* `FetchOptions.Prune { get; set; }`
* `Network.Prune(Remote)`

**Comment by carlosmn** [comment]
`Network.Prune(Remote)` would just be a call to `git_remote_prune()`, but we don't allow setting the option on a `git_remote` as we do not have the code to persist it to disk.

**Comment by nulltoken** [comment]
> [...] we don't allow setting the option on a git_remote as we do not have the code to persist it to disk.

@carlosmn What if we wanted to set it against the in-memory remote? ie. request for this specific `Fetch()` to prune the stale remote tracking branches, without persisting anything to disk?

**Comment by dahlbyk** [comment]
> @carlosmn What if we wanted to set it against the in-memory remote? ie. request for this specific Fetch() to prune the stale remote tracking branches, without persisting anything to disk?

Wouldn't you just call `git_remote_prune`?

**Comment by carlosmn** [comment]
> @carlosmn What if we wanted to set it against the in-memory remote? ie. request for this specific Fetch() to prune the stale remote tracking branches, without persisting anything to disk?

You can't do it.

**Comment by ethomson** [comment]
Dropping the stabilization tag, this can be an additive change to a future version.
