### ISSUE TITLE
staging files with ignored invalid paths raises exceptions 

### ISSUE THREAD

**Issue by shiftkey** [libgit2/libgit2sharp#793]
So here's the setup:

This file path is under `node_modules`, which is specified in the `.gitignore` file for the repository:

```
C:/Projects/GitHub/fiber-verification/node_modules/grunt-contrib-imagemin/
node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/
gifsicle/node_modules/bin-build/node_modules/download/node_modules/
decompress/node_modules/adm-zip/.idea/scopes/scope_settings.xml
```

When staging files multiple changes (two files in different subdirectories seems to be the minimum to trigger this) `libgit2sharp` will pass in the `DiffModifiers.IncludeIgnored` flag:

https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/Index.cs#L157

```
var changes = repo.Diff.Compare<TreeChanges>(
    DiffModifiers.IncludeUntracked | DiffModifiers.IncludeIgnored, paths, explicitPathsOptions);
```

This is mapped to two flags for `libgit2`: `GIT_DIFF_INCLUDE_IGNORED | GIT_DIFF_RECURSE_IGNORED_DIRS`

https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/Diff.cs#L39-L43

And p/invoking `git_diff_index_to_workdir` surfaces this exception:

```
Invalid path for filesystem 'C:/Projects/GitHub/fiber-verification/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/adm-zip/.idea/scopes/scope_settings.xml': The data area passed to a system call is too small.
```

Stack Trace: 

```
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result) 
   at LibGit2Sharp.Core.Ensure.ZeroResult(Int32 result) 
   at LibGit2Sharp.Core.Proxy.git_diff_index_to_workdir(RepositorySafeHandle repo, IndexSafeHandle index, GitDiffOptions options) 
   at LibGit2Sharp.Diff.<>c__DisplayClass5.<WorkdirToIndex>b__4(ObjectId oh, ObjectId nh, GitDiffOptions o) 
   at LibGit2Sharp.Diff.BuildDiffList(ObjectId oldTreeId, ObjectId newTreeId, TreeComparisonHandleRetriever comparisonHandleRetriever, DiffModifiers diffOptions, IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions, CompareOptions compareOptions) 
   at LibGit2Sharp.Diff.Compare[T](DiffModifiers diffOptions, IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions, CompareOptions compareOptions) 
   at LibGit2Sharp.Index.Stage(IEnumerable`1 paths, ExplicitPathsOptions explicitPathsOptions)
```

This is a demo repository which demonstrates the issue (you need to "npm install" to add the ignored folders): https://github.com/agrc/fiber-verification/

**As a workaround**, I've been able to complete staging the files by removing the `DiffModifiers.IncludeIgnored` flag - but this feels like a hack because of the notes mentioned here 885de34f544478ec005dce3d5b5ea5a72d1c7457 cc @ethomson

I'm going to look to recreate this in plain `libgit2` next so I can debug further, as this message makes me think there's something which needs to be addressed in there...

> The data area passed to a system call is too small.

**Comment by bdelaney** [comment]
That workaround does NOT work.
And the connect bug report only has a single workaround. Don't use Git from within VS. Instead use an out of process Git client and the commit should work. Painful.
Microsoft will one day acknowledge this Achille's heel. It rears its ugly head in many cases. What I cannot believe is the windows team does not fix this in Windows 10. Just a complete deal breaker.

**Comment by nulltoken** [comment]
>That workaround does NOT work.

@bdelaney Could you please provide us with a repro case where the workaround doesn't help?

**Comment by ethomson** [comment]
@bdelaney If you have complaints about Visual Studio or Windows, please raise a Connect issue.  This is not the appropriate place for bugs in Visual Studio.

**Comment by tubededentifrice** [comment]
@nulltoken Same here, workaround doesn't work. Nothing more than what was already said, the commit fails the exact same way, with or without the .gitignore file with "*" in the "node_modules" directory.

**Comment by mattmazzola** [comment]
I can also confirm the work around of adding another .gitignore file in node_modules does not resolve the issue.  Still have to do everything from command line.

**Comment by bdelaney** [comment]
@ethomson I learned a lot by this issue discussion. And when I finally did have to deal with the problem, I found that deleting node_modules from the VS project did allow me to finish Git commit.
Apologies for the misplaced comment. And I did visit the Connect pages as well trying to add constructively.

**Comment by shailensukul** [comment]
Just wanted to say thanks to all. I have upvoted the defect and had to resort to deleting the node_modules folder as a workaround.

**Comment by ericis** [comment]
I did the same as @shailensukul.  However, I was able to use the "subst" command to re-root the project directory path to a new drive letter, delete the "node_modules" dir, commit, and then re-add bower/grunt to my project (using npm). Once I re-installed, __I was able to make an edit and commit without getting the error afterward__.  I will continue to see if I can make additional commits or if I get errors and report back!

**Comment by ericis** [comment]
nope. next commit = same error

**Comment by rlamtabbet** [comment]
As stated above, this had to do w/ the path of some of the packages (having lengthy dependencies).
If you are looking for a temporary workaround, In my case, I just used NPM to uninstall the packages that were causing the issue. Committed my change and then installed the packages back. 
- npm uninstall grunt-contrib-imagemin
- npm uninstall grunt-lint-inline

Since I'm running NPM uninstall w/o the --save-dev, The package.json isn't being updated and thus just by running "npm install"  all the missing packages should be added back again.

**Comment by ethomson** [comment]
I'm locking this issue to prevent people piling on with discussion about a bug in Visual Studio that has nothing to do with this issue.

If you have an issue with Visual Studio, please report it to Microsoft, don't report it to a third-party library.

**Comment by carlosmn** [comment]
@ethomson did we end up supporting this in libgit2?

**Comment by carlosmn** [comment]
We now ignoring too-long files when iterating in libgit2, if it hasn't made its way to the natives package, it will shortly.
