### ISSUE TITLE
Move Repository.Reset(paths) into Index

### ISSUE THREAD

**Issue by dahlbyk** [libgit2/libgit2sharp#805]
As proposed in #799:

* [ ] Move `Repository.Reset(…, paths, …)` and related extensions to `Index`
* [ ] Add `Repository.ResetPaths(…)` and related extensions, deferring to new `Index` methods
* [ ] Mark `Repository.Reset(…, paths, …)` and related extensions as `[Obsolete]`, referring to either ResetPaths or Index.Reset.

**Comment by bording** [comment]
Looks like this still needs to be done. I'll take a look at it.

**Comment by nulltoken** [comment]
:cool: Labeled as `in-progress` then
