### ISSUE TITLE
[RFC] Turn the public Configuration ctor feature into GlobalSettings.Configuration property

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#809]
Currently, the `Configuration` type exposes a public constructor to allow one to get/set values from global/xdg/system configuration stores without having to instantiate a `Repository` instance.

Proposal would be to:
 - Create a `GlobalSettings.Configuration` property
 - Obsolete the public ctor with a message redirecting the user to the new way of accessing it
 - Drop the public ctor after next release

Thoughts?

**Comment by carlosmn** [comment]
We now let you specify the search paths globally. Moving a constructor to global would indicate that you'd only want a single configuration object, which is not something we want.
