### ISSUE TITLE
Repository.IsValid should not throw for null/empty argument

### ISSUE THREAD

**Issue by sharwell** [libgit2/libgit2sharp#818]
Currently `Repository.IsValid` throws an exception if the argument is null or empty. Rather than throw an exception, this method should simply return `false` in this case, similar to the behavior of [`Directory.Exists`](http://msdn.microsoft.com/en-us/library/system.io.directory.exists.aspx) or [`File.Exists`](http://msdn.microsoft.com/en-us/library/system.io.file.exists.aspx).

**Comment by nulltoken** [comment]
>I think I would lean towards IsValid returning errors if there is an error in determining whether a valid repository exists at a given path. If we want a function to determine if the current user can open a repository for a given string, maybe that is a separate function.

@jamill So if I understand you correctly, updating the xml documentation on the existing function, to reflect that exceptions could be thrown, would be enough?

**Comment by ethomson** [comment]
Passing `NULL` to this function is a bug, and we should continue to throw.  If we want to accept an empty string here (and always return `false`), I guess we can, but let's drop the stabilization tag for this.

**Comment by nulltoken** [comment]
Agreed.

So we should only

- throw on null arguments
- return false on `string.Empty`

Labeled as `up-for-grabs`

**Comment by kkaradag2** [comment]
try
           {
               if (Repository.IsValid(Repository.Discover(textBox1.Text)))               
               {
                   MessageBox.Show("ok");
               }
           }
           catch (Exception ex)
           {
               MessageBox.Show(string.Format("Folder {0} is not a Git Repository.", textBox1.Text), "Git Repository Not found");               
           }
