### ISSUE TITLE
Committing a git repository that contains another git repository throws an exception.

### ISSUE THREAD

**Issue by BlakeTNC** [libgit2/libgit2sharp#838]
If you try to commit a git repository that contains a different git repository (for example a code library) that has been copied into a subfolder, then libgit2sharp throws an exception that says LibGit2SharpException("requested file is a directory").

It took me forever to find out why my commit was failing…  catching this particular situation and throwing a more descriptive error would be more useful to the user. Maybe some error like, "A git repository was found in a subdirectory. Git repositories cannot be nested.".

Alternatively, the offending code could be modified so that ".git" folders in a subdirectory of the current commit are always ignored. (Or perhaps the git folder could simply be committed like any other file, it could be left up to the user to explicitly ignore them.). 

Blake

**Comment by carlosmn** [comment]
We should have fixed the underlying issue in libgit2, but this is a GHfW thing anyway, so closing.
