### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#847]
Help user with some information regarding the most efficient way to 

 - Report issues (library version, repro case, ...)
 - Contribute code

Below some potentially useful source of inspiration regarding potential structure, content or wording:

 - https://github.com/Haacked/SeeGit/blob/master/CONTRIBUTING.md
 - https://github.com/blog/1184-contributing-guidelines
 - https://github.com/dahlbyk/up-for-grabs.net/pull/14/files
 - https://github.com/contribute-md/contribute-md-template/blob/master/contribute.md
 - https://github.com/yeoman/yeoman/blob/master/contributing.md
 - https://github.com/dradis/dradisframework/blob/master/CONTRIBUTING.md
 - https://github.com/baconstarvation/flight-menu-example/blob/master/CONTRIBUTING.md
 - http://git.libssh2.org/?p=libssh2.git;a=blob;f=HACKING;h=5da8e66c23ae4e6cfc66560698b199ecb337750d;hb=HEAD;js=1
 - https://github.com/joyent/libuv/blob/master/CONTRIBUTING.md
 - https://github.com/MSOpenTech/ChassisManager/wiki/how-to-contribute
 - https://github.com/Pash-Project/Pash/blob/master/CONTRIBUTING.md
 - https://github.com/OneGet/oneget/blob/master/readme.md
 - http://www.snipe.net/2014/11/how-to-contribute-to-open-source-without-being-a-dick/
 - https://github.com/scriptcs/scriptcs/blob/master/CONTRIBUTING.md
 - https://github.com/Microsoft/dotnet/blob/master/CONTRIBUTING.md

**Comment by carlosmn** [comment]
Fixed via #887
