### ISSUE TITLE
Unable to install via NuGet in a .NET Core 4.5/4.5.1 environment

### ISSUE THREAD

**Issue by CruzBishop** [libgit2/libgit2sharp#874]
Hi,

I'm working on a terminal application for Windows 8.1 (and 10 once released), and one of the features I was looking to implement before a release was LibGit2Sharp integration if git isn't installed on the host computer.

When trying to install via Visual Studio 2012 / NuGet, I get the following

```
PM> Install-Package LibGit2Sharp
Installing 'LibGit2Sharp 0.20.0.0'.
Successfully installed 'LibGit2Sharp 0.20.0.0'.
Adding 'LibGit2Sharp 0.20.0.0' to Windows Advanced Shell.
Uninstalling 'LibGit2Sharp 0.20.0.0'.
Successfully uninstalled 'LibGit2Sharp 0.20.0.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'LibGit2Sharp 0.20.0.0'. You are trying to install this package into a project that targets '.NETCore,Version=v4.5.1', but the package 
does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package LibGit2Sharp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

Is there a way to bypass this, or does LibGit2Sharp not yet support .NET 4.5 and 4.5.1?

Thanks in advance :)

~Cruz

**Comment by jyrkij** [comment]
Any idea where to start with this? I'd be interested in getting git running for Windows and Windows Phone applications... I've checked out [jsgit](https://github.com/creationix/jsgit) but it seems quite difficult to implement - and requires ssh library for JS...

**Comment by omidkrad** [comment]
I'm also voting up supporting [.NET Core](https://dotnet.github.io/).

**Comment by carlosmn** [comment]
This isn't a question of voting. Someone needs to figure out if it supports what we need and whether there are changes we should do to support both. And then they need to act on that. There is an issue where the limitations are listed. Start there if you'd like to run this on core.

**Comment by carlosmn** [comment]
We don't support .NET Core, there's some information about what'd be necessary at #1019 and AFAICT we can't run on Windows Phone since we need to load a native DLL.

**Comment by AArnott** [comment]
Windows Phone Appx (wpa81) and UWP do support native DLLs. But I agree, that's not interesting as folks won't have git repos on their phones.

I'm keenly interested in this because MSBuild can now run on CoreCLR, so I want to port my MSBuild tasks to CoreCLR so they can run on Linux and Mac. But my MSBuild Task relies on libgit2sharp so I need it to be CoreCLR ready as well. The LibGit2Sharp.NativeBinaries package appears to already be Mac and Linux ready so hopefully it's just a matter of getting the managed code ready. 

In #1019 a missing `ICustomMarshaller` was mentioned. I haven't looked at your code to see if that's a blocking issue (or one that CoreFx has filled in during the last 9 months).

**Comment by AArnott** [comment]
I'm willing to take a look at converting libgit2sharp to a portable library that can run on CoreCLR. 
My exploration is in [the portable branch of my fork](https://github.com/aarnott/libgit2sharp/tree/portable).

**Comment by hickford** [comment]
Same problem. I added `"LibGit2Sharp": "0.22.0"` to my `project.json`

	>dotnet restore
	log  : Restoring packages for project.json...
	log  : Installing LibGit2Sharp.NativeBinaries 1.0.129.
	log  : Installing LibGit2Sharp 0.22.0.
	error: Package LibGit2Sharp 0.22.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package LibGit2Sharp 0.22.0 supports: net40 (.NETFramework,Version=v4.0)
	error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
	log  : Writing lock file to disk. Path: project.lock.json
	log  : project.json
	log  : Restore failed in 13359ms.

	Errors in project.json
	    Package LibGit2Sharp 0.22.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package LibGit2Sharp 0.22.0 supports: net40 (.NETFramework,Version=v4.0)
	    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by AArnott** [comment]
That's because it's not supported yet. See #1318

**Comment by Trolldemorted** [comment]
@AArnott why should users not have git repos on their phones? E.g. password managers can rely on git to sync and backup the password storage, and these definitely make sense on the windows phone. I'd like to create a [standard unix password manager](https://www.passwordstore.org/) version for windows phones/UWP, but i am unable to find a decent git library for UWP.

if loading native libs works, can we reopen this or #2925?

**Comment by AArnott** [comment]
IMO there are better solutions for synchronizing a data table across one user's devices than git. But it's not my call to reactivate the issue either way.

**Comment by ethomson** [comment]
@Trolldemorted I agree, git does not make a particularly good database.

But that is rather orthogonal to whether LibGit2Sharp should be able to run on a phone or not.  There's an issue discussing CoreCLR at https://github.com/libgit2/libgit2sharp/issues/1019, if you are able to help, I think that's a good place to start.

**Comment by Trolldemorted** [comment]
@ethomson Using git as a database or cdn might not be what git was intended to do, but it works like a charm as it supplies every needed aspect.

Please keep in mind that UWP is not just the windows phone, but also common windows desktops. Currently developers have to make a choice whether they want to use the windows store to distribute their app, or use libgit2sharp, which is imho terrible.

**Comment by ethomson** [comment]
> Using git as a database or cdn might not be what git was intended to do, but it works like a charm as it supplies every needed aspect.

Again, this is orthogonal to the issue at hand.

> Please keep in mind that UWP is not just the windows phone, but also common windows desktops. Currently developers have to make a choice whether they want to use the windows store to distribute their app, or use libgit2sharp, which imho is terrible.

Again, please help us improve it.  The first step is to make sure that the native dependency (libgit2) works on Windows Phone.  Have you tried this yet?  Does it work?  Why not?

**Comment by Trolldemorted** [comment]
@ethomson what do you consider "works"?

I [tested](https://gist.github.com/Trolldemorted/8d909ca7bac61afd5c80256805589380) `git_repository_init`, and it works fine.

Do you have anything specific in mind that would not work?

**Comment by ethomson** [comment]
@Trolldemorted That's good to know.  So it sounds like the only thing needed is support in LibGit2Sharp?  What is needed there?  Can you provide specific steps to help us provide the UWP and Windows Phone support that you want?

**Comment by Trolldemorted** [comment]
@ethomson I suppose so. Since i did not have a look at your codebase, i cannot tell you what changes are required better than you yourself, who has committed several thousand lines of code.

**Comment by carlosmn** [comment]
@Trolldemorted you're the one asking for support of this platform that _you_ are presumably interested in, so you're in the better position to see if things work. This project and the library itself both have test suites. Do they work when you compile them to run in this environment where you want to run them? If not, that's where you can start to see about the changes.
