### ISSUE TITLE
Native binairies not deploying using TFS Build and RemoteAgent

### ISSUE THREAD

**Issue by Allov** [libgit2/libgit2sharp#879]
Last version [used project properties files instead of custom build action](https://github.com/libgit2/libgit2sharp/pull/821). While this work fine when building or using the Publish action in Visual Studio 2013, it won't work at all using TFS build server.

So, publishing or building the project with Visual Studio will copy the `NativeBinaries` folder to the `bin` folder which is perfectly fine. But, using a TFS build deployment setup, the folder is never transfered over the server using the `RemoteAgent`.

MSBuild arguments:

    /p:DeployTarget=MsDeployPublish /p:Configuration=MEP-DEV /p:DeployOnBuild=True /p:CreatePackageOnPublish=False /p:MsDeployPublishMethod=RemoteAgent /p:AllowUntrustedCertificate=True

In the build log file, I can see that the Libgit2sharp NuGet package is being installed, but the libraries are not mentioned anywhere as if they are just ignored by the deployment process.

Also, I tried to create a custom target to copy the file over, but for some reason, the application pool is keeping an handle on the native libraries preventing the deployment process to delete said files until I recycle the pool or kill the process. This is the target instruction:

    <Target Name="BeforePublish">
        <Copy SourceFiles="$(SolutionDir)\NativeBinaries" DestinationFolder="$(OutputDir)\bin\NativeBinaries" ContinueOnError="true" />
    </Target>

**Comment by nulltoken** [comment]
@Allov Closing this now.  Feel free to add comment or reopen if needed.

Cheers!
