### ISSUE TITLE
Git merge conflict is not reflected in repo.RetrieveStatus()

### ISSUE THREAD

**Issue by TormodS** [libgit2/libgit2sharp#881]
git init
touch vvv.txt
git add vvv.txt;git commit -m "First checkin"
date >> vvv.txt
git add vvv.txt;git commit -m "RefOne"
git checkout HEAD^
date >> vvv.txt
git add vvv.txt;git commit -m "RefTwo"
git merge master

At this point you will have a merge conflict. "git status" will show "both modified". However, if you use libgit2sharp repo.Retrievestatus(), this file will read as Removed|Untracked

**Comment by ethomson** [comment]
Fixed via #1062
