### ISSUE TITLE
Maybe migrate to Mono 3.8

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#899]
This should allow us to apt get the packages directly from Xamarin download servers.

- http://www.mono-project.com/news/2014/09/04/mono-3-8-0-is-out/
- http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives

Thoughts?

/cc @Therzok @carlosmn

**Comment by nulltoken** [comment]
@Therzok Are there some public numbers regarding the number of Mono installs per version?

**Comment by Therzok** [comment]
Uuugh, don't think so. I'll ask around tomorrow. What reason would there be for going backwards? 3.12 will be released soon-ish.

**Comment by nulltoken** [comment]
>What reason would there be for going backwards?

Backwards? The readme advertizes Mono 3.6 (FWIW this is why I opened https://github.com/libgit2/libgit2sharp/pull/898).

**Comment by Therzok** [comment]
But what reason would there be not to use a newer Mono? Why not jump to 3.10?

**Comment by nulltoken** [comment]
Ensuring we work fine against the latest Mono makes sense. However, I think we should at least ensure we're still compatible with an older Mono 3.6.

Let's close this and migrate this discussion over to #898
