### ISSUE TITLE
Switch / Checkout Branch ist not working

### ISSUE THREAD

**Issue by Gentlehag** [libgit2/libgit2sharp#903]
I'm using Version 0.19
I've a remote branch named 'dev'

after cloning i want to switch to this branch.
i found some code which performs an update to the branch. but for me it doesn't work.
I also try to run a checkout after this which also doesnt work.

When viewing the git log after the code i see the changesets of the master branch. But the local branch name is the name of the given name for the created branch (e.G. "dev")

what am i doing wrong?
```csharp
    private static Branch SwitchBranch(Repository repo, RepositoryProperties properties)
        {
            string branchname = properties.Branch;
            Branch result = null;
            if (!string.IsNullOrWhiteSpace(properties.Branch))
            {
                Branch remote = null;
                foreach (var branch in repo.Branches)
                {
                    if (string.Equals(branch.Name, "origin/" + branchname))
                    {
                        remote = branch;
                        break;
                    }
                }

                string localBranchName = properties.Branch;
                Branch localbranch = repo.CreateBranch(localBranchName);

                Branch updatedBranch = repo.Branches.Update(localbranch,
                    b =>
                    {
                        b.TrackedBranch = remote.CanonicalName;
                    });

                repo.Checkout(updatedBranch);

                result = updatedBranch;
            }

            return result;
        }
```

**Comment by Gentlehag** [comment]
I posted the issue also on stackoverflow. so if someone is collection points he can get some ;) http://stackoverflow.com/questions/27826579/switch-checkout-branch-ist-not-working

**Comment by nulltoken** [comment]
>I posted the issue also on stackoverflow.

Thanks! Let's deal with this over there, then.

Indeed, as stated in the README, we tend to prefer to answer support questions on StackOverflow because the questions and answers can be much more easily found through search engines.
