### ISSUE TITLE
push changes to a GitLab repo over HTTPS with credentials

### ISSUE THREAD

**Issue by simcard** [libgit2/libgit2sharp#905]
Has anyone manage to push changes to GitLab repo over HTTPS with credentials?. I'm getting "Request failed with status code: 411" error.

**Comment by nulltoken** [comment]
@Yogu IIRC, you were also using GitLab, weren't you? Did you encounter such an issue?

**Comment by Yogu** [comment]
Yes, I was using libgit2sharp with GitLab a lot, and it worked. A handful google results indicate that it might be a problem with too large commits, they suggest [increasing the postBuffer config on the server](https://stackoverflow.com/questions/12651749/git-push-fails-rpc-failed-result-22-http-code-411).

**Comment by nulltoken** [comment]
@Yogu Thanks for the hint!

@simcard Can you repro this error with git command line?

**Comment by simcard** [comment]
@nulltoken Everything works fine with git command line.

**Comment by nulltoken** [comment]
@simcard Do you encounter this issue with all the GitLab hosted repos or only a particular one?

**Comment by simcard** [comment]
@nulltoken Yes with all the GitLab hosted repos. May you please give me an example on how to push changes, maybe I'm doing it wrong.
This is how I do it:
             Repository repo = new Repository(sourcepath);
             var remote = repo.Network.Remotes["origin"];
             var options = new PushOptions() {CredentialsProvider = (url, user, cred) => new                                       UsernamePasswordCredentials {Username = username, Password = password}};
             string pushRefSpec = @"refs/heads/master";
             repo.Network.Push(remote, pushRefSpec, options, new Signature(username, email,    DateTimeOffset.Now), "pushed changes");

**Comment by nulltoken** [comment]
@simcard Could you please change your pushrefspec to the following:

```csharp
string pushRefSpec = @"refs/heads/master:refs/heads/master";
```

**Comment by simcard** [comment]
@nulltoken Still getting the same error "Request failed with status code: 411".

**Comment by simcard** [comment]
Clone, commit, stage and fetch works fine, just push returning a 411 when debugging it gets to git_push_finish which returns -1

**Comment by ethomson** [comment]
Are you using gitlab.com or are you running gitlab on your own server?

If it's the latter, what software are you using to host it?  What do those server's logs say?

Are you using a proxy?

**Comment by simcard** [comment]
@nulltoken and @ethomson Hi guys I think the problem is with the library because it works fine with ngit.

**Comment by ethomson** [comment]
Different clients are going to speak differently.  Maybe ngit buffers everything and splats it all out as a giant POST.  (This is why people suggest tweaking `http.postBuffer`, though usually this is spoken of as a magical incantation without actually discussing what it performs, as if its mere setting is enough to right all wrongs in git network transfers.)

Your server is returning a 411 on its request.  Your server is returning a 200 on *a different request* from *a different client*.  Whether this is the client or the server at fault is not possible to determine knowing only that some other client works.

Knowing the answers to the above questions would help.  A fiddler or charles trace (or wireshark, if you're not using HTTP) would also be quite helpful.

**Comment by danielladd** [comment]
I ran into the same issue, seems to be specific to GitLab. I stood up a bitbucket repo and was able to push without issue:

http://stackoverflow.com/questions/31459188/unable-to-push-to-gitlab-endpoint-libgit2sharp 

Any extra information I can provide please let me know.

**Comment by whoisj** [comment]
Yes, a [Fiddler](http://www.telerik.com/fiddler) trace would be extremely useful.

**Comment by danielladd** [comment]
Sorry for the late response, after some more testing it looks like this has been fixed in newer versions of the gitlab omnibus community edition.

**Comment by simcard** [comment]
Woow that's great news.Thank you so much Guys.
