### ISSUE TITLE
CLS Compliance

### ISSUE THREAD

**Issue by Zoltu** [libgit2/libgit2sharp#906]
The AssemblyInfo file for LibGit2Sharp has
```
[assembly: CLSCompliant(true)]
```
However, there are a number of places in code where UIntPtr is used.  UIntPtr is not CLS compliant (no unsigned types are except for Byte I believe).  Is the library intended to be CLS compliant and there are just some outliers that need to be fixed or is it not and the attribute is incorrect (should be removed)?

**Comment by nulltoken** [comment]
@Zoltu IIRC the attribute is there to ensure the exposed API is CLS compliant for an external caller. So, it would only assess the public members of public types.

As a test, I've added the following function to the `Index`type.

```csharp
public virtual UIntPtr AmIClsCompliantOrNot()
{
      return UIntPtr.Zero;
}
```

Only the following warning were issued

```
1>F:\libgit2sharp\LibGit2Sharp\Index.cs(160,32,160,33): warning CS3002: Return type of 'LibGit2Sharp.Index.f()' is not CLS-compliant
1>F:\libgit2sharp\LibGit2Sharp\Index.cs(160,32,160,33): warning CS1591: Missing XML comment for publicly visible type or member 'LibGit2Sharp.Index.AmIClsCompliantOrNot()'
```

So, unless I've overlooked anything, we look ok on this front, aren't we?

**Comment by Zoltu** [comment]
Ah, okay. My mistake.
