### ISSUE TITLE
Deprecate Branch.Checkout()

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#924]
As discussed in https://github.com/libgit2/libgit2sharp/pull/840#issuecomment-71051879

`branch.Checkout()` modifies the external state (workdir, index and potentially the HEAD state). It may make sense to deprecate it in favor of `IRepository.Checkout()`

Thoughts?

**Comment by carlosmn** [comment]
Makes sense, as the checkout isn't an operation on a branch, but an operation on the repository/workdir. The branch is the argument which tells it what to use.

**Comment by bording** [comment]
Looks like this issue can be closed since it commits 19cd9f5c5ae4f65c5d22e9ed0dddd8898ff19c01 and aa70916bc3798948385967aaa1eff05c9378f758 took care of this already!

**Comment by nulltoken** [comment]
Thanks!
