### ISSUE TITLE
Expose the assume-unchanged flag to IndexEntry

### ISSUE THREAD

**Issue by zpete** [libgit2/libgit2sharp#928]
I couldn't find a way to find out whether a file is flagged as assume-unchanged. Am I missing something?
If there isn't an solution this could be a possible implementation:

`libgit2sharp/LibGit2Sharp/IndexEntry.cs`

 ```c#

...

private const ushort GIT_IDXENTRY_VALID = 0x8000;

/// <summary>
/// Whether the file is marked as assume-unchanged
/// </summary>
public bool AssumeUnchanged { get; private set; }
...

internal static IndexEntry BuildFromPtr( IndexEntrySafeHandle handle )
{
    if( handle == null || handle.IsZero )
    {
        return null;
    }

    GitIndexEntry entry = handle.MarshalAsGitIndexEntry();

    FilePath path = LaxFilePathMarshaler.FromNative( entry.Path );
            
    return new IndexEntry
    {
        AssumeUnchanged = (GIT_IDXENTRY_VALID & entry.Flags) == GIT_IDXENTRY_VALID,
        Path = path.Native,
        Id = entry.Id,
        StageLevel = Proxy.git_index_entry_stage(handle),
        Mode = (Mode)entry.Mode
    };
}
```

**Comment by nulltoken** [comment]
Neat! Would you fancy sending a Pull request with this addition?

**Comment by nulltoken** [comment]
As there's no way (yet?) to teach the index to "ignore" some files through LibGit2Sharp, I took the liberty of creating a test repository with a file marked as "assume-unchanged".

If you feel like sending a Pull request for this proposal, fetch from https://github.com/libgit2/libgit2sharp/tree/ntk/assume_unchanged which may be a good starting point and would allow you to easily cover your feature with some test coverage.

**Comment by zpete** [comment]
Thank you very much - I'll send you the Pull request.
