### ISSUE TITLE
Expose an Api that would allow low level `update-index` manipulation

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#930]
#928 makes the `IndexEntry` expose the `AssumeUnchanged` property.

Now, maybe would it be time to also unleash the full power of `git update-index` and allow one to dabble with those close-to-the-metal operations..

What would this Api look like? (One method with overloads, many differently named methods, an  `IndexUpdater`, ...?)

Thoughts?

**Comment by shiftkey** [comment]
This is relevant to my interests. Added to my bucket of things to investigate this week :metal:

**Comment by carlosmn** [comment]
We're now exposing `Index` as the data structure itself so that's the API itself. If there's missing features, send PRs or ask for them specifically.
