### ISSUE TITLE
Question: Pull remote using Ssh Key authentication 

### ISSUE THREAD

**Issue by JBaltika** [libgit2/libgit2sharp#944]
Hi guys,
I spend a couple hours  looking in docs and source code and I cannot find example or answer to this.
So a little bit context what i trying to accomplish:
1. Clone the Bitbucket private GIT repo with Source Tree (lets say develop or master branch) or just simply using msysgit
2. Write console(.exe) using libgit2sharp to pull from remote using Ssh key authentication
3. Set scheduled task to run exe in 5 min intervals

Any documentation or code snipped would help.

Thanks in advance
J.B

**Comment by nulltoken** [comment]
Hey @JBaltika. As stated in the **[README.md](https://github.com/libgit2/libgit2sharp#troubleshooting-and-support)**:

>Usage or programming related question? Post it on [StackOverflow][so] using the tag *libgit2sharp*

We'll gladly answer you over there! Indeed, we rather keep the issue tracker for bugs and features.

Cheers!
