### ISSUE TITLE
Move FindMergeBase() overloads to ObjectDatabase

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#951]
- [ ] Deprecate `IQueryableCommitLog.FindMergeBase()`
 - [ ] Move `CommitLog.FindMergeBase()` implementation to `ObjectDatabase.FindMergeBase()`
 - [ ] Make `CommitLog.FindMergeBase()` delegate to `ObjectDatabase.FindMergeBase()`
 - [ ] Deprecate `CommitLog.FindMergeBase()`

**Comment by bording** [comment]
I think this issue and #864 are the same thing. They both have the up for grabs tag, so would it be cool if I take a look at this? This looks like it should be pretty easy to revise, and I've been wanting to find a good entry point to contributing!

**Comment by bording** [comment]
I went ahead and gave it a try. If it's something you're ok with me doing, I'll open a PR for it.

If not, well no big deal, I still got to play around in the codebase a bit!

**Comment by jamill** [comment]
@bording Thanks and welcome to the project!

I think it would be great if this was something you wanted to take a look at! I haven't looked at the changes in detail, but if you wanted to open a PR, that would make it easier to proceed. Thanks!

**Comment by nulltoken** [comment]
>I think this issue and #864 are the same thing

@bording Indeed :blush:. I closed the other one, stole the description from it as it was more accurate and marked this one as in-progress.

It's all yours.

**Comment by nulltoken** [comment]
Fixed by #957
