### ISSUE TITLE
Remove default parameters from public API

### ISSUE THREAD

**Issue by jamill** [libgit2/libgit2sharp#952]

**Comment by ethomson** [comment]
Background: http://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/

(Thanks @Haacked !)

**Comment by jamill** [comment]
#779 also seems related

**Comment by Haacked** [comment]
Heh, #779 is directly related. :smile:

**Comment by nulltoken** [comment]
Once this is fixed, how about adding a test to MetaFixture ensuring that no parameter has a default value?

Related: https://msdn.microsoft.com/en-us/library/x0acewhc(v=vs.100).aspx

**Comment by nulltoken** [comment]
Being dealt with through #1031
