### ISSUE TITLE
Improve the Commit indexer xml doc

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#966]
It currently states

```
/// <summary>
/// Gets the <see cref="TreeEntry"/> pointed at by the <paramref name="relativePath"/> in the <see cref="Tree"/>.
/// </summary>
/// <param name="relativePath">The relative path to the <see cref="TreeEntry"/> from the <see cref="Commit"/> working directory.</param>
/// <returns><c>null</c> if nothing has been found, the <see cref="TreeEntry"/> otherwise.</returns>
```

 - `relativePath` usage is misleading. Maybe just `path`?
 - `working directory` makes no sense from a `Commit` standpoint. Maybe just `root`?

**Comment by carlosmn** [comment]
Naming it "path" and changing the comment to something like

>Path to the TreeEntry from the root tree

or

>Path to the TreeEntry from the tree in this commit

should cover both situations ("root tree" and "tree in this commit" are equivalent concepts).

**Comment by nulltoken** [comment]
>Path to the TreeEntry from the tree in this commit

:+1:
