### ISSUE TITLE
API only takes constant Signatures

### ISSUE THREAD

**Issue by jamill** [libgit2/libgit2sharp#967]
Several operations that can generate commit(s) or modify the reflog take a `Signature` argument to specify the signature to use. A limitation of these APIs is that the `Signature` object includes a specific time stamp to use, which might not be desirable for operations where the commit generated could come some time after the operation was actually initiated. For instance, the commit generated by a merge or a pull can come a long time after the `Signature` was generated to use for the commit.

With rebase, this situation is even worse. We can generate N commits, each with the same time stamp.

The API should allow a user to specify either a "constant" signature to use (this is useful for tests or where a client would want to specify a specific time?), or to just specify a name and email field, where we can generate a timestamp that is closer in time to the actual commit.

Two ideas (with a very rough sketch of the API change):

1) Create an `ISignature` interface that exposes properties to get a Name, Email, and When properties to generate a signature used for operations. The current `Signature` type could then just implement this interface, so the existing API structure stays the same. Another type could then implement the functionality to return the "current" time (e.g. 5451eda)

2) Create a new `SignatureGenerator` class, which can know how to generate signatures for use with these operations. We could then have a `ConstantSignatureGenerator` and a `CurrentTimeSignatureGenerator` (e.g. fbb497c). We could add an overload so that there is not a break in the existing API.

/cc @nulltoken @ethomson

**Comment by Therzok** [comment]
Heya, for reference, we should take this into account before doing any major change:
https://github.com/libgit2/libgit2/pull/2808

**Comment by nulltoken** [comment]
@Therzok Agreed. FWIW libgit2/libgit2#2808 has just been rebased. It's waiting for @ethomson's feedback.

@jamill How about a `IIdentity` which would expose `name` and `email` for the purpose of `Rebase`?

We could also create a `ISignature` (deriving from `IIdentity`) and exposing `When`. However, if we go down this road, I'd prefer modify the signature of every method that currently accepts a `Signature` to rather accept a `ISignature`.

**Comment by jamill** [comment]
@nulltoken: Do we want all methods to only take an `IIdentity` or an `ISignature`? I can see cases where it would be useful to specify one or the other. Most of the time, I don't think consumers will care about specifying the `When` property, but I can where it might be useful (and in testing, it is very useful). Do we want our methods to be able to take either an `IIdentity` or an `ISignature`?

One option was that everything takes an `ISignature`, but depending on the implementation of the `ISignature`, you will either get a new up-to-date `When` time when the commit was actually created, or you would get the constant time passed in (or whatever time your ISignature returns).

> However, if we go down this road, I'd prefer modify the signature of every method that currently accepts a  Signature  to rather accept a  ISignature .

Yep - I agree, I think we should be consistent.

I plan to leave this issue open, and will come back to it after Rebase is merged.

**Comment by nulltoken** [comment]
I think this is no longer an issue nwo that the `Identity` type has been introduced, isn't it?

**Comment by nulltoken** [comment]
@jamill Can we close this one now? Or is it still relevant?

**Comment by nulltoken** [comment]
@jamill Ping?

**Comment by nulltoken** [comment]
@jamill Closing this for now as I *think* this is no longer required. Please, reopen it would I be mistaken
