### ISSUE TITLE
How to push with credentials?

### ISSUE THREAD

**Issue by ollytheninja** [libgit2/libgit2sharp#978]
So I've picked this library up today for a project and figured out how to do most of the things I need to do!
I've seen #104 and a few other issues, but still can't figure out how to provide credentials for a push.

Could someone give me a quick-and-dirty example? 
In return I can add some documentation to the wiki in the next week or two on push and a few other things I've figured out that aren't in documentation yet.

**Comment by nulltoken** [comment]
Hey @ollytheninja. As stated in the **[README.md](https://github.com/libgit2/libgit2sharp#troubleshooting-and-support)**:

>Usage or programming related question? Post it on [StackOverflow][so] using the tag *libgit2sharp*

We'll gladly answer you over there! Indeed, we rather keep the issue tracker for bugs and features.

>I can add some documentation to the wiki in the next week or two on push and a few other things I've figured out that aren't in documentation yet.

Awesome!
