### ISSUE TITLE
Expose a way to list remote references without having to go through a repository instance

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#985]
Related:

- https://stackoverflow.com/questions/28758954/how-do-i-run-ls-remote-in-libgit2sharp-without-a-repository
- https://github.com/libgit2/libgit2/issues/2923

**Comment by carlosmn** [comment]
The quick'n'dirty way would be go create a `git_repository_new()` instance with possibly a dummy odb, but I haven't tested it yet.

**Comment by JIghtuse** [comment]
I'm trying to solve this problem and I have a few questions, mostly about implementation details

* Is it possible create git_repository just from remote url?
* Is there a way to extract information from remote host now (without clone), or should I implement it too?

**Comment by JIghtuse** [comment]
Oh, I thought it is libgit2 repo. Sorry for confusing, please ignore my previous comment.

**Comment by nulltoken** [comment]
Fixed by #1065
