### ISSUE TITLE
Leverage Coverity scan on AppVeyor

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2sharp#986]
Related https://github.com/appveyor/ci/issues/144

**Comment by nulltoken** [comment]
Very interesting leads:

- http://help.appveyor.com/discussions/suggestions/497-coverity-static-analysis-support
- https://arkfps.github.io/2015/01/07/using-coverity-scan-with-appveyor/
- https://github.com/csMACnz/coveritypublisher/blob/master/build.tasks.ps1
- https://www.nuget.org/packages/PublishCoverity

**Comment by KindDragon** [comment]
:+1:
