### ISSUE TITLE
Repository suddenly broken

### ISSUE THREAD

**Issue by GeertvanHorrik** [libgit2/libgit2sharp#993]
I have been using GitVersion and GitLink for a long time on a repository, and suddenly something broke (but only on that repository):

https://github.com/WildGums/Orc.FilterBuilder

To test this, simply try to clone:

```
            Repository.Clone("https://github.com/WildGums/Orc.FilterBuilder", gitDirectory,
                new CloneOptions
                {
                    IsBare = true,
                    Checkout = false,
                });
```

It will result in the following error:

![image](https://cloud.githubusercontent.com/assets/1246444/6635989/fbee895c-c96b-11e4-8b10-1ded275d58ae.png)

btw. it would be nice if libgit2sharp would support GitLink (https://github.com/CatenaLogic/GitLink), then everyone can step through the source code ;-)

**Comment by nulltoken** [comment]
@GeertvanHorrik I'll take a look at this this evening (UTC+1).

Regarding GitLink, would you feel as sending a Pull Request so we can discuss this more broadly?

**Comment by GeertvanHorrik** [comment]
Yep. I already looked into it, but you have travis / appveyor. Which one should I fix?

**Comment by nulltoken** [comment]
>Which one should I fix?

I'm not sure what "fix" refers to.... :confounded:

**Comment by GeertvanHorrik** [comment]
For which build script should I implement GitLink support?

**Comment by nulltoken** [comment]
Both ;-)

Current NuGet packages are generated by AppVeyor and only embed Windows binaries. However, @bording is working on packaging the Mac Os X and Linux binaries (cf. #984)

**Comment by GeertvanHorrik** [comment]
Looks like I am having issues cloning any repository from GitHub at the moment. Even cloning my fork of libgit2sharp fails in SourceTree.

**Comment by GeertvanHorrik** [comment]
I am glad the existing clone unit tests fail as well, I am not the only one having this issue :)

**Comment by GeertvanHorrik** [comment]
Do you always build libgit2 yourself? Or can I get the binaries somewhere?

**Comment by nulltoken** [comment]
See https://github.com/libgit2/libgit2sharp/blob/vNext/UpdateLibgit2ToSha.ps1

**Comment by GeertvanHorrik** [comment]
Thanks. Also contacted GitHub because it seems to be broken inside libgit2 (which means they might have updated their git version as a breaking change?). Will try to check what's wrong in libgit2 as well (but this problem is becoming quite big: sln won't build => check gitversion => check libgit2sharp => check libgit2). It's a bit out of scope for today ;-)

**Comment by ethomson** [comment]
Thanks for the report!  We have worked with GitHub and they have made some changes to the service.  (We are improving libgit2 to give better error messages in this case.)

**Comment by GeertvanHorrik** [comment]
Does that mean GitHub did a fix or you did a fix?

**Comment by ethomson** [comment]
GitHub.

**Comment by GeertvanHorrik** [comment]
It's confirmed fixed, thanks!
