### ISSUE TITLE
Disposing of repository

### ISSUE THREAD

**Issue by rafalFurman** [libgit2/libgit2sharp#998]
Consider following program:

    var path = Path.Combine(
        Path.GetTempPath(),
        Path.GetFileNameWithoutExtension(Path.GetRandomFileName()));
    Directory.CreateDirectory(path);
    
    var testFile = Path.Combine(path, "test.txt");
    File.WriteAllText(testFile, "Test file");
    
    var source = Repository.Init(path);
    
    using (var repository = new Repository(source))
    {
        repository.Index.Add("test.txt");
    }
            
    Directory.Delete(path, true); 

On deletion of repository folder I get an UnauthorizedAccessException - access to one of internal git files is denied. Is there anything else I should dispose of in order to delete the folder?

**Comment by nulltoken** [comment]
@rafalFurman We tend to keep the issue tracker for bug and feature related topics. 

Would you be so kind as to ask this on **[StackOverflow](http://stackoverflow.com/questions/tagged/libgit2sharp)** and decorate your question with the `libgit2sharp` tag? We'll gladly answer you over there.

Cheers!

**Comment by rafalFurman** [comment]
as requested
http://stackoverflow.com/questions/29098942/deletion-of-git-repository

**Comment by nulltoken** [comment]
>as requested
http://stackoverflow.com/questions/29098942/deletion-of-git-repository

@rafalFurman Thanks a lot for this. :sparkles:
